# Generated by Django 5.2.16 on 2026-09-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32)),
                ('is_reference', models.BooleanField(default=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_packages', to='cookbook.food')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuaderno_packages', to='cookbook.space')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_packages', to='cookbook.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('explicit_free', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='cuaderno.packageformat')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuaderno_prices', to='cookbook.space')),
            ],
            options={
                'ordering': ('-valid_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SpaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(choices=[('esencial', 'Esencial'), ('profesional', 'Profesional'), ('integral', 'Integral')], default='esencial', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('price_policy', models.CharField(blank=True, choices=[('', 'Sin elegir'), ('net', 'Neto'), ('gross', 'Bruto')], default='', max_length=16)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuaderno_profile', to='cookbook.space')),
            ],
            options={
                'verbose_name': 'perfil de cuaderno',
            },
        ),
        migrations.AddConstraint(
            model_name='packageformat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('space', 'food'), name='cuaderno_one_reference_package_per_food'),
        ),
        migrations.AddIndex(
            model_name='priceversion',
            index=models.Index(fields=['package', 'valid_from'], name='cuaderno_pr_package_c265a4_idx'),
        ),
    ]
