# Generated by Django 5.2.16 on 2026-09-29 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
        ('cuaderno', '0011_service_household'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('explicit_free', models.BooleanField(default=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency_snapshot',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.household'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuaderno.packageformat'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='package_count',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='package_quantity_snapshot',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='package_unit_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_order_package_units', to='cookbook.unit'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_quantity',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(
                choices=[('draft', 'Borrador'), ('ordered', 'Pedido'), ('part_received', 'Recibido parcialmente'),
                         ('received', 'Recibido'), ('cancelled', 'Cancelado')],
                db_index=True, default='draft', max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.supermarket'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cuaderno_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(
                condition=models.Q(('received_quantity__gte', 0), ('received_quantity__lte', models.F('quantity'))),
                name='cuaderno_order_received_bounds',
            ),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(
                condition=models.Q(('state__in', ['draft', 'ordered', 'part_received', 'received', 'cancelled'])),
                name='cuaderno_order_valid_state',
            ),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='cuaderno.packageformat'),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_offers', to='cookbook.supermarket'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.inventoryentry'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt', to='cuaderno.stockmovement'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cuaderno.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_reversal', to='cuaderno.stockmovement'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
        migrations.AddIndex(
            model_name='purchaseoffer',
            index=models.Index(fields=['package', 'supplier', 'valid_from'], name='cuaderno_offer_supplier_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseoffer',
            constraint=models.CheckConstraint(
                condition=models.Q(('amount__gt', 0), models.Q(('amount', 0), ('explicit_free', True)), _connector='OR'),
                name='cuaderno_offer_explicit_price',
            ),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('space', 'idempotency_key'), name='cuaderno_receipt_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cuaderno_receipt_positive'),
        ),
    ]
