# Generated by Django 5.2.17 on 2026-10-04 01:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def check_existing_integrity(apps, schema_editor):
    """Report invalid historical rows without inventing or deleting business data."""
    checks = (
        ('PackageFormat', models.Q(quantity__lte=0)),
        ('RecipeYield', models.Q(quantity__lte=0)),
        ('ServicePlan', models.Q(covers__lte=0) | ~models.Q(state__in=('draft', 'confirmed', 'produced', 'cancelled'))),
        ('SpaceProfile', models.Q(target_food_cost_ratio__lte=0) | models.Q(target_food_cost_ratio__gt=1)),
        ('StockMovement', models.Q(quantity__lte=0) | ~models.Q(kind__in=('receipt', 'consume', 'waste')) | models.Q(reverses_id=models.F('pk'))),
        ('AllergenDeclaration', ~models.Q(state__in=('declared', 'unknown'))),
    )
    problems = []
    for name, invalid in checks:
        rows = apps.get_model('cuaderno', name)._base_manager.using(schema_editor.connection.alias).filter(invalid)
        count = rows.count()
        if count:
            problems.append(f'{name}: {count} filas; IDs de ejemplo: {list(rows.values_list("pk", flat=True)[:20])}')
    if problems:
        raise RuntimeError('Integridad de Cuaderno: revisa y corrige estos datos antes de migrar (no se han modificado): ' + '; '.join(problems))


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0243_ingredient_yield_policy'),
        ('cuaderno', '0016_servicepreparationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_existing_integrity, migrations.RunPython.noop),
        migrations.AddField(
            model_name='allergendeclaration',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allergendeclaration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='allergendeclaration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='priceversion',
            index=models.Index(fields=['space', 'package', '-valid_from', '-id'], include=('amount', 'explicit_free'), name='cuaderno_price_current_cover'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['space', '-id'], name='cuaderno_movement_space_id'),
        ),
        migrations.AddConstraint(
            model_name='allergendeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('declared', 'unknown'))), name='cuaderno_allergen_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='packageformat',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cuaderno_package_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='recipeyield',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cuaderno_yield_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.CheckConstraint(condition=models.Q(('covers__gt', 0)), name='cuaderno_service_positive_covers'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'confirmed', 'produced', 'cancelled'))), name='cuaderno_service_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='spaceprofile',
            constraint=models.CheckConstraint(condition=models.Q(('target_food_cost_ratio__isnull', True), models.Q(('target_food_cost_ratio__gt', 0), ('target_food_cost_ratio__lte', 1)), _connector='OR'), name='cuaderno_profile_target_ratio'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cuaderno_movement_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('receipt', 'consume', 'waste'))), name='cuaderno_movement_valid_kind'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reverses', models.F('pk')), _negated=True), name='cuaderno_movement_no_self_reversal'),
        ),
    ]
