# Generated by Django 5.2.17 on 2026-10-10 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0245_cuaderno_theme_labels'),
        ('cuaderno', '0019_food_and_menu_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('service_date', models.DateField(db_index=True)),
                ('service_time', models.TimeField()),
                ('template_day', models.PositiveSmallIntegerField(default=0)),
                ('covers', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('in_kitchen', 'En cocina'), ('served', 'Servida'), ('cancelled', 'Anulada')], db_index=True, default='requested', max_length=16)),
                ('menu_snapshot', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.household')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.mealtype')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuaderno.menutemplate')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuaderno_reservations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('service_date', 'service_time', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ReservationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='cuaderno.customerreservation')),
            ],
            options={
                'ordering': ('revision', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_links', to='cuaderno.customerreservation')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_link', to='cuaderno.serviceplan')),
            ],
            options={
                'ordering': ('revision', 'position', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='customerreservation',
            index=models.Index(fields=['space', 'service_date', 'state'], name='cuaderno_reservation_day'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('covers__gte', 1), ('covers__lte', 9999)), name='cuaderno_reservation_covers'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('template_day__lte', 34)), name='cuaderno_reservation_menu_day'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='cuaderno_reservation_revision'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), ('phone', ''), _negated=True), name='cuaderno_reservation_contact'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('requested', 'confirmed', 'in_kitchen', 'served', 'cancelled'))), name='cuaderno_reservation_state'),
        ),
        migrations.AddConstraint(
            model_name='reservationrevision',
            constraint=models.UniqueConstraint(fields=('reservation', 'revision'), name='cuaderno_reservation_history'),
        ),
        migrations.AddConstraint(
            model_name='reservationservice',
            constraint=models.UniqueConstraint(fields=('reservation', 'revision', 'position'), name='cuaderno_reservation_dish'),
        ),
    ]
