/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenRequest
 */
export interface AccessTokenRequest {
    /**
     * 
     * @type {Date}
     * @memberof AccessTokenRequest
     */
    expires: Date;
    /**
     * 
     * @type {string}
     * @memberof AccessTokenRequest
     */
    scope?: string;
    /**
     * 
     * @type {number}
     * @memberof AccessTokenRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the AccessTokenRequest interface.
 */
export function instanceOfAccessTokenRequest(value: object): value is AccessTokenRequest {
    if (!('expires' in value) || value['expires'] === undefined) return false;
    return true;
}

export function AccessTokenRequestFromJSON(json: any): AccessTokenRequest {
    return AccessTokenRequestFromJSONTyped(json, false);
}

export function AccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expires': (new Date(json['expires'])),
        'scope': json['scope'] == null ? undefined : json['scope'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AccessTokenRequestToJSON(json: any): AccessTokenRequest {
    return AccessTokenRequestToJSONTyped(json, false);
}

export function AccessTokenRequestToJSONTyped(value?: AccessTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires': value['expires'].toISOString(),
        'scope': value['scope'],
        'id': value['id'],
    };
}

