/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllergenDeclarationSchema } from './AllergenDeclarationSchema';
import {
    AllergenDeclarationSchemaFromJSON,
    AllergenDeclarationSchemaFromJSONTyped,
    AllergenDeclarationSchemaToJSON,
    AllergenDeclarationSchemaToJSONTyped,
} from './AllergenDeclarationSchema';

/**
 * 
 * @export
 * @interface AllergenFoodSchema
 */
export interface AllergenFoodSchema {
    /**
     * 
     * @type {number}
     * @memberof AllergenFoodSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AllergenFoodSchema
     */
    name: string;
    /**
     * 
     * @type {Array<AllergenDeclarationSchema>}
     * @memberof AllergenFoodSchema
     */
    declarations: Array<AllergenDeclarationSchema>;
}

/**
 * Check if a given object implements the AllergenFoodSchema interface.
 */
export function instanceOfAllergenFoodSchema(value: object): value is AllergenFoodSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('declarations' in value) || value['declarations'] === undefined) return false;
    return true;
}

export function AllergenFoodSchemaFromJSON(json: any): AllergenFoodSchema {
    return AllergenFoodSchemaFromJSONTyped(json, false);
}

export function AllergenFoodSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllergenFoodSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'declarations': ((json['declarations'] as Array<any>).map(AllergenDeclarationSchemaFromJSON)),
    };
}

export function AllergenFoodSchemaToJSON(json: any): AllergenFoodSchema {
    return AllergenFoodSchemaToJSONTyped(json, false);
}

export function AllergenFoodSchemaToJSONTyped(value?: AllergenFoodSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'declarations': ((value['declarations'] as Array<any>).map(AllergenDeclarationSchemaToJSON)),
    };
}

