/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `food` - food
 * * `recipe` - recipe
 * @export
 */
export const AllergenScopeSchemaTypeEnum = {
    Food: 'food',
    Recipe: 'recipe'
} as const;
export type AllergenScopeSchemaTypeEnum = typeof AllergenScopeSchemaTypeEnum[keyof typeof AllergenScopeSchemaTypeEnum];


export function instanceOfAllergenScopeSchemaTypeEnum(value: any): boolean {
    for (const key in AllergenScopeSchemaTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(AllergenScopeSchemaTypeEnum, key)) {
            if (AllergenScopeSchemaTypeEnum[key as keyof typeof AllergenScopeSchemaTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AllergenScopeSchemaTypeEnumFromJSON(json: any): AllergenScopeSchemaTypeEnum {
    return AllergenScopeSchemaTypeEnumFromJSONTyped(json, false);
}

export function AllergenScopeSchemaTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllergenScopeSchemaTypeEnum {
    return json as AllergenScopeSchemaTypeEnum;
}

export function AllergenScopeSchemaTypeEnumToJSON(value?: AllergenScopeSchemaTypeEnum | null): any {
    return value as any;
}

export function AllergenScopeSchemaTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AllergenScopeSchemaTypeEnum {
    return value as AllergenScopeSchemaTypeEnum;
}

