/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllergenScopeSchemaTypeEnum } from './AllergenScopeSchemaTypeEnum';
import {
    AllergenScopeSchemaTypeEnumFromJSON,
    AllergenScopeSchemaTypeEnumFromJSONTyped,
    AllergenScopeSchemaTypeEnumToJSON,
    AllergenScopeSchemaTypeEnumToJSONTyped,
} from './AllergenScopeSchemaTypeEnum';

/**
 * 
 * @export
 * @interface AllergenScopeSchema
 */
export interface AllergenScopeSchema {
    /**
     * 
     * @type {AllergenScopeSchemaTypeEnum}
     * @memberof AllergenScopeSchema
     */
    type: AllergenScopeSchemaTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AllergenScopeSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AllergenScopeSchema
     */
    name: string;
}



/**
 * Check if a given object implements the AllergenScopeSchema interface.
 */
export function instanceOfAllergenScopeSchema(value: object): value is AllergenScopeSchema {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AllergenScopeSchemaFromJSON(json: any): AllergenScopeSchema {
    return AllergenScopeSchemaFromJSONTyped(json, false);
}

export function AllergenScopeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllergenScopeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'type': AllergenScopeSchemaTypeEnumFromJSON(json['type']),
        'id': json['id'],
        'name': json['name'],
    };
}

export function AllergenScopeSchemaToJSON(json: any): AllergenScopeSchema {
    return AllergenScopeSchemaToJSONTyped(json, false);
}

export function AllergenScopeSchemaToJSONTyped(value?: AllergenScopeSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': AllergenScopeSchemaTypeEnumToJSON(value['type']),
        'id': value['id'],
        'name': value['name'],
    };
}

