/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeywordModeEnum } from './KeywordModeEnum';
import {
    KeywordModeEnumFromJSON,
    KeywordModeEnumFromJSONTyped,
    KeywordModeEnumToJSON,
    KeywordModeEnumToJSONTyped,
} from './KeywordModeEnum';
import type { UserRequest } from './UserRequest';
import {
    UserRequestFromJSON,
    UserRequestFromJSONTyped,
    UserRequestToJSON,
    UserRequestToJSONTyped,
} from './UserRequest';

/**
 * 
 * @export
 * @interface AutoMealPlanRequest
 */
export interface AutoMealPlanRequest {
    /**
     * 
     * @type {Date}
     * @memberof AutoMealPlanRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof AutoMealPlanRequest
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof AutoMealPlanRequest
     */
    mealTypeId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof AutoMealPlanRequest
     */
    keywords?: Array<number>;
    /**
     * 
     * @type {KeywordModeEnum}
     * @memberof AutoMealPlanRequest
     */
    keywordMode?: KeywordModeEnum;
    /**
     * 
     * @type {number}
     * @memberof AutoMealPlanRequest
     */
    servings: number;
    /**
     * 
     * @type {Array<UserRequest>}
     * @memberof AutoMealPlanRequest
     */
    shared?: Array<UserRequest> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AutoMealPlanRequest
     */
    addshopping: boolean;
}



/**
 * Check if a given object implements the AutoMealPlanRequest interface.
 */
export function instanceOfAutoMealPlanRequest(value: object): value is AutoMealPlanRequest {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('mealTypeId' in value) || value['mealTypeId'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('addshopping' in value) || value['addshopping'] === undefined) return false;
    return true;
}

export function AutoMealPlanRequestFromJSON(json: any): AutoMealPlanRequest {
    return AutoMealPlanRequestFromJSONTyped(json, false);
}

export function AutoMealPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoMealPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'mealTypeId': json['meal_type_id'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'keywordMode': json['keyword_mode'] == null ? undefined : KeywordModeEnumFromJSON(json['keyword_mode']),
        'servings': json['servings'],
        'shared': json['shared'] == null ? undefined : ((json['shared'] as Array<any>).map(UserRequestFromJSON)),
        'addshopping': json['addshopping'],
    };
}

export function AutoMealPlanRequestToJSON(json: any): AutoMealPlanRequest {
    return AutoMealPlanRequestToJSONTyped(json, false);
}

export function AutoMealPlanRequestToJSONTyped(value?: AutoMealPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_date': value['startDate'].toISOString(),
        'end_date': value['endDate'].toISOString(),
        'meal_type_id': value['mealTypeId'],
        'keywords': value['keywords'],
        'keyword_mode': KeywordModeEnumToJSON(value['keywordMode']),
        'servings': value['servings'],
        'shared': value['shared'] == null ? undefined : ((value['shared'] as Array<any>).map(UserRequestToJSON)),
        'addshopping': value['addshopping'],
    };
}

