/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarEntryKindEnum } from './CalendarEntryKindEnum';
import {
    CalendarEntryKindEnumFromJSON,
    CalendarEntryKindEnumFromJSONTyped,
    CalendarEntryKindEnumToJSON,
    CalendarEntryKindEnumToJSONTyped,
} from './CalendarEntryKindEnum';

/**
 * 
 * @export
 * @interface CalendarWriteSchemaRequest
 */
export interface CalendarWriteSchemaRequest {
    /**
     * 
     * @type {CalendarEntryKindEnum}
     * @memberof CalendarWriteSchemaRequest
     */
    kind: CalendarEntryKindEnum;
    /**
     * 
     * @type {string}
     * @memberof CalendarWriteSchemaRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarWriteSchemaRequest
     */
    memberName?: string;
    /**
     * 
     * @type {Date}
     * @memberof CalendarWriteSchemaRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CalendarWriteSchemaRequest
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CalendarWriteSchemaRequest
     */
    note?: string;
}



/**
 * Check if a given object implements the CalendarWriteSchemaRequest interface.
 */
export function instanceOfCalendarWriteSchemaRequest(value: object): value is CalendarWriteSchemaRequest {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function CalendarWriteSchemaRequestFromJSON(json: any): CalendarWriteSchemaRequest {
    return CalendarWriteSchemaRequestFromJSONTyped(json, false);
}

export function CalendarWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': CalendarEntryKindEnumFromJSON(json['kind']),
        'title': json['title'],
        'memberName': json['member_name'] == null ? undefined : json['member_name'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CalendarWriteSchemaRequestToJSON(json: any): CalendarWriteSchemaRequest {
    return CalendarWriteSchemaRequestToJSONTyped(json, false);
}

export function CalendarWriteSchemaRequestToJSONTyped(value?: CalendarWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': CalendarEntryKindEnumToJSON(value['kind']),
        'title': value['title'],
        'member_name': value['memberName'],
        'start_date': value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'].toISOString().substring(0,10),
        'note': value['note'],
    };
}

