/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `event` - event
 * * `absence` - absence
 * @export
 */
export const CalendarEntryKindEnum = {
    Event: 'event',
    Absence: 'absence'
} as const;
export type CalendarEntryKindEnum = typeof CalendarEntryKindEnum[keyof typeof CalendarEntryKindEnum];


export function instanceOfCalendarEntryKindEnum(value: any): boolean {
    for (const key in CalendarEntryKindEnum) {
        if (Object.prototype.hasOwnProperty.call(CalendarEntryKindEnum, key)) {
            if (CalendarEntryKindEnum[key as keyof typeof CalendarEntryKindEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CalendarEntryKindEnumFromJSON(json: any): CalendarEntryKindEnum {
    return CalendarEntryKindEnumFromJSONTyped(json, false);
}

export function CalendarEntryKindEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarEntryKindEnum {
    return json as CalendarEntryKindEnum;
}

export function CalendarEntryKindEnumToJSON(value?: CalendarEntryKindEnum | null): any {
    return value as any;
}

export function CalendarEntryKindEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CalendarEntryKindEnum {
    return value as CalendarEntryKindEnum;
}

