/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarEntryKindEnum } from './CalendarEntryKindEnum';
import {
    CalendarEntryKindEnumFromJSON,
    CalendarEntryKindEnumFromJSONTyped,
    CalendarEntryKindEnumToJSON,
    CalendarEntryKindEnumToJSONTyped,
} from './CalendarEntryKindEnum';

/**
 * 
 * @export
 * @interface CalendarUpdateSchemaRequest
 */
export interface CalendarUpdateSchemaRequest {
    /**
     * 
     * @type {CalendarEntryKindEnum}
     * @memberof CalendarUpdateSchemaRequest
     */
    kind: CalendarEntryKindEnum;
    /**
     * 
     * @type {string}
     * @memberof CalendarUpdateSchemaRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarUpdateSchemaRequest
     */
    memberName?: string;
    /**
     * 
     * @type {Date}
     * @memberof CalendarUpdateSchemaRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CalendarUpdateSchemaRequest
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CalendarUpdateSchemaRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarUpdateSchemaRequest
     */
    revision: string;
}



/**
 * Check if a given object implements the CalendarUpdateSchemaRequest interface.
 */
export function instanceOfCalendarUpdateSchemaRequest(value: object): value is CalendarUpdateSchemaRequest {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function CalendarUpdateSchemaRequestFromJSON(json: any): CalendarUpdateSchemaRequest {
    return CalendarUpdateSchemaRequestFromJSONTyped(json, false);
}

export function CalendarUpdateSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarUpdateSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': CalendarEntryKindEnumFromJSON(json['kind']),
        'title': json['title'],
        'memberName': json['member_name'] == null ? undefined : json['member_name'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'note': json['note'] == null ? undefined : json['note'],
        'revision': json['revision'],
    };
}

export function CalendarUpdateSchemaRequestToJSON(json: any): CalendarUpdateSchemaRequest {
    return CalendarUpdateSchemaRequestToJSONTyped(json, false);
}

export function CalendarUpdateSchemaRequestToJSONTyped(value?: CalendarUpdateSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': CalendarEntryKindEnumToJSON(value['kind']),
        'title': value['title'],
        'member_name': value['memberName'],
        'start_date': value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'].toISOString().substring(0,10),
        'note': value['note'],
        'revision': value['revision'],
    };
}

