/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
    StatusEnumToJSONTyped,
} from './StatusEnum';

/**
 * 
 * @export
 * @interface CostLineSchema
 */
export interface CostLineSchema {
    /**
     * 
     * @type {StatusEnum}
     * @memberof CostLineSchema
     */
    status: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CostLineSchema
     */
    unrounded: string | null;
    /**
     * 
     * @type {string}
     * @memberof CostLineSchema
     */
    display: string | null;
    /**
     * 
     * @type {string}
     * @memberof CostLineSchema
     */
    knownSubtotal: string | null;
    /**
     * 
     * @type {string}
     * @memberof CostLineSchema
     */
    total: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CostLineSchema
     */
    warnings: Array<string>;
}



/**
 * Check if a given object implements the CostLineSchema interface.
 */
export function instanceOfCostLineSchema(value: object): value is CostLineSchema {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('unrounded' in value) || value['unrounded'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('knownSubtotal' in value) || value['knownSubtotal'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    return true;
}

export function CostLineSchemaFromJSON(json: any): CostLineSchema {
    return CostLineSchemaFromJSONTyped(json, false);
}

export function CostLineSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostLineSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusEnumFromJSON(json['status']),
        'unrounded': json['unrounded'],
        'display': json['display'],
        'knownSubtotal': json['known_subtotal'],
        'total': json['total'],
        'warnings': json['warnings'],
    };
}

export function CostLineSchemaToJSON(json: any): CostLineSchema {
    return CostLineSchemaToJSONTyped(json, false);
}

export function CostLineSchemaToJSONTyped(value?: CostLineSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusEnumToJSON(value['status']),
        'unrounded': value['unrounded'],
        'display': value['display'],
        'known_subtotal': value['knownSubtotal'],
        'total': value['total'],
        'warnings': value['warnings'],
    };
}

