/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseWriteSchemaRequest
 */
export interface CourseWriteSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof CourseWriteSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CourseWriteSchemaRequest
     */
    mealType: number;
    /**
     * 
     * @type {number}
     * @memberof CourseWriteSchemaRequest
     */
    position?: number;
}

/**
 * Check if a given object implements the CourseWriteSchemaRequest interface.
 */
export function instanceOfCourseWriteSchemaRequest(value: object): value is CourseWriteSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mealType' in value) || value['mealType'] === undefined) return false;
    return true;
}

export function CourseWriteSchemaRequestFromJSON(json: any): CourseWriteSchemaRequest {
    return CourseWriteSchemaRequestFromJSONTyped(json, false);
}

export function CourseWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'mealType': json['meal_type'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CourseWriteSchemaRequestToJSON(json: any): CourseWriteSchemaRequest {
    return CourseWriteSchemaRequestToJSONTyped(json, false);
}

export function CourseWriteSchemaRequestToJSONTyped(value?: CourseWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'meal_type': value['mealType'],
        'position': value['position'],
    };
}

