/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CuadernoRecipeFinanceValues
 */
export interface CuadernoRecipeFinanceValues {
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    sellingPricePerServing: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    budgetPerPerson: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    ingredientCostPerServing: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    differencePerServing: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    foodCostRatio: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    budgetGapPerPerson: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    pricePolicy: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    netProfit: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceValues
     */
    status: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CuadernoRecipeFinanceValues
     */
    warnings: Array<string>;
}

/**
 * Check if a given object implements the CuadernoRecipeFinanceValues interface.
 */
export function instanceOfCuadernoRecipeFinanceValues(value: object): value is CuadernoRecipeFinanceValues {
    if (!('sellingPricePerServing' in value) || value['sellingPricePerServing'] === undefined) return false;
    if (!('budgetPerPerson' in value) || value['budgetPerPerson'] === undefined) return false;
    if (!('ingredientCostPerServing' in value) || value['ingredientCostPerServing'] === undefined) return false;
    if (!('differencePerServing' in value) || value['differencePerServing'] === undefined) return false;
    if (!('foodCostRatio' in value) || value['foodCostRatio'] === undefined) return false;
    if (!('budgetGapPerPerson' in value) || value['budgetGapPerPerson'] === undefined) return false;
    if (!('pricePolicy' in value) || value['pricePolicy'] === undefined) return false;
    if (!('netProfit' in value) || value['netProfit'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    return true;
}

export function CuadernoRecipeFinanceValuesFromJSON(json: any): CuadernoRecipeFinanceValues {
    return CuadernoRecipeFinanceValuesFromJSONTyped(json, false);
}

export function CuadernoRecipeFinanceValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CuadernoRecipeFinanceValues {
    if (json == null) {
        return json;
    }
    return {
        
        'sellingPricePerServing': json['selling_price_per_serving'],
        'budgetPerPerson': json['budget_per_person'],
        'ingredientCostPerServing': json['ingredient_cost_per_serving'],
        'differencePerServing': json['difference_per_serving'],
        'foodCostRatio': json['food_cost_ratio'],
        'budgetGapPerPerson': json['budget_gap_per_person'],
        'pricePolicy': json['price_policy'],
        'netProfit': json['net_profit'],
        'status': json['status'],
        'warnings': json['warnings'],
    };
}

export function CuadernoRecipeFinanceValuesToJSON(json: any): CuadernoRecipeFinanceValues {
    return CuadernoRecipeFinanceValuesToJSONTyped(json, false);
}

export function CuadernoRecipeFinanceValuesToJSONTyped(value?: CuadernoRecipeFinanceValues | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selling_price_per_serving': value['sellingPricePerServing'],
        'budget_per_person': value['budgetPerPerson'],
        'ingredient_cost_per_serving': value['ingredientCostPerServing'],
        'difference_per_serving': value['differencePerServing'],
        'food_cost_ratio': value['foodCostRatio'],
        'budget_gap_per_person': value['budgetGapPerPerson'],
        'price_policy': value['pricePolicy'],
        'net_profit': value['netProfit'],
        'status': value['status'],
        'warnings': value['warnings'],
    };
}

