/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ManualProductionResultSchema } from './ManualProductionResultSchema';
import {
    instanceOfManualProductionResultSchema,
    ManualProductionResultSchemaFromJSON,
    ManualProductionResultSchemaFromJSONTyped,
    ManualProductionResultSchemaToJSON,
} from './ManualProductionResultSchema';
import type { ServiceProductionResultSchema } from './ServiceProductionResultSchema';
import {
    instanceOfServiceProductionResultSchema,
    ServiceProductionResultSchemaFromJSON,
    ServiceProductionResultSchemaFromJSONTyped,
    ServiceProductionResultSchemaToJSON,
} from './ServiceProductionResultSchema';
import type { ServiceProductionSheetSchema } from './ServiceProductionSheetSchema';
import {
    instanceOfServiceProductionSheetSchema,
    ServiceProductionSheetSchemaFromJSON,
    ServiceProductionSheetSchemaFromJSONTyped,
    ServiceProductionSheetSchemaToJSON,
} from './ServiceProductionSheetSchema';

/**
 * @type CuadernoProductionResponse
 * 
 * @export
 */
export type CuadernoProductionResponse = ManualProductionResultSchema | ServiceProductionResultSchema | ServiceProductionSheetSchema;

export function CuadernoProductionResponseFromJSON(json: any): CuadernoProductionResponse {
    return CuadernoProductionResponseFromJSONTyped(json, false);
}

export function CuadernoProductionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CuadernoProductionResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfManualProductionResultSchema(json)) {
        return ManualProductionResultSchemaFromJSONTyped(json, true);
    }
    if (instanceOfServiceProductionResultSchema(json)) {
        return ServiceProductionResultSchemaFromJSONTyped(json, true);
    }
    if (instanceOfServiceProductionSheetSchema(json)) {
        return ServiceProductionSheetSchemaFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CuadernoProductionResponseToJSON(json: any): any {
    return CuadernoProductionResponseToJSONTyped(json, false);
}

export function CuadernoProductionResponseToJSONTyped(value?: CuadernoProductionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfManualProductionResultSchema(value)) {
        return ManualProductionResultSchemaToJSON(value as ManualProductionResultSchema);
    }
    if (instanceOfServiceProductionResultSchema(value)) {
        return ServiceProductionResultSchemaToJSON(value as ServiceProductionResultSchema);
    }
    if (instanceOfServiceProductionSheetSchema(value)) {
        return ServiceProductionSheetSchemaToJSON(value as ServiceProductionSheetSchema);
    }
    return {};
}

