/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CuadernoRecipeFinanceWriteRequest
 */
export interface CuadernoRecipeFinanceWriteRequest {
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceWriteRequest
     */
    sellingPricePerServing?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CuadernoRecipeFinanceWriteRequest
     */
    budgetPerPerson?: string | null;
}

/**
 * Check if a given object implements the CuadernoRecipeFinanceWriteRequest interface.
 */
export function instanceOfCuadernoRecipeFinanceWriteRequest(value: object): value is CuadernoRecipeFinanceWriteRequest {
    return true;
}

export function CuadernoRecipeFinanceWriteRequestFromJSON(json: any): CuadernoRecipeFinanceWriteRequest {
    return CuadernoRecipeFinanceWriteRequestFromJSONTyped(json, false);
}

export function CuadernoRecipeFinanceWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CuadernoRecipeFinanceWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sellingPricePerServing': json['selling_price_per_serving'] == null ? undefined : json['selling_price_per_serving'],
        'budgetPerPerson': json['budget_per_person'] == null ? undefined : json['budget_per_person'],
    };
}

export function CuadernoRecipeFinanceWriteRequestToJSON(json: any): CuadernoRecipeFinanceWriteRequest {
    return CuadernoRecipeFinanceWriteRequestToJSONTyped(json, false);
}

export function CuadernoRecipeFinanceWriteRequestToJSONTyped(value?: CuadernoRecipeFinanceWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selling_price_per_serving': value['sellingPricePerServing'],
        'budget_per_person': value['budgetPerPerson'],
    };
}

