/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDietEnum } from './RecipeDietEnum';
import {
    RecipeDietEnumFromJSON,
    RecipeDietEnumFromJSONTyped,
    RecipeDietEnumToJSON,
    RecipeDietEnumToJSONTyped,
} from './RecipeDietEnum';
import type { RecipeDietStatusEnum } from './RecipeDietStatusEnum';
import {
    RecipeDietStatusEnumFromJSON,
    RecipeDietStatusEnumFromJSONTyped,
    RecipeDietStatusEnumToJSON,
    RecipeDietStatusEnumToJSONTyped,
} from './RecipeDietStatusEnum';

/**
 * 
 * @export
 * @interface DietWriteSchemaRequest
 */
export interface DietWriteSchemaRequest {
    /**
     * 
     * @type {RecipeDietEnum}
     * @memberof DietWriteSchemaRequest
     */
    slug: RecipeDietEnum;
    /**
     * 
     * @type {RecipeDietStatusEnum}
     * @memberof DietWriteSchemaRequest
     */
    status: RecipeDietStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DietWriteSchemaRequest
     */
    note?: string;
}



/**
 * Check if a given object implements the DietWriteSchemaRequest interface.
 */
export function instanceOfDietWriteSchemaRequest(value: object): value is DietWriteSchemaRequest {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DietWriteSchemaRequestFromJSON(json: any): DietWriteSchemaRequest {
    return DietWriteSchemaRequestFromJSONTyped(json, false);
}

export function DietWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DietWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': RecipeDietEnumFromJSON(json['slug']),
        'status': RecipeDietStatusEnumFromJSON(json['status']),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function DietWriteSchemaRequestToJSON(json: any): DietWriteSchemaRequest {
    return DietWriteSchemaRequestToJSONTyped(json, false);
}

export function DietWriteSchemaRequestToJSONTyped(value?: DietWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': RecipeDietEnumToJSON(value['slug']),
        'status': RecipeDietStatusEnumToJSON(value['status']),
        'note': value['note'],
    };
}

