/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDietEnum } from './RecipeDietEnum';
import {
    RecipeDietEnumFromJSON,
    RecipeDietEnumFromJSONTyped,
    RecipeDietEnumToJSON,
    RecipeDietEnumToJSONTyped,
} from './RecipeDietEnum';
import type { RecipeDietStatusEnum } from './RecipeDietStatusEnum';
import {
    RecipeDietStatusEnumFromJSON,
    RecipeDietStatusEnumFromJSONTyped,
    RecipeDietStatusEnumToJSON,
    RecipeDietStatusEnumToJSONTyped,
} from './RecipeDietStatusEnum';

/**
 * 
 * @export
 * @interface DietDeclarationSchema
 */
export interface DietDeclarationSchema {
    /**
     * 
     * @type {RecipeDietEnum}
     * @memberof DietDeclarationSchema
     */
    slug: RecipeDietEnum;
    /**
     * 
     * @type {RecipeDietStatusEnum}
     * @memberof DietDeclarationSchema
     */
    status: RecipeDietStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DietDeclarationSchema
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof DietDeclarationSchema
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof DietDeclarationSchema
     */
    updatedAt: Date | null;
}



/**
 * Check if a given object implements the DietDeclarationSchema interface.
 */
export function instanceOfDietDeclarationSchema(value: object): value is DietDeclarationSchema {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DietDeclarationSchemaFromJSON(json: any): DietDeclarationSchema {
    return DietDeclarationSchemaFromJSONTyped(json, false);
}

export function DietDeclarationSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DietDeclarationSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': RecipeDietEnumFromJSON(json['slug']),
        'status': RecipeDietStatusEnumFromJSON(json['status']),
        'note': json['note'] == null ? undefined : json['note'],
        'label': json['label'],
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function DietDeclarationSchemaToJSON(json: any): DietDeclarationSchema {
    return DietDeclarationSchemaToJSONTyped(json, false);
}

export function DietDeclarationSchemaToJSONTyped(value?: DietDeclarationSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': RecipeDietEnumToJSON(value['slug']),
        'status': RecipeDietStatusEnumToJSON(value['status']),
        'note': value['note'],
        'label': value['label'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

