/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeConversionSchema } from './ExchangeConversionSchema';
import {
    ExchangeConversionSchemaFromJSON,
    ExchangeConversionSchemaFromJSONTyped,
    ExchangeConversionSchemaToJSON,
    ExchangeConversionSchemaToJSONTyped,
} from './ExchangeConversionSchema';
import type { ExchangeFoodSchema } from './ExchangeFoodSchema';
import {
    ExchangeFoodSchemaFromJSON,
    ExchangeFoodSchemaFromJSONTyped,
    ExchangeFoodSchemaToJSON,
    ExchangeFoodSchemaToJSONTyped,
} from './ExchangeFoodSchema';
import type { ExchangePackageSchema } from './ExchangePackageSchema';
import {
    ExchangePackageSchemaFromJSON,
    ExchangePackageSchemaFromJSONTyped,
    ExchangePackageSchemaToJSON,
    ExchangePackageSchemaToJSONTyped,
} from './ExchangePackageSchema';
import type { ExchangeUnitSchema } from './ExchangeUnitSchema';
import {
    ExchangeUnitSchemaFromJSON,
    ExchangeUnitSchemaFromJSONTyped,
    ExchangeUnitSchemaToJSON,
    ExchangeUnitSchemaToJSONTyped,
} from './ExchangeUnitSchema';

/**
 * 
 * @export
 * @interface ExchangeCatalogSchema
 */
export interface ExchangeCatalogSchema {
    /**
     * 
     * @type {Array<ExchangeFoodSchema>}
     * @memberof ExchangeCatalogSchema
     */
    foods: Array<ExchangeFoodSchema>;
    /**
     * 
     * @type {Array<ExchangeUnitSchema>}
     * @memberof ExchangeCatalogSchema
     */
    units: Array<ExchangeUnitSchema>;
    /**
     * 
     * @type {Array<ExchangePackageSchema>}
     * @memberof ExchangeCatalogSchema
     */
    packages: Array<ExchangePackageSchema>;
    /**
     * 
     * @type {Array<ExchangeConversionSchema>}
     * @memberof ExchangeCatalogSchema
     */
    conversions: Array<ExchangeConversionSchema>;
}

/**
 * Check if a given object implements the ExchangeCatalogSchema interface.
 */
export function instanceOfExchangeCatalogSchema(value: object): value is ExchangeCatalogSchema {
    if (!('foods' in value) || value['foods'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('packages' in value) || value['packages'] === undefined) return false;
    if (!('conversions' in value) || value['conversions'] === undefined) return false;
    return true;
}

export function ExchangeCatalogSchemaFromJSON(json: any): ExchangeCatalogSchema {
    return ExchangeCatalogSchemaFromJSONTyped(json, false);
}

export function ExchangeCatalogSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeCatalogSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'foods': ((json['foods'] as Array<any>).map(ExchangeFoodSchemaFromJSON)),
        'units': ((json['units'] as Array<any>).map(ExchangeUnitSchemaFromJSON)),
        'packages': ((json['packages'] as Array<any>).map(ExchangePackageSchemaFromJSON)),
        'conversions': ((json['conversions'] as Array<any>).map(ExchangeConversionSchemaFromJSON)),
    };
}

export function ExchangeCatalogSchemaToJSON(json: any): ExchangeCatalogSchema {
    return ExchangeCatalogSchemaToJSONTyped(json, false);
}

export function ExchangeCatalogSchemaToJSONTyped(value?: ExchangeCatalogSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'foods': ((value['foods'] as Array<any>).map(ExchangeFoodSchemaToJSON)),
        'units': ((value['units'] as Array<any>).map(ExchangeUnitSchemaToJSON)),
        'packages': ((value['packages'] as Array<any>).map(ExchangePackageSchemaToJSON)),
        'conversions': ((value['conversions'] as Array<any>).map(ExchangeConversionSchemaToJSON)),
    };
}

