/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportIngredientSchemaRequest } from './ExchangeImportIngredientSchemaRequest';
import {
    ExchangeImportIngredientSchemaRequestFromJSON,
    ExchangeImportIngredientSchemaRequestFromJSONTyped,
    ExchangeImportIngredientSchemaRequestToJSON,
    ExchangeImportIngredientSchemaRequestToJSONTyped,
} from './ExchangeImportIngredientSchemaRequest';
import type { ExchangeImportYieldSchemaRequest } from './ExchangeImportYieldSchemaRequest';
import {
    ExchangeImportYieldSchemaRequestFromJSON,
    ExchangeImportYieldSchemaRequestFromJSONTyped,
    ExchangeImportYieldSchemaRequestToJSON,
    ExchangeImportYieldSchemaRequestToJSONTyped,
} from './ExchangeImportYieldSchemaRequest';
import type { ExchangeImportStepSchemaRequest } from './ExchangeImportStepSchemaRequest';
import {
    ExchangeImportStepSchemaRequestFromJSON,
    ExchangeImportStepSchemaRequestFromJSONTyped,
    ExchangeImportStepSchemaRequestToJSON,
    ExchangeImportStepSchemaRequestToJSONTyped,
} from './ExchangeImportStepSchemaRequest';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';

/**
 * 
 * @export
 * @interface ExchangeImportRecipeSchemaRequest
 */
export interface ExchangeImportRecipeSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    idExterno?: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    servings?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    _private?: boolean;
    /**
     * 
     * @type {Array<ExchangeImportIngredientSchemaRequest>}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    ingredients?: Array<ExchangeImportIngredientSchemaRequest>;
    /**
     * 
     * @type {Array<ExchangeImportStepSchemaRequest>}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    steps?: Array<ExchangeImportStepSchemaRequest>;
    /**
     * 
     * @type {ExchangeImportYieldSchemaRequest}
     * @memberof ExchangeImportRecipeSchemaRequest
     */
    _yield?: ExchangeImportYieldSchemaRequest | null;
}

/**
 * Check if a given object implements the ExchangeImportRecipeSchemaRequest interface.
 */
export function instanceOfExchangeImportRecipeSchemaRequest(value: object): value is ExchangeImportRecipeSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExchangeImportRecipeSchemaRequestFromJSON(json: any): ExchangeImportRecipeSchemaRequest {
    return ExchangeImportRecipeSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeImportRecipeSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportRecipeSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idExterno': json['id_externo'] == null ? undefined : json['id_externo'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'name': json['name'],
        'servings': json['servings'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['servings']),
        'description': json['description'] == null ? undefined : json['description'],
        '_private': json['private'] == null ? undefined : json['private'],
        'ingredients': json['ingredients'] == null ? undefined : ((json['ingredients'] as Array<any>).map(ExchangeImportIngredientSchemaRequestFromJSON)),
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(ExchangeImportStepSchemaRequestFromJSON)),
        '_yield': json['yield'] == null ? undefined : ExchangeImportYieldSchemaRequestFromJSON(json['yield']),
    };
}

export function ExchangeImportRecipeSchemaRequestToJSON(json: any): ExchangeImportRecipeSchemaRequest {
    return ExchangeImportRecipeSchemaRequestToJSONTyped(json, false);
}

export function ExchangeImportRecipeSchemaRequestToJSONTyped(value?: ExchangeImportRecipeSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id_externo': value['idExterno'],
        'external_id': value['externalId'],
        'name': value['name'],
        'servings': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['servings']),
        'description': value['description'],
        'private': value['_private'],
        'ingredients': value['ingredients'] == null ? undefined : ((value['ingredients'] as Array<any>).map(ExchangeImportIngredientSchemaRequestToJSON)),
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(ExchangeImportStepSchemaRequestToJSON)),
        'yield': ExchangeImportYieldSchemaRequestToJSON(value['_yield']),
    };
}

