/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeStepSchema } from './ExchangeStepSchema';
import {
    ExchangeStepSchemaFromJSON,
    ExchangeStepSchemaFromJSONTyped,
    ExchangeStepSchemaToJSON,
    ExchangeStepSchemaToJSONTyped,
} from './ExchangeStepSchema';
import type { ExchangeIngredientSchema } from './ExchangeIngredientSchema';
import {
    ExchangeIngredientSchemaFromJSON,
    ExchangeIngredientSchemaFromJSONTyped,
    ExchangeIngredientSchemaToJSON,
    ExchangeIngredientSchemaToJSONTyped,
} from './ExchangeIngredientSchema';
import type { ExchangeYieldSchema } from './ExchangeYieldSchema';
import {
    ExchangeYieldSchemaFromJSON,
    ExchangeYieldSchemaFromJSONTyped,
    ExchangeYieldSchemaToJSON,
    ExchangeYieldSchemaToJSONTyped,
} from './ExchangeYieldSchema';

/**
 * 
 * @export
 * @interface ExchangeRecipeSchema
 */
export interface ExchangeRecipeSchema {
    /**
     * 
     * @type {string}
     * @memberof ExchangeRecipeSchema
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRecipeSchema
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRecipeSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRecipeSchema
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangeRecipeSchema
     */
    _private: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRecipeSchema
     */
    servings: string;
    /**
     * 
     * @type {Array<ExchangeIngredientSchema>}
     * @memberof ExchangeRecipeSchema
     */
    ingredients?: Array<ExchangeIngredientSchema>;
    /**
     * 
     * @type {Array<ExchangeStepSchema>}
     * @memberof ExchangeRecipeSchema
     */
    steps: Array<ExchangeStepSchema>;
    /**
     * 
     * @type {ExchangeYieldSchema}
     * @memberof ExchangeRecipeSchema
     */
    _yield: ExchangeYieldSchema | null;
}

/**
 * Check if a given object implements the ExchangeRecipeSchema interface.
 */
export function instanceOfExchangeRecipeSchema(value: object): value is ExchangeRecipeSchema {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('_private' in value) || value['_private'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    if (!('_yield' in value) || value['_yield'] === undefined) return false;
    return true;
}

export function ExchangeRecipeSchemaFromJSON(json: any): ExchangeRecipeSchema {
    return ExchangeRecipeSchemaFromJSONTyped(json, false);
}

export function ExchangeRecipeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeRecipeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'externalId': json['external_id'],
        'name': json['name'],
        'description': json['description'],
        '_private': json['private'],
        'servings': json['servings'],
        'ingredients': json['ingredients'] == null ? undefined : ((json['ingredients'] as Array<any>).map(ExchangeIngredientSchemaFromJSON)),
        'steps': ((json['steps'] as Array<any>).map(ExchangeStepSchemaFromJSON)),
        '_yield': ExchangeYieldSchemaFromJSON(json['yield']),
    };
}

export function ExchangeRecipeSchemaToJSON(json: any): ExchangeRecipeSchema {
    return ExchangeRecipeSchemaToJSONTyped(json, false);
}

export function ExchangeRecipeSchemaToJSONTyped(value?: ExchangeRecipeSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'external_id': value['externalId'],
        'name': value['name'],
        'description': value['description'],
        'private': value['_private'],
        'servings': value['servings'],
        'ingredients': value['ingredients'] == null ? undefined : ((value['ingredients'] as Array<any>).map(ExchangeIngredientSchemaToJSON)),
        'steps': ((value['steps'] as Array<any>).map(ExchangeStepSchemaToJSON)),
        'yield': ExchangeYieldSchemaToJSON(value['_yield']),
    };
}

