/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangePriceSchema } from './ExchangePriceSchema';
import {
    ExchangePriceSchemaFromJSON,
    ExchangePriceSchemaFromJSONTyped,
    ExchangePriceSchemaToJSON,
    ExchangePriceSchemaToJSONTyped,
} from './ExchangePriceSchema';

/**
 * 
 * @export
 * @interface ExchangePackageSchema
 */
export interface ExchangePackageSchema {
    /**
     * 
     * @type {string}
     * @memberof ExchangePackageSchema
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangePackageSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangePackageSchema
     */
    foodRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangePackageSchema
     */
    unitRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangePackageSchema
     */
    quantity: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangePackageSchema
     */
    label: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangePackageSchema
     */
    isReference: boolean;
    /**
     * 
     * @type {Array<ExchangePriceSchema>}
     * @memberof ExchangePackageSchema
     */
    prices: Array<ExchangePriceSchema>;
}

/**
 * Check if a given object implements the ExchangePackageSchema interface.
 */
export function instanceOfExchangePackageSchema(value: object): value is ExchangePackageSchema {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('foodRef' in value) || value['foodRef'] === undefined) return false;
    if (!('unitRef' in value) || value['unitRef'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('isReference' in value) || value['isReference'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function ExchangePackageSchemaFromJSON(json: any): ExchangePackageSchema {
    return ExchangePackageSchemaFromJSONTyped(json, false);
}

export function ExchangePackageSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangePackageSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'],
        'foodRef': json['food_ref'],
        'unitRef': json['unit_ref'],
        'quantity': json['quantity'],
        'label': json['label'],
        'isReference': json['is_reference'],
        'prices': ((json['prices'] as Array<any>).map(ExchangePriceSchemaFromJSON)),
    };
}

export function ExchangePackageSchemaToJSON(json: any): ExchangePackageSchema {
    return ExchangePackageSchemaToJSONTyped(json, false);
}

export function ExchangePackageSchemaToJSONTyped(value?: ExchangePackageSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'food_ref': value['foodRef'],
        'unit_ref': value['unitRef'],
        'quantity': value['quantity'],
        'label': value['label'],
        'is_reference': value['isReference'],
        'prices': ((value['prices'] as Array<any>).map(ExchangePriceSchemaToJSON)),
    };
}

