/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeImportFoodSchemaRequest
 */
export interface ExchangeImportFoodSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportFoodSchemaRequest
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeImportFoodSchemaRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportFoodSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportFoodSchemaRequest
     */
    recipe?: string | null;
}

/**
 * Check if a given object implements the ExchangeImportFoodSchemaRequest interface.
 */
export function instanceOfExchangeImportFoodSchemaRequest(value: object): value is ExchangeImportFoodSchemaRequest {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExchangeImportFoodSchemaRequestFromJSON(json: any): ExchangeImportFoodSchemaRequest {
    return ExchangeImportFoodSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeImportFoodSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportFoodSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
    };
}

export function ExchangeImportFoodSchemaRequestToJSON(json: any): ExchangeImportFoodSchemaRequest {
    return ExchangeImportFoodSchemaRequestToJSONTyped(json, false);
}

export function ExchangeImportFoodSchemaRequestToJSONTyped(value?: ExchangeImportFoodSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'name': value['name'],
        'recipe': value['recipe'],
    };
}

