/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeUnitSchema
 */
export interface ExchangeUnitSchema {
    /**
     * 
     * @type {string}
     * @memberof ExchangeUnitSchema
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeUnitSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeUnitSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeUnitSchema
     */
    baseUnit: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeUnitSchema
     */
    pluralName: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeUnitSchema
     */
    description: string | null;
}

/**
 * Check if a given object implements the ExchangeUnitSchema interface.
 */
export function instanceOfExchangeUnitSchema(value: object): value is ExchangeUnitSchema {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('baseUnit' in value) || value['baseUnit'] === undefined) return false;
    if (!('pluralName' in value) || value['pluralName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ExchangeUnitSchemaFromJSON(json: any): ExchangeUnitSchema {
    return ExchangeUnitSchemaFromJSONTyped(json, false);
}

export function ExchangeUnitSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeUnitSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'],
        'name': json['name'],
        'baseUnit': json['base_unit'],
        'pluralName': json['plural_name'],
        'description': json['description'],
    };
}

export function ExchangeUnitSchemaToJSON(json: any): ExchangeUnitSchema {
    return ExchangeUnitSchemaToJSONTyped(json, false);
}

export function ExchangeUnitSchemaToJSONTyped(value?: ExchangeUnitSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'name': value['name'],
        'base_unit': value['baseUnit'],
        'plural_name': value['pluralName'],
        'description': value['description'],
    };
}

