/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeRecipeSchema } from './ExchangeRecipeSchema';
import {
    ExchangeRecipeSchemaFromJSON,
    ExchangeRecipeSchemaFromJSONTyped,
    ExchangeRecipeSchemaToJSON,
    ExchangeRecipeSchemaToJSONTyped,
} from './ExchangeRecipeSchema';

/**
 * 
 * @export
 * @interface ExchangePreviewSchema
 */
export interface ExchangePreviewSchema {
    /**
     * 
     * @type {number}
     * @memberof ExchangePreviewSchema
     */
    count: number;
    /**
     * 
     * @type {Array<ExchangeRecipeSchema>}
     * @memberof ExchangePreviewSchema
     */
    preview: Array<ExchangeRecipeSchema>;
    /**
     * 
     * @type {number}
     * @memberof ExchangePreviewSchema
     */
    writes: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangePreviewSchema
     */
    previewSha256: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangePreviewSchema
     */
    mappingRequired: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExchangePreviewSchema
     */
    warnings: Array<string>;
}

/**
 * Check if a given object implements the ExchangePreviewSchema interface.
 */
export function instanceOfExchangePreviewSchema(value: object): value is ExchangePreviewSchema {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('preview' in value) || value['preview'] === undefined) return false;
    if (!('writes' in value) || value['writes'] === undefined) return false;
    if (!('previewSha256' in value) || value['previewSha256'] === undefined) return false;
    if (!('mappingRequired' in value) || value['mappingRequired'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    return true;
}

export function ExchangePreviewSchemaFromJSON(json: any): ExchangePreviewSchema {
    return ExchangePreviewSchemaFromJSONTyped(json, false);
}

export function ExchangePreviewSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangePreviewSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'preview': ((json['preview'] as Array<any>).map(ExchangeRecipeSchemaFromJSON)),
        'writes': json['writes'],
        'previewSha256': json['preview_sha256'],
        'mappingRequired': json['mapping_required'],
        'warnings': json['warnings'],
    };
}

export function ExchangePreviewSchemaToJSON(json: any): ExchangePreviewSchema {
    return ExchangePreviewSchemaToJSONTyped(json, false);
}

export function ExchangePreviewSchemaToJSONTyped(value?: ExchangePreviewSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'preview': ((value['preview'] as Array<any>).map(ExchangeRecipeSchemaToJSON)),
        'writes': value['writes'],
        'preview_sha256': value['previewSha256'],
        'mapping_required': value['mappingRequired'],
        'warnings': value['warnings'],
    };
}

