/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeConversionSchema
 */
export interface ExchangeConversionSchema {
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeConversionSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    foodRef: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    baseUnitRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    convertedUnitRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    baseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeConversionSchema
     */
    convertedAmount: string;
}

/**
 * Check if a given object implements the ExchangeConversionSchema interface.
 */
export function instanceOfExchangeConversionSchema(value: object): value is ExchangeConversionSchema {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('foodRef' in value) || value['foodRef'] === undefined) return false;
    if (!('baseUnitRef' in value) || value['baseUnitRef'] === undefined) return false;
    if (!('convertedUnitRef' in value) || value['convertedUnitRef'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('convertedAmount' in value) || value['convertedAmount'] === undefined) return false;
    return true;
}

export function ExchangeConversionSchemaFromJSON(json: any): ExchangeConversionSchema {
    return ExchangeConversionSchemaFromJSONTyped(json, false);
}

export function ExchangeConversionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeConversionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'],
        'foodRef': json['food_ref'],
        'baseUnitRef': json['base_unit_ref'],
        'convertedUnitRef': json['converted_unit_ref'],
        'baseAmount': json['base_amount'],
        'convertedAmount': json['converted_amount'],
    };
}

export function ExchangeConversionSchemaToJSON(json: any): ExchangeConversionSchema {
    return ExchangeConversionSchemaToJSONTyped(json, false);
}

export function ExchangeConversionSchemaToJSONTyped(value?: ExchangeConversionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'food_ref': value['foodRef'],
        'base_unit_ref': value['baseUnitRef'],
        'converted_unit_ref': value['convertedUnitRef'],
        'base_amount': value['baseAmount'],
        'converted_amount': value['convertedAmount'],
    };
}

