/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeMappingSchemaRequest
 */
export interface ExchangeMappingSchemaRequest {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ExchangeMappingSchemaRequest
     */
    foods?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ExchangeMappingSchemaRequest
     */
    units?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ExchangeMappingSchemaRequest
     */
    packages?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ExchangeMappingSchemaRequest
     */
    conversions?: { [key: string]: number; };
}

/**
 * Check if a given object implements the ExchangeMappingSchemaRequest interface.
 */
export function instanceOfExchangeMappingSchemaRequest(value: object): value is ExchangeMappingSchemaRequest {
    return true;
}

export function ExchangeMappingSchemaRequestFromJSON(json: any): ExchangeMappingSchemaRequest {
    return ExchangeMappingSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeMappingSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeMappingSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'foods': json['foods'] == null ? undefined : json['foods'],
        'units': json['units'] == null ? undefined : json['units'],
        'packages': json['packages'] == null ? undefined : json['packages'],
        'conversions': json['conversions'] == null ? undefined : json['conversions'],
    };
}

export function ExchangeMappingSchemaRequestToJSON(json: any): ExchangeMappingSchemaRequest {
    return ExchangeMappingSchemaRequestToJSONTyped(json, false);
}

export function ExchangeMappingSchemaRequestToJSONTyped(value?: ExchangeMappingSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'foods': value['foods'],
        'units': value['units'],
        'packages': value['packages'],
        'conversions': value['conversions'],
    };
}

