/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';

/**
 * 
 * @export
 * @interface ExchangeImportConversionSchemaRequest
 */
export interface ExchangeImportConversionSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    foodRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    baseUnitRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    convertedUnitRef: string;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    baseAmount: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ExchangeImportConversionSchemaRequest
     */
    convertedAmount: ExchangeImportConversionSchemaRequestBaseAmount;
}

/**
 * Check if a given object implements the ExchangeImportConversionSchemaRequest interface.
 */
export function instanceOfExchangeImportConversionSchemaRequest(value: object): value is ExchangeImportConversionSchemaRequest {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('baseUnitRef' in value) || value['baseUnitRef'] === undefined) return false;
    if (!('convertedUnitRef' in value) || value['convertedUnitRef'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('convertedAmount' in value) || value['convertedAmount'] === undefined) return false;
    return true;
}

export function ExchangeImportConversionSchemaRequestFromJSON(json: any): ExchangeImportConversionSchemaRequest {
    return ExchangeImportConversionSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeImportConversionSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportConversionSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'] == null ? undefined : json['id'],
        'foodRef': json['food_ref'] == null ? undefined : json['food_ref'],
        'baseUnitRef': json['base_unit_ref'],
        'convertedUnitRef': json['converted_unit_ref'],
        'baseAmount': ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['base_amount']),
        'convertedAmount': ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['converted_amount']),
    };
}

export function ExchangeImportConversionSchemaRequestToJSON(json: any): ExchangeImportConversionSchemaRequest {
    return ExchangeImportConversionSchemaRequestToJSONTyped(json, false);
}

export function ExchangeImportConversionSchemaRequestToJSONTyped(value?: ExchangeImportConversionSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'food_ref': value['foodRef'],
        'base_unit_ref': value['baseUnitRef'],
        'converted_unit_ref': value['convertedUnitRef'],
        'base_amount': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['baseAmount']),
        'converted_amount': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['convertedAmount']),
    };
}

