/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeImportResultSchema
 */
export interface ExchangeImportResultSchema {
    /**
     * 
     * @type {Array<number>}
     * @memberof ExchangeImportResultSchema
     */
    created: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExchangeImportResultSchema
     */
    replayed: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExchangeImportResultSchema
     */
    rejected: Array<number>;
}

/**
 * Check if a given object implements the ExchangeImportResultSchema interface.
 */
export function instanceOfExchangeImportResultSchema(value: object): value is ExchangeImportResultSchema {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('replayed' in value) || value['replayed'] === undefined) return false;
    if (!('rejected' in value) || value['rejected'] === undefined) return false;
    return true;
}

export function ExchangeImportResultSchemaFromJSON(json: any): ExchangeImportResultSchema {
    return ExchangeImportResultSchemaFromJSONTyped(json, false);
}

export function ExchangeImportResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'replayed': json['replayed'],
        'rejected': json['rejected'],
    };
}

export function ExchangeImportResultSchemaToJSON(json: any): ExchangeImportResultSchema {
    return ExchangeImportResultSchemaToJSONTyped(json, false);
}

export function ExchangeImportResultSchemaToJSONTyped(value?: ExchangeImportResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'replayed': value['replayed'],
        'rejected': value['rejected'],
    };
}

