/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ExchangeImportConversionSchemaRequestBaseAmount
 * 
 * @export
 */
export type ExchangeImportConversionSchemaRequestBaseAmount = number | string;

export function ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json: any): ExchangeImportConversionSchemaRequestBaseAmount {
    return ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped(json, false);
}

export function ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportConversionSchemaRequestBaseAmount {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ExchangeImportConversionSchemaRequestBaseAmountToJSON(json: any): any {
    return ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped(json, false);
}

export function ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped(value?: ExchangeImportConversionSchemaRequestBaseAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

