/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';
import type { ExchangeImportPriceSchemaRequest } from './ExchangeImportPriceSchemaRequest';
import {
    ExchangeImportPriceSchemaRequestFromJSON,
    ExchangeImportPriceSchemaRequestFromJSONTyped,
    ExchangeImportPriceSchemaRequestToJSON,
    ExchangeImportPriceSchemaRequestToJSONTyped,
} from './ExchangeImportPriceSchemaRequest';

/**
 * 
 * @export
 * @interface ExchangeImportPackageSchemaRequest
 */
export interface ExchangeImportPackageSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    foodRef: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    unitRef: string;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    quantity: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    label: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    isReference: boolean;
    /**
     * 
     * @type {Array<ExchangeImportPriceSchemaRequest>}
     * @memberof ExchangeImportPackageSchemaRequest
     */
    prices: Array<ExchangeImportPriceSchemaRequest>;
}

/**
 * Check if a given object implements the ExchangeImportPackageSchemaRequest interface.
 */
export function instanceOfExchangeImportPackageSchemaRequest(value: object): value is ExchangeImportPackageSchemaRequest {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('foodRef' in value) || value['foodRef'] === undefined) return false;
    if (!('unitRef' in value) || value['unitRef'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('isReference' in value) || value['isReference'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function ExchangeImportPackageSchemaRequestFromJSON(json: any): ExchangeImportPackageSchemaRequest {
    return ExchangeImportPackageSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeImportPackageSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportPackageSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'] == null ? undefined : json['id'],
        'foodRef': json['food_ref'],
        'unitRef': json['unit_ref'],
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['quantity']),
        'label': json['label'],
        'isReference': json['is_reference'],
        'prices': ((json['prices'] as Array<any>).map(ExchangeImportPriceSchemaRequestFromJSON)),
    };
}

export function ExchangeImportPackageSchemaRequestToJSON(json: any): ExchangeImportPackageSchemaRequest {
    return ExchangeImportPackageSchemaRequestToJSONTyped(json, false);
}

export function ExchangeImportPackageSchemaRequestToJSONTyped(value?: ExchangeImportPackageSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'food_ref': value['foodRef'],
        'unit_ref': value['unitRef'],
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['quantity']),
        'label': value['label'],
        'is_reference': value['isReference'],
        'prices': ((value['prices'] as Array<any>).map(ExchangeImportPriceSchemaRequestToJSON)),
    };
}

