/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeMediaSchema
 */
export interface ExchangeMediaSchema {
    /**
     * 
     * @type {boolean}
     * @memberof ExchangeMediaSchema
     */
    included: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExchangeMediaSchema
     */
    method: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExchangeMediaSchema
     */
    urlDownloads: boolean;
}

/**
 * Check if a given object implements the ExchangeMediaSchema interface.
 */
export function instanceOfExchangeMediaSchema(value: object): value is ExchangeMediaSchema {
    if (!('included' in value) || value['included'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('urlDownloads' in value) || value['urlDownloads'] === undefined) return false;
    return true;
}

export function ExchangeMediaSchemaFromJSON(json: any): ExchangeMediaSchema {
    return ExchangeMediaSchemaFromJSONTyped(json, false);
}

export function ExchangeMediaSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeMediaSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'included': json['included'],
        'method': json['method'],
        'urlDownloads': json['url_downloads'],
    };
}

export function ExchangeMediaSchemaToJSON(json: any): ExchangeMediaSchema {
    return ExchangeMediaSchemaToJSONTyped(json, false);
}

export function ExchangeMediaSchemaToJSONTyped(value?: ExchangeMediaSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'included': value['included'],
        'method': value['method'],
        'url_downloads': value['urlDownloads'],
    };
}

