/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeIngredientSchema } from './ExchangeIngredientSchema';
import {
    ExchangeIngredientSchemaFromJSON,
    ExchangeIngredientSchemaFromJSONTyped,
    ExchangeIngredientSchemaToJSON,
    ExchangeIngredientSchemaToJSONTyped,
} from './ExchangeIngredientSchema';

/**
 * 
 * @export
 * @interface ExchangeStepSchema
 */
export interface ExchangeStepSchema {
    /**
     * 
     * @type {string}
     * @memberof ExchangeStepSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeStepSchema
     */
    instruction: string;
    /**
     * 
     * @type {Array<ExchangeIngredientSchema>}
     * @memberof ExchangeStepSchema
     */
    ingredients: Array<ExchangeIngredientSchema>;
    /**
     * 
     * @type {string}
     * @memberof ExchangeStepSchema
     */
    stepRecipe: string | null;
}

/**
 * Check if a given object implements the ExchangeStepSchema interface.
 */
export function instanceOfExchangeStepSchema(value: object): value is ExchangeStepSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('instruction' in value) || value['instruction'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('stepRecipe' in value) || value['stepRecipe'] === undefined) return false;
    return true;
}

export function ExchangeStepSchemaFromJSON(json: any): ExchangeStepSchema {
    return ExchangeStepSchemaFromJSONTyped(json, false);
}

export function ExchangeStepSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeStepSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'instruction': json['instruction'],
        'ingredients': ((json['ingredients'] as Array<any>).map(ExchangeIngredientSchemaFromJSON)),
        'stepRecipe': json['step_recipe'],
    };
}

export function ExchangeStepSchemaToJSON(json: any): ExchangeStepSchema {
    return ExchangeStepSchemaToJSONTyped(json, false);
}

export function ExchangeStepSchemaToJSONTyped(value?: ExchangeStepSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'instruction': value['instruction'],
        'ingredients': ((value['ingredients'] as Array<any>).map(ExchangeIngredientSchemaToJSON)),
        'step_recipe': value['stepRecipe'],
    };
}

