/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeImportUnitSchemaRequest
 */
export interface ExchangeImportUnitSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    baseUnit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    pluralName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExchangeImportUnitSchemaRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ExchangeImportUnitSchemaRequest interface.
 */
export function instanceOfExchangeImportUnitSchemaRequest(value: object): value is ExchangeImportUnitSchemaRequest {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExchangeImportUnitSchemaRequestFromJSON(json: any): ExchangeImportUnitSchemaRequest {
    return ExchangeImportUnitSchemaRequestFromJSONTyped(json, false);
}

export function ExchangeImportUnitSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeImportUnitSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'baseUnit': json['base_unit'] == null ? undefined : json['base_unit'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ExchangeImportUnitSchemaRequestToJSON(json: any): ExchangeImportUnitSchemaRequest {
    return ExchangeImportUnitSchemaRequestToJSONTyped(json, false);
}

export function ExchangeImportUnitSchemaRequestToJSONTyped(value?: ExchangeImportUnitSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
        'id': value['id'],
        'name': value['name'],
        'base_unit': value['baseUnit'],
        'plural_name': value['pluralName'],
        'description': value['description'],
    };
}

