/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoriteRecipeSchema
 */
export interface FavoriteRecipeSchema {
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecipeSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FavoriteRecipeSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FavoriteRecipeSchema
     */
    image: string | null;
}

/**
 * Check if a given object implements the FavoriteRecipeSchema interface.
 */
export function instanceOfFavoriteRecipeSchema(value: object): value is FavoriteRecipeSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function FavoriteRecipeSchemaFromJSON(json: any): FavoriteRecipeSchema {
    return FavoriteRecipeSchemaFromJSONTyped(json, false);
}

export function FavoriteRecipeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteRecipeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
    };
}

export function FavoriteRecipeSchemaToJSON(json: any): FavoriteRecipeSchema {
    return FavoriteRecipeSchemaToJSONTyped(json, false);
}

export function FavoriteRecipeSchemaToJSONTyped(value?: FavoriteRecipeSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
    };
}

