/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavoriteRecipeSchema } from './FavoriteRecipeSchema';
import {
    FavoriteRecipeSchemaFromJSON,
    FavoriteRecipeSchemaFromJSONTyped,
    FavoriteRecipeSchemaToJSON,
    FavoriteRecipeSchemaToJSONTyped,
} from './FavoriteRecipeSchema';

/**
 * 
 * @export
 * @interface FavoritesSchema
 */
export interface FavoritesSchema {
    /**
     * 
     * @type {number}
     * @memberof FavoritesSchema
     */
    count: number;
    /**
     * 
     * @type {Array<FavoriteRecipeSchema>}
     * @memberof FavoritesSchema
     */
    results: Array<FavoriteRecipeSchema>;
}

/**
 * Check if a given object implements the FavoritesSchema interface.
 */
export function instanceOfFavoritesSchema(value: object): value is FavoritesSchema {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function FavoritesSchemaFromJSON(json: any): FavoritesSchema {
    return FavoritesSchemaFromJSONTyped(json, false);
}

export function FavoritesSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'results': ((json['results'] as Array<any>).map(FavoriteRecipeSchemaFromJSON)),
    };
}

export function FavoritesSchemaToJSON(json: any): FavoritesSchema {
    return FavoritesSchemaToJSONTyped(json, false);
}

export function FavoritesSchemaToJSONTyped(value?: FavoritesSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'results': ((value['results'] as Array<any>).map(FavoriteRecipeSchemaToJSON)),
    };
}

