/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnitRequest } from './UnitRequest';
import {
    UnitRequestFromJSON,
    UnitRequestFromJSONTyped,
    UnitRequestToJSON,
    UnitRequestToJSONTyped,
} from './UnitRequest';
import type { QuantityBasisEnum } from './QuantityBasisEnum';
import {
    QuantityBasisEnumFromJSON,
    QuantityBasisEnumFromJSONTyped,
    QuantityBasisEnumToJSON,
    QuantityBasisEnumToJSONTyped,
} from './QuantityBasisEnum';
import type { FoodRequest } from './FoodRequest';
import {
    FoodRequestFromJSON,
    FoodRequestFromJSONTyped,
    FoodRequestToJSON,
    FoodRequestToJSONTyped,
} from './FoodRequest';

/**
 * Adds nested create feature
 * @export
 * @interface IngredientRequest
 */
export interface IngredientRequest {
    /**
     * 
     * @type {FoodRequest}
     * @memberof IngredientRequest
     */
    food: FoodRequest | null;
    /**
     * 
     * @type {UnitRequest}
     * @memberof IngredientRequest
     */
    unit: UnitRequest | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientRequest
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientRequest
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientRequest
     */
    isHeader?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientRequest
     */
    noAmount?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IngredientRequest
     */
    originalText?: string | null;
    /**
     * 
     * @type {QuantityBasisEnum}
     * @memberof IngredientRequest
     */
    quantityBasis?: QuantityBasisEnum;
    /**
     * 
     * @type {number}
     * @memberof IngredientRequest
     */
    yieldRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientRequest
     */
    id?: number;
}



/**
 * Check if a given object implements the IngredientRequest interface.
 */
export function instanceOfIngredientRequest(value: object): value is IngredientRequest {
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function IngredientRequestFromJSON(json: any): IngredientRequest {
    return IngredientRequestFromJSONTyped(json, false);
}

export function IngredientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'food': FoodRequestFromJSON(json['food']),
        'unit': UnitRequestFromJSON(json['unit']),
        'amount': json['amount'],
        'note': json['note'] == null ? undefined : json['note'],
        'order': json['order'] == null ? undefined : json['order'],
        'isHeader': json['is_header'] == null ? undefined : json['is_header'],
        'noAmount': json['no_amount'] == null ? undefined : json['no_amount'],
        'originalText': json['original_text'] == null ? undefined : json['original_text'],
        'quantityBasis': json['quantity_basis'] == null ? undefined : QuantityBasisEnumFromJSON(json['quantity_basis']),
        'yieldRatio': json['yield_ratio'] == null ? undefined : json['yield_ratio'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function IngredientRequestToJSON(json: any): IngredientRequest {
    return IngredientRequestToJSONTyped(json, false);
}

export function IngredientRequestToJSONTyped(value?: IngredientRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': FoodRequestToJSON(value['food']),
        'unit': UnitRequestToJSON(value['unit']),
        'amount': value['amount'],
        'note': value['note'],
        'order': value['order'],
        'is_header': value['isHeader'],
        'no_amount': value['noAmount'],
        'original_text': value['originalText'],
        'quantity_basis': QuantityBasisEnumToJSON(value['quantityBasis']),
        'yield_ratio': value['yieldRatio'],
        'id': value['id'],
    };
}

