/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientYieldWriteQuantityBasisEnum } from './IngredientYieldWriteQuantityBasisEnum';
import {
    IngredientYieldWriteQuantityBasisEnumFromJSON,
    IngredientYieldWriteQuantityBasisEnumFromJSONTyped,
    IngredientYieldWriteQuantityBasisEnumToJSON,
    IngredientYieldWriteQuantityBasisEnumToJSONTyped,
} from './IngredientYieldWriteQuantityBasisEnum';

/**
 * 
 * @export
 * @interface IngredientYieldWriteRequest
 */
export interface IngredientYieldWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof IngredientYieldWriteRequest
     */
    ingredient: number;
    /**
     * 
     * @type {IngredientYieldWriteQuantityBasisEnum}
     * @memberof IngredientYieldWriteRequest
     */
    quantityBasis: IngredientYieldWriteQuantityBasisEnum;
    /**
     * 
     * @type {number}
     * @memberof IngredientYieldWriteRequest
     */
    yieldRatio: number | null;
    /**
     * 
     * @type {string}
     * @memberof IngredientYieldWriteRequest
     */
    revision: string;
}



/**
 * Check if a given object implements the IngredientYieldWriteRequest interface.
 */
export function instanceOfIngredientYieldWriteRequest(value: object): value is IngredientYieldWriteRequest {
    if (!('ingredient' in value) || value['ingredient'] === undefined) return false;
    if (!('quantityBasis' in value) || value['quantityBasis'] === undefined) return false;
    if (!('yieldRatio' in value) || value['yieldRatio'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function IngredientYieldWriteRequestFromJSON(json: any): IngredientYieldWriteRequest {
    return IngredientYieldWriteRequestFromJSONTyped(json, false);
}

export function IngredientYieldWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientYieldWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ingredient': json['ingredient'],
        'quantityBasis': IngredientYieldWriteQuantityBasisEnumFromJSON(json['quantity_basis']),
        'yieldRatio': json['yield_ratio'],
        'revision': json['revision'],
    };
}

export function IngredientYieldWriteRequestToJSON(json: any): IngredientYieldWriteRequest {
    return IngredientYieldWriteRequestToJSONTyped(json, false);
}

export function IngredientYieldWriteRequestToJSONTyped(value?: IngredientYieldWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ingredient': value['ingredient'],
        'quantity_basis': IngredientYieldWriteQuantityBasisEnumToJSON(value['quantityBasis']),
        'yield_ratio': value['yieldRatio'],
        'revision': value['revision'],
    };
}

