/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientYieldRowSchema } from './IngredientYieldRowSchema';
import {
    IngredientYieldRowSchemaFromJSON,
    IngredientYieldRowSchemaFromJSONTyped,
    IngredientYieldRowSchemaToJSON,
    IngredientYieldRowSchemaToJSONTyped,
} from './IngredientYieldRowSchema';

/**
 * 
 * @export
 * @interface IngredientYieldSchema
 */
export interface IngredientYieldSchema {
    /**
     * 
     * @type {number}
     * @memberof IngredientYieldSchema
     */
    recipeId: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientYieldSchema
     */
    edition: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientYieldSchema
     */
    revision: string;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientYieldSchema
     */
    canEdit: boolean;
    /**
     * 
     * @type {Array<IngredientYieldRowSchema>}
     * @memberof IngredientYieldSchema
     */
    ingredients: Array<IngredientYieldRowSchema>;
}

/**
 * Check if a given object implements the IngredientYieldSchema interface.
 */
export function instanceOfIngredientYieldSchema(value: object): value is IngredientYieldSchema {
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('edition' in value) || value['edition'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    return true;
}

export function IngredientYieldSchemaFromJSON(json: any): IngredientYieldSchema {
    return IngredientYieldSchemaFromJSONTyped(json, false);
}

export function IngredientYieldSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientYieldSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeId': json['recipe_id'],
        'edition': json['edition'],
        'revision': json['revision'],
        'canEdit': json['can_edit'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientYieldRowSchemaFromJSON)),
    };
}

export function IngredientYieldSchemaToJSON(json: any): IngredientYieldSchema {
    return IngredientYieldSchemaToJSONTyped(json, false);
}

export function IngredientYieldSchemaToJSONTyped(value?: IngredientYieldSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipe_id': value['recipeId'],
        'edition': value['edition'],
        'revision': value['revision'],
        'can_edit': value['canEdit'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientYieldRowSchemaToJSON)),
    };
}

