/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HouseholdRequest } from './HouseholdRequest';
import {
    HouseholdRequestFromJSON,
    HouseholdRequestFromJSONTyped,
    HouseholdRequestToJSON,
    HouseholdRequestToJSONTyped,
} from './HouseholdRequest';

/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface InventoryLocationRequest
 */
export interface InventoryLocationRequest {
    /**
     * 
     * @type {string}
     * @memberof InventoryLocationRequest
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof InventoryLocationRequest
     */
    isFreezer?: boolean;
    /**
     * 
     * @type {HouseholdRequest}
     * @memberof InventoryLocationRequest
     */
    household: HouseholdRequest;
    /**
     * 
     * @type {number}
     * @memberof InventoryLocationRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the InventoryLocationRequest interface.
 */
export function instanceOfInventoryLocationRequest(value: object): value is InventoryLocationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('household' in value) || value['household'] === undefined) return false;
    return true;
}

export function InventoryLocationRequestFromJSON(json: any): InventoryLocationRequest {
    return InventoryLocationRequestFromJSONTyped(json, false);
}

export function InventoryLocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryLocationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isFreezer': json['is_freezer'] == null ? undefined : json['is_freezer'],
        'household': HouseholdRequestFromJSON(json['household']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function InventoryLocationRequestToJSON(json: any): InventoryLocationRequest {
    return InventoryLocationRequestToJSONTyped(json, false);
}

export function InventoryLocationRequestToJSONTyped(value?: InventoryLocationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'is_freezer': value['isFreezer'],
        'household': HouseholdRequestToJSON(value['household']),
        'id': value['id'],
    };
}

