/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';
import type { EditionWriteSchemaRequestTargetFoodCostRatio } from './EditionWriteSchemaRequestTargetFoodCostRatio';
import {
    EditionWriteSchemaRequestTargetFoodCostRatioFromJSON,
    EditionWriteSchemaRequestTargetFoodCostRatioFromJSONTyped,
    EditionWriteSchemaRequestTargetFoodCostRatioToJSON,
    EditionWriteSchemaRequestTargetFoodCostRatioToJSONTyped,
} from './EditionWriteSchemaRequestTargetFoodCostRatio';

/**
 * 
 * @export
 * @interface LegacyOrderWriteSchemaRequest
 */
export interface LegacyOrderWriteSchemaRequest {
    /**
     * 
     * @type {number}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    food?: number;
    /**
     * 
     * @type {number}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    unit?: number;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    quantity: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {number}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    supplier?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    supplierName?: string;
    /**
     * 
     * @type {number}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    _package?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    offer?: number | null;
    /**
     * 
     * @type {EditionWriteSchemaRequestTargetFoodCostRatio}
     * @memberof LegacyOrderWriteSchemaRequest
     */
    packageCount?: EditionWriteSchemaRequestTargetFoodCostRatio | null;
}

/**
 * Check if a given object implements the LegacyOrderWriteSchemaRequest interface.
 */
export function instanceOfLegacyOrderWriteSchemaRequest(value: object): value is LegacyOrderWriteSchemaRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function LegacyOrderWriteSchemaRequestFromJSON(json: any): LegacyOrderWriteSchemaRequest {
    return LegacyOrderWriteSchemaRequestFromJSONTyped(json, false);
}

export function LegacyOrderWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyOrderWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'food': json['food'] == null ? undefined : json['food'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['quantity']),
        'supplier': json['supplier'] == null ? undefined : json['supplier'],
        'supplierName': json['supplier_name'] == null ? undefined : json['supplier_name'],
        '_package': json['package'] == null ? undefined : json['package'],
        'offer': json['offer'] == null ? undefined : json['offer'],
        'packageCount': json['package_count'] == null ? undefined : EditionWriteSchemaRequestTargetFoodCostRatioFromJSON(json['package_count']),
    };
}

export function LegacyOrderWriteSchemaRequestToJSON(json: any): LegacyOrderWriteSchemaRequest {
    return LegacyOrderWriteSchemaRequestToJSONTyped(json, false);
}

export function LegacyOrderWriteSchemaRequestToJSONTyped(value?: LegacyOrderWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': value['food'],
        'unit': value['unit'],
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['quantity']),
        'supplier': value['supplier'],
        'supplier_name': value['supplierName'],
        'package': value['_package'],
        'offer': value['offer'],
        'package_count': EditionWriteSchemaRequestTargetFoodCostRatioToJSON(value['packageCount']),
    };
}

