/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphWarningSchema } from './GraphWarningSchema';
import {
    GraphWarningSchemaFromJSON,
    GraphWarningSchemaFromJSONTyped,
    GraphWarningSchemaToJSON,
    GraphWarningSchemaToJSONTyped,
} from './GraphWarningSchema';

/**
 * 
 * @export
 * @interface ManualProductionResultSchema
 */
export interface ManualProductionResultSchema {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ManualProductionResultSchema
     */
    needs: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof ManualProductionResultSchema
     */
    stockChanged: boolean;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ManualProductionResultSchema
     */
    edges: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<GraphWarningSchema>}
     * @memberof ManualProductionResultSchema
     */
    warnings: Array<GraphWarningSchema>;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof ManualProductionResultSchema
     */
    units: { [key: string]: string | null; };
}

/**
 * Check if a given object implements the ManualProductionResultSchema interface.
 */
export function instanceOfManualProductionResultSchema(value: object): value is ManualProductionResultSchema {
    if (!('needs' in value) || value['needs'] === undefined) return false;
    if (!('stockChanged' in value) || value['stockChanged'] === undefined) return false;
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    return true;
}

export function ManualProductionResultSchemaFromJSON(json: any): ManualProductionResultSchema {
    return ManualProductionResultSchemaFromJSONTyped(json, false);
}

export function ManualProductionResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualProductionResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'needs': json['needs'],
        'stockChanged': json['stock_changed'],
        'edges': json['edges'],
        'warnings': ((json['warnings'] as Array<any>).map(GraphWarningSchemaFromJSON)),
        'units': json['units'],
    };
}

export function ManualProductionResultSchemaToJSON(json: any): ManualProductionResultSchema {
    return ManualProductionResultSchemaToJSONTyped(json, false);
}

export function ManualProductionResultSchemaToJSONTyped(value?: ManualProductionResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'needs': value['needs'],
        'stock_changed': value['stockChanged'],
        'edges': value['edges'],
        'warnings': ((value['warnings'] as Array<any>).map(GraphWarningSchemaToJSON)),
        'units': value['units'],
    };
}

