/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeOverviewRequest } from './RecipeOverviewRequest';
import {
    RecipeOverviewRequestFromJSON,
    RecipeOverviewRequestFromJSONTyped,
    RecipeOverviewRequestToJSON,
    RecipeOverviewRequestToJSONTyped,
} from './RecipeOverviewRequest';
import type { MealTypeRequest } from './MealTypeRequest';
import {
    MealTypeRequestFromJSON,
    MealTypeRequestFromJSONTyped,
    MealTypeRequestToJSON,
    MealTypeRequestToJSONTyped,
} from './MealTypeRequest';

/**
 * Adds nested create feature
 * @export
 * @interface MealPlanRequest
 */
export interface MealPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof MealPlanRequest
     */
    title?: string;
    /**
     * 
     * @type {RecipeOverviewRequest}
     * @memberof MealPlanRequest
     */
    recipe?: RecipeOverviewRequest | null;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRequest
     */
    servings: number;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRequest
     */
    note?: string;
    /**
     * 
     * @type {Date}
     * @memberof MealPlanRequest
     */
    fromDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof MealPlanRequest
     */
    toDate?: Date;
    /**
     * 
     * @type {MealTypeRequest}
     * @memberof MealPlanRequest
     */
    mealType: MealTypeRequest;
    /**
     * 
     * @type {boolean}
     * @memberof MealPlanRequest
     */
    addshopping?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the MealPlanRequest interface.
 */
export function instanceOfMealPlanRequest(value: object): value is MealPlanRequest {
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('fromDate' in value) || value['fromDate'] === undefined) return false;
    if (!('mealType' in value) || value['mealType'] === undefined) return false;
    return true;
}

export function MealPlanRequestFromJSON(json: any): MealPlanRequest {
    return MealPlanRequestFromJSONTyped(json, false);
}

export function MealPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MealPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'recipe': json['recipe'] == null ? undefined : RecipeOverviewRequestFromJSON(json['recipe']),
        'servings': json['servings'],
        'note': json['note'] == null ? undefined : json['note'],
        'fromDate': (new Date(json['from_date'])),
        'toDate': json['to_date'] == null ? undefined : (new Date(json['to_date'])),
        'mealType': MealTypeRequestFromJSON(json['meal_type']),
        'addshopping': json['addshopping'] == null ? undefined : json['addshopping'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function MealPlanRequestToJSON(json: any): MealPlanRequest {
    return MealPlanRequestToJSONTyped(json, false);
}

export function MealPlanRequestToJSONTyped(value?: MealPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'recipe': RecipeOverviewRequestToJSON(value['recipe']),
        'servings': value['servings'],
        'note': value['note'],
        'from_date': value['fromDate'].toISOString(),
        'to_date': value['toDate'] == null ? value['toDate'] : value['toDate'].toISOString(),
        'meal_type': MealTypeRequestToJSON(value['mealType']),
        'addshopping': value['addshopping'],
        'id': value['id'],
    };
}

