/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuTemplateSchema } from './MenuTemplateSchema';
import {
    MenuTemplateSchemaFromJSON,
    MenuTemplateSchemaFromJSONTyped,
    MenuTemplateSchemaToJSON,
    MenuTemplateSchemaToJSONTyped,
} from './MenuTemplateSchema';

/**
 * 
 * @export
 * @interface MenuTemplatesSchema
 */
export interface MenuTemplatesSchema {
    /**
     * 
     * @type {number}
     * @memberof MenuTemplatesSchema
     */
    count: number;
    /**
     * 
     * @type {Array<MenuTemplateSchema>}
     * @memberof MenuTemplatesSchema
     */
    results: Array<MenuTemplateSchema>;
}

/**
 * Check if a given object implements the MenuTemplatesSchema interface.
 */
export function instanceOfMenuTemplatesSchema(value: object): value is MenuTemplatesSchema {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MenuTemplatesSchemaFromJSON(json: any): MenuTemplatesSchema {
    return MenuTemplatesSchemaFromJSONTyped(json, false);
}

export function MenuTemplatesSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuTemplatesSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'results': ((json['results'] as Array<any>).map(MenuTemplateSchemaFromJSON)),
    };
}

export function MenuTemplatesSchemaToJSON(json: any): MenuTemplatesSchema {
    return MenuTemplatesSchemaToJSONTyped(json, false);
}

export function MenuTemplatesSchemaToJSONTyped(value?: MenuTemplatesSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'results': ((value['results'] as Array<any>).map(MenuTemplateSchemaToJSON)),
    };
}

