/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrientationEnum } from './OrientationEnum';
import {
    OrientationEnumFromJSON,
    OrientationEnumFromJSONTyped,
    OrientationEnumToJSON,
    OrientationEnumToJSONTyped,
} from './OrientationEnum';
import type { PrintMenuWriteSchemaRequest } from './PrintMenuWriteSchemaRequest';
import {
    PrintMenuWriteSchemaRequestFromJSON,
    PrintMenuWriteSchemaRequestFromJSONTyped,
    PrintMenuWriteSchemaRequestToJSON,
    PrintMenuWriteSchemaRequestToJSONTyped,
} from './PrintMenuWriteSchemaRequest';
import type { RecipeDietEnum } from './RecipeDietEnum';
import {
    RecipeDietEnumFromJSON,
    RecipeDietEnumFromJSONTyped,
    RecipeDietEnumToJSON,
    RecipeDietEnumToJSONTyped,
} from './RecipeDietEnum';

/**
 * 
 * @export
 * @interface MenuPrintWriteSchemaRequest
 */
export interface MenuPrintWriteSchemaRequest {
    /**
     * 
     * @type {OrientationEnum}
     * @memberof MenuPrintWriteSchemaRequest
     */
    orientation: OrientationEnum;
    /**
     * 
     * @type {Array<PrintMenuWriteSchemaRequest>}
     * @memberof MenuPrintWriteSchemaRequest
     */
    menus: Array<PrintMenuWriteSchemaRequest>;
    /**
     * 
     * @type {RecipeDietEnum}
     * @memberof MenuPrintWriteSchemaRequest
     */
    diet?: RecipeDietEnum | null;
}



/**
 * Check if a given object implements the MenuPrintWriteSchemaRequest interface.
 */
export function instanceOfMenuPrintWriteSchemaRequest(value: object): value is MenuPrintWriteSchemaRequest {
    if (!('orientation' in value) || value['orientation'] === undefined) return false;
    if (!('menus' in value) || value['menus'] === undefined) return false;
    return true;
}

export function MenuPrintWriteSchemaRequestFromJSON(json: any): MenuPrintWriteSchemaRequest {
    return MenuPrintWriteSchemaRequestFromJSONTyped(json, false);
}

export function MenuPrintWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuPrintWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orientation': OrientationEnumFromJSON(json['orientation']),
        'menus': ((json['menus'] as Array<any>).map(PrintMenuWriteSchemaRequestFromJSON)),
        'diet': json['diet'] == null ? undefined : RecipeDietEnumFromJSON(json['diet']),
    };
}

export function MenuPrintWriteSchemaRequestToJSON(json: any): MenuPrintWriteSchemaRequest {
    return MenuPrintWriteSchemaRequestToJSONTyped(json, false);
}

export function MenuPrintWriteSchemaRequestToJSONTyped(value?: MenuPrintWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orientation': OrientationEnumToJSON(value['orientation']),
        'menus': ((value['menus'] as Array<any>).map(PrintMenuWriteSchemaRequestToJSON)),
        'diet': RecipeDietEnumToJSON(value['diet']),
    };
}

