/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimumWriteRequest
 */
export interface MinimumWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof MinimumWriteRequest
     */
    food: number;
    /**
     * 
     * @type {number}
     * @memberof MinimumWriteRequest
     */
    unit: number;
    /**
     * 
     * @type {string}
     * @memberof MinimumWriteRequest
     */
    quantity: string | null;
    /**
     * 
     * @type {number}
     * @memberof MinimumWriteRequest
     */
    location?: number | null;
}

/**
 * Check if a given object implements the MinimumWriteRequest interface.
 */
export function instanceOfMinimumWriteRequest(value: object): value is MinimumWriteRequest {
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function MinimumWriteRequestFromJSON(json: any): MinimumWriteRequest {
    return MinimumWriteRequestFromJSONTyped(json, false);
}

export function MinimumWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimumWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'food': json['food'],
        'unit': json['unit'],
        'quantity': json['quantity'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function MinimumWriteRequestToJSON(json: any): MinimumWriteRequest {
    return MinimumWriteRequestToJSONTyped(json, false);
}

export function MinimumWriteRequestToJSONTyped(value?: MinimumWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': value['food'],
        'unit': value['unit'],
        'quantity': value['quantity'],
        'location': value['location'],
    };
}

