/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovementResultSchema
 */
export interface MovementResultSchema {
    /**
     * 
     * @type {number}
     * @memberof MovementResultSchema
     */
    movementId: number;
    /**
     * 
     * @type {string}
     * @memberof MovementResultSchema
     */
    balance: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovementResultSchema
     */
    currentBalance: string;
    /**
     * Versioned ledger metadata extension
     * @type {any}
     * @memberof MovementResultSchema
     */
    metadataSnapshot: any | null;
    /**
     * 
     * @type {string}
     * @memberof MovementResultSchema
     */
    kind: string;
    /**
     * 
     * @type {number}
     * @memberof MovementResultSchema
     */
    reverses: number | null;
}

/**
 * Check if a given object implements the MovementResultSchema interface.
 */
export function instanceOfMovementResultSchema(value: object): value is MovementResultSchema {
    if (!('movementId' in value) || value['movementId'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('currentBalance' in value) || value['currentBalance'] === undefined) return false;
    if (!('metadataSnapshot' in value) || value['metadataSnapshot'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('reverses' in value) || value['reverses'] === undefined) return false;
    return true;
}

export function MovementResultSchemaFromJSON(json: any): MovementResultSchema {
    return MovementResultSchemaFromJSONTyped(json, false);
}

export function MovementResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'movementId': json['movement_id'],
        'balance': json['balance'],
        'currentBalance': json['current_balance'],
        'metadataSnapshot': json['metadata_snapshot'],
        'kind': json['kind'],
        'reverses': json['reverses'],
    };
}

export function MovementResultSchemaToJSON(json: any): MovementResultSchema {
    return MovementResultSchemaToJSONTyped(json, false);
}

export function MovementResultSchemaToJSONTyped(value?: MovementResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'movement_id': value['movementId'],
        'balance': value['balance'],
        'current_balance': value['currentBalance'],
        'metadata_snapshot': value['metadataSnapshot'],
        'kind': value['kind'],
        'reverses': value['reverses'],
    };
}

