/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';
import type { KindEnum } from './KindEnum';
import {
    KindEnumFromJSON,
    KindEnumFromJSONTyped,
    KindEnumToJSON,
    KindEnumToJSONTyped,
} from './KindEnum';

/**
 * 
 * @export
 * @interface MovementWriteSchemaRequest
 */
export interface MovementWriteSchemaRequest {
    /**
     * 
     * @type {number}
     * @memberof MovementWriteSchemaRequest
     */
    entry?: number;
    /**
     * 
     * @type {KindEnum}
     * @memberof MovementWriteSchemaRequest
     */
    kind?: KindEnum;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof MovementWriteSchemaRequest
     */
    quantity?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {string}
     * @memberof MovementWriteSchemaRequest
     */
    idempotencyKey?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementWriteSchemaRequest
     */
    cause?: string;
    /**
     * 
     * @type {number}
     * @memberof MovementWriteSchemaRequest
     */
    reverseOf?: number;
}



/**
 * Check if a given object implements the MovementWriteSchemaRequest interface.
 */
export function instanceOfMovementWriteSchemaRequest(value: object): value is MovementWriteSchemaRequest {
    return true;
}

export function MovementWriteSchemaRequestFromJSON(json: any): MovementWriteSchemaRequest {
    return MovementWriteSchemaRequestFromJSONTyped(json, false);
}

export function MovementWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entry': json['entry'] == null ? undefined : json['entry'],
        'kind': json['kind'] == null ? undefined : KindEnumFromJSON(json['kind']),
        'quantity': json['quantity'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['quantity']),
        'idempotencyKey': json['idempotency_key'] == null ? undefined : json['idempotency_key'],
        'cause': json['cause'] == null ? undefined : json['cause'],
        'reverseOf': json['reverse_of'] == null ? undefined : json['reverse_of'],
    };
}

export function MovementWriteSchemaRequestToJSON(json: any): MovementWriteSchemaRequest {
    return MovementWriteSchemaRequestToJSONTyped(json, false);
}

export function MovementWriteSchemaRequestToJSONTyped(value?: MovementWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry': value['entry'],
        'kind': KindEnumToJSON(value['kind']),
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['quantity']),
        'idempotency_key': value['idempotencyKey'],
        'cause': value['cause'],
        'reverse_of': value['reverseOf'],
    };
}

