/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OfferSchema
 */
export interface OfferSchema {
    /**
     * 
     * @type {number}
     * @memberof OfferSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OfferSchema
     */
    _package: number;
    /**
     * 
     * @type {number}
     * @memberof OfferSchema
     */
    supplier: number;
    /**
     * 
     * @type {string}
     * @memberof OfferSchema
     */
    amount: string;
    /**
     * 
     * @type {boolean}
     * @memberof OfferSchema
     */
    explicitFree: boolean;
    /**
     * 
     * @type {string}
     * @memberof OfferSchema
     */
    currency: string;
    /**
     * 
     * @type {Date}
     * @memberof OfferSchema
     */
    validFrom: Date;
    /**
     * 
     * @type {number}
     * @memberof OfferSchema
     */
    createdBy: number;
    /**
     * 
     * @type {Date}
     * @memberof OfferSchema
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the OfferSchema interface.
 */
export function instanceOfOfferSchema(value: object): value is OfferSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_package' in value) || value['_package'] === undefined) return false;
    if (!('supplier' in value) || value['supplier'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('explicitFree' in value) || value['explicitFree'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OfferSchemaFromJSON(json: any): OfferSchema {
    return OfferSchemaFromJSONTyped(json, false);
}

export function OfferSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        '_package': json['package'],
        'supplier': json['supplier'],
        'amount': json['amount'],
        'explicitFree': json['explicit_free'],
        'currency': json['currency'],
        'validFrom': (new Date(json['valid_from'])),
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function OfferSchemaToJSON(json: any): OfferSchema {
    return OfferSchemaToJSONTyped(json, false);
}

export function OfferSchemaToJSONTyped(value?: OfferSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'package': value['_package'],
        'supplier': value['supplier'],
        'amount': value['amount'],
        'explicit_free': value['explicitFree'],
        'currency': value['currency'],
        'valid_from': value['validFrom'].toISOString(),
        'created_by': value['createdBy'],
        'created_at': value['createdAt'].toISOString(),
    };
}

