/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeEnum } from './CodeEnum';
import {
    CodeEnumFromJSON,
    CodeEnumFromJSONTyped,
    CodeEnumToJSON,
    CodeEnumToJSONTyped,
} from './CodeEnum';

/**
 * 
 * @export
 * @interface OperationalRoleSchema
 */
export interface OperationalRoleSchema {
    /**
     * 
     * @type {CodeEnum}
     * @memberof OperationalRoleSchema
     */
    code: CodeEnum;
    /**
     * 
     * @type {string}
     * @memberof OperationalRoleSchema
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof OperationalRoleSchema
     */
    space: number;
    /**
     * 
     * @type {boolean}
     * @memberof OperationalRoleSchema
     */
    canOperateCuaderno: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationalRoleSchema
     */
    canManageEdition: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationalRoleSchema
     */
    nativePermissionsPreserved: boolean;
}



/**
 * Check if a given object implements the OperationalRoleSchema interface.
 */
export function instanceOfOperationalRoleSchema(value: object): value is OperationalRoleSchema {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('space' in value) || value['space'] === undefined) return false;
    if (!('canOperateCuaderno' in value) || value['canOperateCuaderno'] === undefined) return false;
    if (!('canManageEdition' in value) || value['canManageEdition'] === undefined) return false;
    if (!('nativePermissionsPreserved' in value) || value['nativePermissionsPreserved'] === undefined) return false;
    return true;
}

export function OperationalRoleSchemaFromJSON(json: any): OperationalRoleSchema {
    return OperationalRoleSchemaFromJSONTyped(json, false);
}

export function OperationalRoleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationalRoleSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'code': CodeEnumFromJSON(json['code']),
        'label': json['label'],
        'space': json['space'],
        'canOperateCuaderno': json['can_operate_cuaderno'],
        'canManageEdition': json['can_manage_edition'],
        'nativePermissionsPreserved': json['native_permissions_preserved'],
    };
}

export function OperationalRoleSchemaToJSON(json: any): OperationalRoleSchema {
    return OperationalRoleSchemaToJSONTyped(json, false);
}

export function OperationalRoleSchemaToJSONTyped(value?: OperationalRoleSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': CodeEnumToJSON(value['code']),
        'label': value['label'],
        'space': value['space'],
        'can_operate_cuaderno': value['canOperateCuaderno'],
        'can_manage_edition': value['canManageEdition'],
        'native_permissions_preserved': value['nativePermissionsPreserved'],
    };
}

