/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderActionActionEnum } from './OrderActionActionEnum';
import {
    OrderActionActionEnumFromJSON,
    OrderActionActionEnumFromJSONTyped,
    OrderActionActionEnumToJSON,
    OrderActionActionEnumToJSONTyped,
} from './OrderActionActionEnum';

/**
 * 
 * @export
 * @interface OrderActionRequest
 */
export interface OrderActionRequest {
    /**
     * 
     * @type {OrderActionActionEnum}
     * @memberof OrderActionRequest
     */
    action: OrderActionActionEnum;
}



/**
 * Check if a given object implements the OrderActionRequest interface.
 */
export function instanceOfOrderActionRequest(value: object): value is OrderActionRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function OrderActionRequestFromJSON(json: any): OrderActionRequest {
    return OrderActionRequestFromJSONTyped(json, false);
}

export function OrderActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderActionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': OrderActionActionEnumFromJSON(json['action']),
    };
}

export function OrderActionRequestToJSON(json: any): OrderActionRequest {
    return OrderActionRequestToJSONTyped(json, false);
}

export function OrderActionRequestToJSONTyped(value?: OrderActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': OrderActionActionEnumToJSON(value['action']),
    };
}

