/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderSchema
 */
export interface OrderSchema {
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    food: number;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    unit: number;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    quantity: string;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    receivedQuantity: string;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    household: number;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    supplier: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    supplierName: string;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    _package: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    packageCount: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    packageQuantitySnapshot: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    packageUnitSnapshot: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    priceSnapshot: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    currencySnapshot: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderSchema
     */
    state: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderSchema
     */
    orderedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof OrderSchema
     */
    cancelledAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof OrderSchema
     */
    createdBy: number;
    /**
     * 
     * @type {Date}
     * @memberof OrderSchema
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the OrderSchema interface.
 */
export function instanceOfOrderSchema(value: object): value is OrderSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('receivedQuantity' in value) || value['receivedQuantity'] === undefined) return false;
    if (!('household' in value) || value['household'] === undefined) return false;
    if (!('supplier' in value) || value['supplier'] === undefined) return false;
    if (!('supplierName' in value) || value['supplierName'] === undefined) return false;
    if (!('_package' in value) || value['_package'] === undefined) return false;
    if (!('packageCount' in value) || value['packageCount'] === undefined) return false;
    if (!('packageQuantitySnapshot' in value) || value['packageQuantitySnapshot'] === undefined) return false;
    if (!('packageUnitSnapshot' in value) || value['packageUnitSnapshot'] === undefined) return false;
    if (!('priceSnapshot' in value) || value['priceSnapshot'] === undefined) return false;
    if (!('currencySnapshot' in value) || value['currencySnapshot'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('orderedAt' in value) || value['orderedAt'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrderSchemaFromJSON(json: any): OrderSchema {
    return OrderSchemaFromJSONTyped(json, false);
}

export function OrderSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'food': json['food'],
        'unit': json['unit'],
        'quantity': json['quantity'],
        'receivedQuantity': json['received_quantity'],
        'household': json['household'],
        'supplier': json['supplier'],
        'supplierName': json['supplier_name'],
        '_package': json['package'],
        'packageCount': json['package_count'],
        'packageQuantitySnapshot': json['package_quantity_snapshot'],
        'packageUnitSnapshot': json['package_unit_snapshot'],
        'priceSnapshot': json['price_snapshot'],
        'currencySnapshot': json['currency_snapshot'],
        'state': json['state'],
        'orderedAt': (json['ordered_at'] == null ? null : new Date(json['ordered_at'])),
        'cancelledAt': (json['cancelled_at'] == null ? null : new Date(json['cancelled_at'])),
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function OrderSchemaToJSON(json: any): OrderSchema {
    return OrderSchemaToJSONTyped(json, false);
}

export function OrderSchemaToJSONTyped(value?: OrderSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'food': value['food'],
        'unit': value['unit'],
        'quantity': value['quantity'],
        'received_quantity': value['receivedQuantity'],
        'household': value['household'],
        'supplier': value['supplier'],
        'supplier_name': value['supplierName'],
        'package': value['_package'],
        'package_count': value['packageCount'],
        'package_quantity_snapshot': value['packageQuantitySnapshot'],
        'package_unit_snapshot': value['packageUnitSnapshot'],
        'price_snapshot': value['priceSnapshot'],
        'currency_snapshot': value['currencySnapshot'],
        'state': value['state'],
        'ordered_at': value['orderedAt'] == null ? value['orderedAt'] : value['orderedAt'].toISOString(),
        'cancelled_at': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'created_by': value['createdBy'],
        'created_at': value['createdAt'].toISOString(),
    };
}

