/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderWriteRequest
 */
export interface OrderWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof OrderWriteRequest
     */
    food?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderWriteRequest
     */
    unit?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderWriteRequest
     */
    quantity: string;
    /**
     * 
     * @type {number}
     * @memberof OrderWriteRequest
     */
    supplier?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrderWriteRequest
     */
    _package?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrderWriteRequest
     */
    offer?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrderWriteRequest
     */
    packageCount?: string | null;
}

/**
 * Check if a given object implements the OrderWriteRequest interface.
 */
export function instanceOfOrderWriteRequest(value: object): value is OrderWriteRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function OrderWriteRequestFromJSON(json: any): OrderWriteRequest {
    return OrderWriteRequestFromJSONTyped(json, false);
}

export function OrderWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'food': json['food'] == null ? undefined : json['food'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'quantity': json['quantity'],
        'supplier': json['supplier'] == null ? undefined : json['supplier'],
        '_package': json['package'] == null ? undefined : json['package'],
        'offer': json['offer'] == null ? undefined : json['offer'],
        'packageCount': json['package_count'] == null ? undefined : json['package_count'],
    };
}

export function OrderWriteRequestToJSON(json: any): OrderWriteRequest {
    return OrderWriteRequestToJSONTyped(json, false);
}

export function OrderWriteRequestToJSONTyped(value?: OrderWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': value['food'],
        'unit': value['unit'],
        'quantity': value['quantity'],
        'supplier': value['supplier'],
        'package': value['_package'],
        'offer': value['offer'],
        'package_count': value['packageCount'],
    };
}

