/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceSummarySchema } from './PriceSummarySchema';
import {
    PriceSummarySchemaFromJSON,
    PriceSummarySchemaFromJSONTyped,
    PriceSummarySchemaToJSON,
    PriceSummarySchemaToJSONTyped,
} from './PriceSummarySchema';

/**
 * 
 * @export
 * @interface PackageSchema
 */
export interface PackageSchema {
    /**
     * 
     * @type {number}
     * @memberof PackageSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PackageSchema
     */
    food: number;
    /**
     * 
     * @type {string}
     * @memberof PackageSchema
     */
    foodName: string;
    /**
     * 
     * @type {number}
     * @memberof PackageSchema
     */
    unit: number;
    /**
     * 
     * @type {string}
     * @memberof PackageSchema
     */
    unitName: string;
    /**
     * 
     * @type {string}
     * @memberof PackageSchema
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof PackageSchema
     */
    quantity: string;
    /**
     * 
     * @type {boolean}
     * @memberof PackageSchema
     */
    isReference: boolean;
    /**
     * 
     * @type {PriceSummarySchema}
     * @memberof PackageSchema
     */
    currentPrice: PriceSummarySchema | null;
}

/**
 * Check if a given object implements the PackageSchema interface.
 */
export function instanceOfPackageSchema(value: object): value is PackageSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('foodName' in value) || value['foodName'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('unitName' in value) || value['unitName'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('isReference' in value) || value['isReference'] === undefined) return false;
    if (!('currentPrice' in value) || value['currentPrice'] === undefined) return false;
    return true;
}

export function PackageSchemaFromJSON(json: any): PackageSchema {
    return PackageSchemaFromJSONTyped(json, false);
}

export function PackageSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'food': json['food'],
        'foodName': json['food_name'],
        'unit': json['unit'],
        'unitName': json['unit_name'],
        'label': json['label'],
        'quantity': json['quantity'],
        'isReference': json['is_reference'],
        'currentPrice': PriceSummarySchemaFromJSON(json['current_price']),
    };
}

export function PackageSchemaToJSON(json: any): PackageSchema {
    return PackageSchemaToJSONTyped(json, false);
}

export function PackageSchemaToJSONTyped(value?: PackageSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'food': value['food'],
        'food_name': value['foodName'],
        'unit': value['unit'],
        'unit_name': value['unitName'],
        'label': value['label'],
        'quantity': value['quantity'],
        'is_reference': value['isReference'],
        'current_price': PriceSummarySchemaToJSON(value['currentPrice']),
    };
}

