/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MealTypeRequest } from './MealTypeRequest';
import {
    MealTypeRequestFromJSON,
    MealTypeRequestFromJSONTyped,
    MealTypeRequestToJSON,
    MealTypeRequestToJSONTyped,
} from './MealTypeRequest';
import type { UserPreferenceNavTextColorEnum } from './UserPreferenceNavTextColorEnum';
import {
    UserPreferenceNavTextColorEnumFromJSON,
    UserPreferenceNavTextColorEnumFromJSONTyped,
    UserPreferenceNavTextColorEnumToJSON,
    UserPreferenceNavTextColorEnumToJSONTyped,
} from './UserPreferenceNavTextColorEnum';
import type { UserFileViewRequest } from './UserFileViewRequest';
import {
    UserFileViewRequestFromJSON,
    UserFileViewRequestFromJSONTyped,
    UserFileViewRequestToJSON,
    UserFileViewRequestToJSONTyped,
} from './UserFileViewRequest';
import type { ThemeEnum } from './ThemeEnum';
import {
    ThemeEnumFromJSON,
    ThemeEnumFromJSONTyped,
    ThemeEnumToJSON,
    ThemeEnumToJSONTyped,
} from './ThemeEnum';
import type { DefaultPageEnum } from './DefaultPageEnum';
import {
    DefaultPageEnumFromJSON,
    DefaultPageEnumFromJSONTyped,
    DefaultPageEnumToJSON,
    DefaultPageEnumToJSONTyped,
} from './DefaultPageEnum';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedUserPreferenceRequest
 */
export interface PatchedUserPreferenceRequest {
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof PatchedUserPreferenceRequest
     */
    image?: UserFileViewRequest | null;
    /**
     * 
     * @type {ThemeEnum}
     * @memberof PatchedUserPreferenceRequest
     */
    theme?: ThemeEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserPreferenceRequest
     */
    navBgColor?: string;
    /**
     * 
     * @type {UserPreferenceNavTextColorEnum}
     * @memberof PatchedUserPreferenceRequest
     */
    navTextColor?: UserPreferenceNavTextColorEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    navShowLogo?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserPreferenceRequest
     */
    defaultUnit?: string;
    /**
     * 
     * @type {DefaultPageEnum}
     * @memberof PatchedUserPreferenceRequest
     */
    defaultPage?: DefaultPageEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    useFractions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    useKj?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    navSticky?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserPreferenceRequest
     */
    ingredientDecimals?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    comments?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserPreferenceRequest
     */
    shoppingAutoSync?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    mealplanAutoaddShopping?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserPreferenceRequest
     */
    defaultDelay?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    mealplanAutoincludeRelated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    mealplanAutoexcludeOnhand?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserPreferenceRequest
     */
    shoppingRecentDays?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserPreferenceRequest
     */
    csvDelim?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserPreferenceRequest
     */
    csvPrefix?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    shoppingUpdateFoodLists?: boolean;
    /**
     * 
     * @type {MealTypeRequest}
     * @memberof PatchedUserPreferenceRequest
     */
    defaultMealType?: MealTypeRequest | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    filterToSupermarket?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    shoppingAddOnhand?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    leftHanded?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserPreferenceRequest
     */
    showStepIngredients?: boolean;
}



/**
 * Check if a given object implements the PatchedUserPreferenceRequest interface.
 */
export function instanceOfPatchedUserPreferenceRequest(value: object): value is PatchedUserPreferenceRequest {
    return true;
}

export function PatchedUserPreferenceRequestFromJSON(json: any): PatchedUserPreferenceRequest {
    return PatchedUserPreferenceRequestFromJSONTyped(json, false);
}

export function PatchedUserPreferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserPreferenceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : UserFileViewRequestFromJSON(json['image']),
        'theme': json['theme'] == null ? undefined : ThemeEnumFromJSON(json['theme']),
        'navBgColor': json['nav_bg_color'] == null ? undefined : json['nav_bg_color'],
        'navTextColor': json['nav_text_color'] == null ? undefined : UserPreferenceNavTextColorEnumFromJSON(json['nav_text_color']),
        'navShowLogo': json['nav_show_logo'] == null ? undefined : json['nav_show_logo'],
        'defaultUnit': json['default_unit'] == null ? undefined : json['default_unit'],
        'defaultPage': json['default_page'] == null ? undefined : DefaultPageEnumFromJSON(json['default_page']),
        'useFractions': json['use_fractions'] == null ? undefined : json['use_fractions'],
        'useKj': json['use_kj'] == null ? undefined : json['use_kj'],
        'navSticky': json['nav_sticky'] == null ? undefined : json['nav_sticky'],
        'ingredientDecimals': json['ingredient_decimals'] == null ? undefined : json['ingredient_decimals'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'shoppingAutoSync': json['shopping_auto_sync'] == null ? undefined : json['shopping_auto_sync'],
        'mealplanAutoaddShopping': json['mealplan_autoadd_shopping'] == null ? undefined : json['mealplan_autoadd_shopping'],
        'defaultDelay': json['default_delay'] == null ? undefined : json['default_delay'],
        'mealplanAutoincludeRelated': json['mealplan_autoinclude_related'] == null ? undefined : json['mealplan_autoinclude_related'],
        'mealplanAutoexcludeOnhand': json['mealplan_autoexclude_onhand'] == null ? undefined : json['mealplan_autoexclude_onhand'],
        'shoppingRecentDays': json['shopping_recent_days'] == null ? undefined : json['shopping_recent_days'],
        'csvDelim': json['csv_delim'] == null ? undefined : json['csv_delim'],
        'csvPrefix': json['csv_prefix'] == null ? undefined : json['csv_prefix'],
        'shoppingUpdateFoodLists': json['shopping_update_food_lists'] == null ? undefined : json['shopping_update_food_lists'],
        'defaultMealType': json['default_meal_type'] == null ? undefined : MealTypeRequestFromJSON(json['default_meal_type']),
        'filterToSupermarket': json['filter_to_supermarket'] == null ? undefined : json['filter_to_supermarket'],
        'shoppingAddOnhand': json['shopping_add_onhand'] == null ? undefined : json['shopping_add_onhand'],
        'leftHanded': json['left_handed'] == null ? undefined : json['left_handed'],
        'showStepIngredients': json['show_step_ingredients'] == null ? undefined : json['show_step_ingredients'],
    };
}

export function PatchedUserPreferenceRequestToJSON(json: any): PatchedUserPreferenceRequest {
    return PatchedUserPreferenceRequestToJSONTyped(json, false);
}

export function PatchedUserPreferenceRequestToJSONTyped(value?: PatchedUserPreferenceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': UserFileViewRequestToJSON(value['image']),
        'theme': ThemeEnumToJSON(value['theme']),
        'nav_bg_color': value['navBgColor'],
        'nav_text_color': UserPreferenceNavTextColorEnumToJSON(value['navTextColor']),
        'nav_show_logo': value['navShowLogo'],
        'default_unit': value['defaultUnit'],
        'default_page': DefaultPageEnumToJSON(value['defaultPage']),
        'use_fractions': value['useFractions'],
        'use_kj': value['useKj'],
        'nav_sticky': value['navSticky'],
        'ingredient_decimals': value['ingredientDecimals'],
        'comments': value['comments'],
        'shopping_auto_sync': value['shoppingAutoSync'],
        'mealplan_autoadd_shopping': value['mealplanAutoaddShopping'],
        'default_delay': value['defaultDelay'],
        'mealplan_autoinclude_related': value['mealplanAutoincludeRelated'],
        'mealplan_autoexclude_onhand': value['mealplanAutoexcludeOnhand'],
        'shopping_recent_days': value['shoppingRecentDays'],
        'csv_delim': value['csvDelim'],
        'csv_prefix': value['csvPrefix'],
        'shopping_update_food_lists': value['shoppingUpdateFoodLists'],
        'default_meal_type': MealTypeRequestToJSON(value['defaultMealType']),
        'filter_to_supermarket': value['filterToSupermarket'],
        'shopping_add_onhand': value['shoppingAddOnhand'],
        'left_handed': value['leftHanded'],
        'show_step_ingredients': value['showStepIngredients'],
    };
}

