/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorConfigUrl } from './ConnectorConfigUrl';
import {
    ConnectorConfigUrlFromJSON,
    ConnectorConfigUrlFromJSONTyped,
    ConnectorConfigUrlToJSON,
    ConnectorConfigUrlToJSONTyped,
} from './ConnectorConfigUrl';
import type { ConnectorConfigTypeEnum } from './ConnectorConfigTypeEnum';
import {
    ConnectorConfigTypeEnumFromJSON,
    ConnectorConfigTypeEnumFromJSONTyped,
    ConnectorConfigTypeEnumToJSON,
    ConnectorConfigTypeEnumToJSONTyped,
} from './ConnectorConfigTypeEnum';

/**
 * 
 * @export
 * @interface PatchedConnectorConfigRequest
 */
export interface PatchedConnectorConfigRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedConnectorConfigRequest
     */
    name?: string;
    /**
     * 
     * @type {ConnectorConfigTypeEnum}
     * @memberof PatchedConnectorConfigRequest
     */
    type?: ConnectorConfigTypeEnum;
    /**
     * 
     * @type {ConnectorConfigUrl}
     * @memberof PatchedConnectorConfigRequest
     */
    url?: ConnectorConfigUrl | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedConnectorConfigRequest
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedConnectorConfigRequest
     */
    todoEntity?: string | null;
    /**
     * Is Connector Enabled
     * @type {boolean}
     * @memberof PatchedConnectorConfigRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedConnectorConfigRequest
     */
    onShoppingListEntryCreatedEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedConnectorConfigRequest
     */
    onShoppingListEntryUpdatedEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedConnectorConfigRequest
     */
    onShoppingListEntryDeletedEnabled?: boolean;
    /**
     * Does the todo entity support the description field
     * @type {boolean}
     * @memberof PatchedConnectorConfigRequest
     */
    supportsDescriptionField?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedConnectorConfigRequest
     */
    id?: number;
}



/**
 * Check if a given object implements the PatchedConnectorConfigRequest interface.
 */
export function instanceOfPatchedConnectorConfigRequest(value: object): value is PatchedConnectorConfigRequest {
    return true;
}

export function PatchedConnectorConfigRequestFromJSON(json: any): PatchedConnectorConfigRequest {
    return PatchedConnectorConfigRequestFromJSONTyped(json, false);
}

export function PatchedConnectorConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedConnectorConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : ConnectorConfigTypeEnumFromJSON(json['type']),
        'url': json['url'] == null ? undefined : ConnectorConfigUrlFromJSON(json['url']),
        'token': json['token'] == null ? undefined : json['token'],
        'todoEntity': json['todo_entity'] == null ? undefined : json['todo_entity'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'onShoppingListEntryCreatedEnabled': json['on_shopping_list_entry_created_enabled'] == null ? undefined : json['on_shopping_list_entry_created_enabled'],
        'onShoppingListEntryUpdatedEnabled': json['on_shopping_list_entry_updated_enabled'] == null ? undefined : json['on_shopping_list_entry_updated_enabled'],
        'onShoppingListEntryDeletedEnabled': json['on_shopping_list_entry_deleted_enabled'] == null ? undefined : json['on_shopping_list_entry_deleted_enabled'],
        'supportsDescriptionField': json['supports_description_field'] == null ? undefined : json['supports_description_field'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedConnectorConfigRequestToJSON(json: any): PatchedConnectorConfigRequest {
    return PatchedConnectorConfigRequestToJSONTyped(json, false);
}

export function PatchedConnectorConfigRequestToJSONTyped(value?: PatchedConnectorConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': ConnectorConfigTypeEnumToJSON(value['type']),
        'url': ConnectorConfigUrlToJSON(value['url']),
        'token': value['token'],
        'todo_entity': value['todoEntity'],
        'enabled': value['enabled'],
        'on_shopping_list_entry_created_enabled': value['onShoppingListEntryCreatedEnabled'],
        'on_shopping_list_entry_updated_enabled': value['onShoppingListEntryUpdatedEnabled'],
        'on_shopping_list_entry_deleted_enabled': value['onShoppingListEntryDeletedEnabled'],
        'supports_description_field': value['supportsDescriptionField'],
        'id': value['id'],
    };
}

