/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HouseholdRequest } from './HouseholdRequest';
import {
    HouseholdRequestFromJSON,
    HouseholdRequestFromJSONTyped,
    HouseholdRequestToJSON,
    HouseholdRequestToJSONTyped,
} from './HouseholdRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedUserSpaceRequest
 */
export interface PatchedUserSpaceRequest {
    /**
     * 
     * @type {HouseholdRequest}
     * @memberof PatchedUserSpaceRequest
     */
    household?: HouseholdRequest | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserSpaceRequest
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserSpaceRequest
     */
    internalNote?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserSpaceRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedUserSpaceRequest interface.
 */
export function instanceOfPatchedUserSpaceRequest(value: object): value is PatchedUserSpaceRequest {
    return true;
}

export function PatchedUserSpaceRequestFromJSON(json: any): PatchedUserSpaceRequest {
    return PatchedUserSpaceRequestFromJSONTyped(json, false);
}

export function PatchedUserSpaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserSpaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'household': json['household'] == null ? undefined : HouseholdRequestFromJSON(json['household']),
        'active': json['active'] == null ? undefined : json['active'],
        'internalNote': json['internal_note'] == null ? undefined : json['internal_note'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedUserSpaceRequestToJSON(json: any): PatchedUserSpaceRequest {
    return PatchedUserSpaceRequestToJSONTyped(json, false);
}

export function PatchedUserSpaceRequestToJSONTyped(value?: PatchedUserSpaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'household': HouseholdRequestToJSON(value['household']),
        'active': value['active'],
        'internal_note': value['internalNote'],
        'id': value['id'],
    };
}

