/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAiProviderRequest
 */
export interface PatchedAiProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProviderRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProviderRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProviderRequest
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProviderRequest
     */
    modelName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProviderRequest
     */
    url?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedAiProviderRequest
     */
    logCreditCost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedAiProviderRequest
     */
    space?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedAiProviderRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedAiProviderRequest interface.
 */
export function instanceOfPatchedAiProviderRequest(value: object): value is PatchedAiProviderRequest {
    return true;
}

export function PatchedAiProviderRequestFromJSON(json: any): PatchedAiProviderRequest {
    return PatchedAiProviderRequestFromJSONTyped(json, false);
}

export function PatchedAiProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAiProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'url': json['url'] == null ? undefined : json['url'],
        'logCreditCost': json['log_credit_cost'] == null ? undefined : json['log_credit_cost'],
        'space': json['space'] == null ? undefined : json['space'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedAiProviderRequestToJSON(json: any): PatchedAiProviderRequest {
    return PatchedAiProviderRequestToJSONTyped(json, false);
}

export function PatchedAiProviderRequestToJSONTyped(value?: PatchedAiProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'api_key': value['apiKey'],
        'model_name': value['modelName'],
        'url': value['url'],
        'log_credit_cost': value['logCreditCost'],
        'space': value['space'],
        'id': value['id'],
    };
}

