/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface PatchedMealTypeRequest
 */
export interface PatchedMealTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedMealTypeRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedMealTypeRequest
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedMealTypeRequest
     */
    time?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedMealTypeRequest
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedMealTypeRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedMealTypeRequest interface.
 */
export function instanceOfPatchedMealTypeRequest(value: object): value is PatchedMealTypeRequest {
    return true;
}

export function PatchedMealTypeRequestFromJSON(json: any): PatchedMealTypeRequest {
    return PatchedMealTypeRequestFromJSONTyped(json, false);
}

export function PatchedMealTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMealTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'order': json['order'] == null ? undefined : json['order'],
        'time': json['time'] == null ? undefined : json['time'],
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedMealTypeRequestToJSON(json: any): PatchedMealTypeRequest {
    return PatchedMealTypeRequestToJSONTyped(json, false);
}

export function PatchedMealTypeRequestToJSONTyped(value?: PatchedMealTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'order': value['order'],
        'time': value['time'],
        'color': value['color'],
        'id': value['id'],
    };
}

