/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InviteLinkEmail } from './InviteLinkEmail';
import {
    InviteLinkEmailFromJSON,
    InviteLinkEmailFromJSONTyped,
    InviteLinkEmailToJSON,
    InviteLinkEmailToJSONTyped,
} from './InviteLinkEmail';
import type { HouseholdRequest } from './HouseholdRequest';
import {
    HouseholdRequestFromJSON,
    HouseholdRequestFromJSONTyped,
    HouseholdRequestToJSON,
    HouseholdRequestToJSONTyped,
} from './HouseholdRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedInviteLinkRequest
 */
export interface PatchedInviteLinkRequest {
    /**
     * 
     * @type {InviteLinkEmail}
     * @memberof PatchedInviteLinkRequest
     */
    email?: InviteLinkEmail;
    /**
     * 
     * @type {HouseholdRequest}
     * @memberof PatchedInviteLinkRequest
     */
    household?: HouseholdRequest | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInviteLinkRequest
     */
    validUntil?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedInviteLinkRequest
     */
    reusable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedInviteLinkRequest
     */
    internalNote?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedInviteLinkRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedInviteLinkRequest interface.
 */
export function instanceOfPatchedInviteLinkRequest(value: object): value is PatchedInviteLinkRequest {
    return true;
}

export function PatchedInviteLinkRequestFromJSON(json: any): PatchedInviteLinkRequest {
    return PatchedInviteLinkRequestFromJSONTyped(json, false);
}

export function PatchedInviteLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedInviteLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : InviteLinkEmailFromJSON(json['email']),
        'household': json['household'] == null ? undefined : HouseholdRequestFromJSON(json['household']),
        'validUntil': json['valid_until'] == null ? undefined : (new Date(json['valid_until'])),
        'reusable': json['reusable'] == null ? undefined : json['reusable'],
        'internalNote': json['internal_note'] == null ? undefined : json['internal_note'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedInviteLinkRequestToJSON(json: any): PatchedInviteLinkRequest {
    return PatchedInviteLinkRequestToJSONTyped(json, false);
}

export function PatchedInviteLinkRequestToJSONTyped(value?: PatchedInviteLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': InviteLinkEmailToJSON(value['email']),
        'household': HouseholdRequestToJSON(value['household']),
        'valid_until': value['validUntil'] == null ? value['validUntil'] : value['validUntil'].toISOString().substring(0,10),
        'reusable': value['reusable'],
        'internal_note': value['internalNote'],
        'id': value['id'],
    };
}

