/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeOverviewRequest } from './RecipeOverviewRequest';
import {
    RecipeOverviewRequestFromJSON,
    RecipeOverviewRequestFromJSONTyped,
    RecipeOverviewRequestToJSON,
    RecipeOverviewRequestToJSONTyped,
} from './RecipeOverviewRequest';
import type { MealTypeRequest } from './MealTypeRequest';
import {
    MealTypeRequestFromJSON,
    MealTypeRequestFromJSONTyped,
    MealTypeRequestToJSON,
    MealTypeRequestToJSONTyped,
} from './MealTypeRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedMealPlanRequest
 */
export interface PatchedMealPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedMealPlanRequest
     */
    title?: string;
    /**
     * 
     * @type {RecipeOverviewRequest}
     * @memberof PatchedMealPlanRequest
     */
    recipe?: RecipeOverviewRequest | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedMealPlanRequest
     */
    servings?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedMealPlanRequest
     */
    note?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedMealPlanRequest
     */
    fromDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedMealPlanRequest
     */
    toDate?: Date;
    /**
     * 
     * @type {MealTypeRequest}
     * @memberof PatchedMealPlanRequest
     */
    mealType?: MealTypeRequest;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedMealPlanRequest
     */
    addshopping?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedMealPlanRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedMealPlanRequest interface.
 */
export function instanceOfPatchedMealPlanRequest(value: object): value is PatchedMealPlanRequest {
    return true;
}

export function PatchedMealPlanRequestFromJSON(json: any): PatchedMealPlanRequest {
    return PatchedMealPlanRequestFromJSONTyped(json, false);
}

export function PatchedMealPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMealPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'recipe': json['recipe'] == null ? undefined : RecipeOverviewRequestFromJSON(json['recipe']),
        'servings': json['servings'] == null ? undefined : json['servings'],
        'note': json['note'] == null ? undefined : json['note'],
        'fromDate': json['from_date'] == null ? undefined : (new Date(json['from_date'])),
        'toDate': json['to_date'] == null ? undefined : (new Date(json['to_date'])),
        'mealType': json['meal_type'] == null ? undefined : MealTypeRequestFromJSON(json['meal_type']),
        'addshopping': json['addshopping'] == null ? undefined : json['addshopping'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedMealPlanRequestToJSON(json: any): PatchedMealPlanRequest {
    return PatchedMealPlanRequestToJSONTyped(json, false);
}

export function PatchedMealPlanRequestToJSONTyped(value?: PatchedMealPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'recipe': RecipeOverviewRequestToJSON(value['recipe']),
        'servings': value['servings'],
        'note': value['note'],
        'from_date': value['fromDate'] == null ? value['fromDate'] : value['fromDate'].toISOString(),
        'to_date': value['toDate'] == null ? value['toDate'] : value['toDate'].toISOString(),
        'meal_type': MealTypeRequestToJSON(value['mealType']),
        'addshopping': value['addshopping'],
        'id': value['id'],
    };
}

