/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageRequest } from './StorageRequest';
import {
    StorageRequestFromJSON,
    StorageRequestFromJSONTyped,
    StorageRequestToJSON,
    StorageRequestToJSONTyped,
} from './StorageRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedSyncRequest
 */
export interface PatchedSyncRequest {
    /**
     * 
     * @type {StorageRequest}
     * @memberof PatchedSyncRequest
     */
    storage?: StorageRequest;
    /**
     * 
     * @type {string}
     * @memberof PatchedSyncRequest
     */
    path?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSyncRequest
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSyncRequest
     */
    lastChecked?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedSyncRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedSyncRequest interface.
 */
export function instanceOfPatchedSyncRequest(value: object): value is PatchedSyncRequest {
    return true;
}

export function PatchedSyncRequestFromJSON(json: any): PatchedSyncRequest {
    return PatchedSyncRequestFromJSONTyped(json, false);
}

export function PatchedSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : StorageRequestFromJSON(json['storage']),
        'path': json['path'] == null ? undefined : json['path'],
        'active': json['active'] == null ? undefined : json['active'],
        'lastChecked': json['last_checked'] == null ? undefined : (new Date(json['last_checked'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedSyncRequestToJSON(json: any): PatchedSyncRequest {
    return PatchedSyncRequestToJSONTyped(json, false);
}

export function PatchedSyncRequestToJSONTyped(value?: PatchedSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': StorageRequestToJSON(value['storage']),
        'path': value['path'],
        'active': value['active'],
        'last_checked': value['lastChecked'] == null ? value['lastChecked'] : value['lastChecked'].toISOString(),
        'id': value['id'],
    };
}

