/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedShoppingListRecipeRequest
 */
export interface PatchedShoppingListRecipeRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedShoppingListRecipeRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    recipe?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    mealplan?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    servings?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedShoppingListRecipeRequest interface.
 */
export function instanceOfPatchedShoppingListRecipeRequest(value: object): value is PatchedShoppingListRecipeRequest {
    return true;
}

export function PatchedShoppingListRecipeRequestFromJSON(json: any): PatchedShoppingListRecipeRequest {
    return PatchedShoppingListRecipeRequestFromJSONTyped(json, false);
}

export function PatchedShoppingListRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedShoppingListRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'mealplan': json['mealplan'] == null ? undefined : json['mealplan'],
        'servings': json['servings'] == null ? undefined : json['servings'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedShoppingListRecipeRequestToJSON(json: any): PatchedShoppingListRecipeRequest {
    return PatchedShoppingListRecipeRequestToJSONTyped(json, false);
}

export function PatchedShoppingListRecipeRequestToJSONTyped(value?: PatchedShoppingListRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'recipe': value['recipe'],
        'mealplan': value['mealplan'],
        'servings': value['servings'],
        'id': value['id'],
    };
}

