/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HouseholdRequest } from './HouseholdRequest';
import {
    HouseholdRequestFromJSON,
    HouseholdRequestFromJSONTyped,
    HouseholdRequestToJSON,
    HouseholdRequestToJSONTyped,
} from './HouseholdRequest';

/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface PatchedInventoryLocationRequest
 */
export interface PatchedInventoryLocationRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedInventoryLocationRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedInventoryLocationRequest
     */
    isFreezer?: boolean;
    /**
     * 
     * @type {HouseholdRequest}
     * @memberof PatchedInventoryLocationRequest
     */
    household?: HouseholdRequest;
    /**
     * 
     * @type {number}
     * @memberof PatchedInventoryLocationRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedInventoryLocationRequest interface.
 */
export function instanceOfPatchedInventoryLocationRequest(value: object): value is PatchedInventoryLocationRequest {
    return true;
}

export function PatchedInventoryLocationRequestFromJSON(json: any): PatchedInventoryLocationRequest {
    return PatchedInventoryLocationRequestFromJSONTyped(json, false);
}

export function PatchedInventoryLocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedInventoryLocationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'isFreezer': json['is_freezer'] == null ? undefined : json['is_freezer'],
        'household': json['household'] == null ? undefined : HouseholdRequestFromJSON(json['household']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedInventoryLocationRequestToJSON(json: any): PatchedInventoryLocationRequest {
    return PatchedInventoryLocationRequestToJSONTyped(json, false);
}

export function PatchedInventoryLocationRequestToJSONTyped(value?: PatchedInventoryLocationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'is_freezer': value['isFreezer'],
        'household': HouseholdRequestToJSON(value['household']),
        'id': value['id'],
    };
}

