/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeReferenceSchema } from './RecipeReferenceSchema';
import {
    RecipeReferenceSchemaFromJSON,
    RecipeReferenceSchemaFromJSONTyped,
    RecipeReferenceSchemaToJSON,
    RecipeReferenceSchemaToJSONTyped,
} from './RecipeReferenceSchema';
import type { RecipeDietStatusEnum } from './RecipeDietStatusEnum';
import {
    RecipeDietStatusEnumFromJSON,
    RecipeDietStatusEnumFromJSONTyped,
    RecipeDietStatusEnumToJSON,
    RecipeDietStatusEnumToJSONTyped,
} from './RecipeDietStatusEnum';

/**
 * 
 * @export
 * @interface PlanningMealSchema
 */
export interface PlanningMealSchema {
    /**
     * 
     * @type {number}
     * @memberof PlanningMealSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PlanningMealSchema
     */
    title: string;
    /**
     * 
     * @type {RecipeReferenceSchema}
     * @memberof PlanningMealSchema
     */
    recipe: RecipeReferenceSchema | null;
    /**
     * 
     * @type {RecipeReferenceSchema}
     * @memberof PlanningMealSchema
     */
    mealType: RecipeReferenceSchema;
    /**
     * 
     * @type {number}
     * @memberof PlanningMealSchema
     */
    course: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlanningMealSchema
     */
    courseName: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlanningMealSchema
     */
    servings: string;
    /**
     * 
     * @type {Date}
     * @memberof PlanningMealSchema
     */
    fromDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlanningMealSchema
     */
    toDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PlanningMealSchema
     */
    note: string;
    /**
     * 
     * @type {string}
     * @memberof PlanningMealSchema
     */
    sourceUrl: string;
    /**
     * 
     * @type {RecipeDietStatusEnum}
     * @memberof PlanningMealSchema
     */
    dietStatus: RecipeDietStatusEnum;
}



/**
 * Check if a given object implements the PlanningMealSchema interface.
 */
export function instanceOfPlanningMealSchema(value: object): value is PlanningMealSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    if (!('mealType' in value) || value['mealType'] === undefined) return false;
    if (!('course' in value) || value['course'] === undefined) return false;
    if (!('courseName' in value) || value['courseName'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('fromDate' in value) || value['fromDate'] === undefined) return false;
    if (!('toDate' in value) || value['toDate'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    if (!('dietStatus' in value) || value['dietStatus'] === undefined) return false;
    return true;
}

export function PlanningMealSchemaFromJSON(json: any): PlanningMealSchema {
    return PlanningMealSchemaFromJSONTyped(json, false);
}

export function PlanningMealSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanningMealSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'recipe': RecipeReferenceSchemaFromJSON(json['recipe']),
        'mealType': RecipeReferenceSchemaFromJSON(json['meal_type']),
        'course': json['course'],
        'courseName': json['course_name'],
        'servings': json['servings'],
        'fromDate': (new Date(json['from_date'])),
        'toDate': (new Date(json['to_date'])),
        'note': json['note'],
        'sourceUrl': json['source_url'],
        'dietStatus': RecipeDietStatusEnumFromJSON(json['diet_status']),
    };
}

export function PlanningMealSchemaToJSON(json: any): PlanningMealSchema {
    return PlanningMealSchemaToJSONTyped(json, false);
}

export function PlanningMealSchemaToJSONTyped(value?: PlanningMealSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'recipe': RecipeReferenceSchemaToJSON(value['recipe']),
        'meal_type': RecipeReferenceSchemaToJSON(value['mealType']),
        'course': value['course'],
        'course_name': value['courseName'],
        'servings': value['servings'],
        'from_date': value['fromDate'].toISOString(),
        'to_date': value['toDate'].toISOString(),
        'note': value['note'],
        'source_url': value['sourceUrl'],
        'diet_status': RecipeDietStatusEnumToJSON(value['dietStatus']),
    };
}

