/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreparationItemSchema } from './PreparationItemSchema';
import {
    PreparationItemSchemaFromJSON,
    PreparationItemSchemaFromJSONTyped,
    PreparationItemSchemaToJSON,
    PreparationItemSchemaToJSONTyped,
} from './PreparationItemSchema';

/**
 * 
 * @export
 * @interface PreparationSchema
 */
export interface PreparationSchema {
    /**
     * 
     * @type {number}
     * @memberof PreparationSchema
     */
    serviceId: number;
    /**
     * 
     * @type {string}
     * @memberof PreparationSchema
     */
    state: string;
    /**
     * 
     * @type {boolean}
     * @memberof PreparationSchema
     */
    canEdit: boolean;
    /**
     * 
     * @type {string}
     * @memberof PreparationSchema
     */
    revision: string;
    /**
     * 
     * @type {Array<PreparationItemSchema>}
     * @memberof PreparationSchema
     */
    items: Array<PreparationItemSchema>;
}

/**
 * Check if a given object implements the PreparationSchema interface.
 */
export function instanceOfPreparationSchema(value: object): value is PreparationSchema {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PreparationSchemaFromJSON(json: any): PreparationSchema {
    return PreparationSchemaFromJSONTyped(json, false);
}

export function PreparationSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparationSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'state': json['state'],
        'canEdit': json['can_edit'],
        'revision': json['revision'],
        'items': ((json['items'] as Array<any>).map(PreparationItemSchemaFromJSON)),
    };
}

export function PreparationSchemaToJSON(json: any): PreparationSchema {
    return PreparationSchemaToJSONTyped(json, false);
}

export function PreparationSchemaToJSONTyped(value?: PreparationSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'state': value['state'],
        'can_edit': value['canEdit'],
        'revision': value['revision'],
        'items': ((value['items'] as Array<any>).map(PreparationItemSchemaToJSON)),
    };
}

