/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreparationWriteRequest
 */
export interface PreparationWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof PreparationWriteRequest
     */
    item: number;
    /**
     * 
     * @type {boolean}
     * @memberof PreparationWriteRequest
     */
    checked: boolean;
    /**
     * 
     * @type {string}
     * @memberof PreparationWriteRequest
     */
    revision: string;
}

/**
 * Check if a given object implements the PreparationWriteRequest interface.
 */
export function instanceOfPreparationWriteRequest(value: object): value is PreparationWriteRequest {
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('checked' in value) || value['checked'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function PreparationWriteRequestFromJSON(json: any): PreparationWriteRequest {
    return PreparationWriteRequestFromJSONTyped(json, false);
}

export function PreparationWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparationWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'],
        'checked': json['checked'],
        'revision': json['revision'],
    };
}

export function PreparationWriteRequestToJSON(json: any): PreparationWriteRequest {
    return PreparationWriteRequestToJSONTyped(json, false);
}

export function PreparationWriteRequestToJSONTyped(value?: PreparationWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'],
        'checked': value['checked'],
        'revision': value['revision'],
    };
}

