/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceSummarySchema
 */
export interface PriceSummarySchema {
    /**
     * 
     * @type {number}
     * @memberof PriceSummarySchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PriceSummarySchema
     */
    amount: string;
    /**
     * 
     * @type {boolean}
     * @memberof PriceSummarySchema
     */
    explicitFree: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PriceSummarySchema
     */
    validFrom: Date;
}

/**
 * Check if a given object implements the PriceSummarySchema interface.
 */
export function instanceOfPriceSummarySchema(value: object): value is PriceSummarySchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('explicitFree' in value) || value['explicitFree'] === undefined) return false;
    if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
    return true;
}

export function PriceSummarySchemaFromJSON(json: any): PriceSummarySchema {
    return PriceSummarySchemaFromJSONTyped(json, false);
}

export function PriceSummarySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceSummarySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'explicitFree': json['explicit_free'],
        'validFrom': (new Date(json['valid_from'])),
    };
}

export function PriceSummarySchemaToJSON(json: any): PriceSummarySchema {
    return PriceSummarySchemaToJSONTyped(json, false);
}

export function PriceSummarySchemaToJSONTyped(value?: PriceSummarySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'explicit_free': value['explicitFree'],
        'valid_from': value['validFrom'].toISOString(),
    };
}

