/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceHistoryItemSchema } from './PriceHistoryItemSchema';
import {
    PriceHistoryItemSchemaFromJSON,
    PriceHistoryItemSchemaFromJSONTyped,
    PriceHistoryItemSchemaToJSON,
    PriceHistoryItemSchemaToJSONTyped,
} from './PriceHistoryItemSchema';

/**
 * 
 * @export
 * @interface PriceHistorySchema
 */
export interface PriceHistorySchema {
    /**
     * 
     * @type {number}
     * @memberof PriceHistorySchema
     */
    _package: number;
    /**
     * 
     * @type {string}
     * @memberof PriceHistorySchema
     */
    currency: string;
    /**
     * 
     * @type {Date}
     * @memberof PriceHistorySchema
     */
    asOf: Date;
    /**
     * 
     * @type {number}
     * @memberof PriceHistorySchema
     */
    currentPriceId: number | null;
    /**
     * 
     * @type {number}
     * @memberof PriceHistorySchema
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof PriceHistorySchema
     */
    nextOffset: number | null;
    /**
     * 
     * @type {Array<PriceHistoryItemSchema>}
     * @memberof PriceHistorySchema
     */
    items: Array<PriceHistoryItemSchema>;
}

/**
 * Check if a given object implements the PriceHistorySchema interface.
 */
export function instanceOfPriceHistorySchema(value: object): value is PriceHistorySchema {
    if (!('_package' in value) || value['_package'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('asOf' in value) || value['asOf'] === undefined) return false;
    if (!('currentPriceId' in value) || value['currentPriceId'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PriceHistorySchemaFromJSON(json: any): PriceHistorySchema {
    return PriceHistorySchemaFromJSONTyped(json, false);
}

export function PriceHistorySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceHistorySchema {
    if (json == null) {
        return json;
    }
    return {
        
        '_package': json['package'],
        'currency': json['currency'],
        'asOf': (new Date(json['as_of'])),
        'currentPriceId': json['current_price_id'],
        'count': json['count'],
        'nextOffset': json['next_offset'],
        'items': ((json['items'] as Array<any>).map(PriceHistoryItemSchemaFromJSON)),
    };
}

export function PriceHistorySchemaToJSON(json: any): PriceHistorySchema {
    return PriceHistorySchemaToJSONTyped(json, false);
}

export function PriceHistorySchemaToJSONTyped(value?: PriceHistorySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'package': value['_package'],
        'currency': value['currency'],
        'as_of': value['asOf'].toISOString(),
        'current_price_id': value['currentPriceId'],
        'count': value['count'],
        'next_offset': value['nextOffset'],
        'items': ((value['items'] as Array<any>).map(PriceHistoryItemSchemaToJSON)),
    };
}

