/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `` - 
 * * `net` - net
 * * `gross` - gross
 * @export
 */
export const PricePolicyEnum = {
    Net: 'net',
    Gross: 'gross'
} as const;
export type PricePolicyEnum = typeof PricePolicyEnum[keyof typeof PricePolicyEnum];


export function instanceOfPricePolicyEnum(value: any): boolean {
    for (const key in PricePolicyEnum) {
        if (Object.prototype.hasOwnProperty.call(PricePolicyEnum, key)) {
            if (PricePolicyEnum[key as keyof typeof PricePolicyEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PricePolicyEnumFromJSON(json: any): PricePolicyEnum {
    return PricePolicyEnumFromJSONTyped(json, false);
}

export function PricePolicyEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricePolicyEnum {
    return json as PricePolicyEnum;
}

export function PricePolicyEnumToJSON(value?: PricePolicyEnum | null): any {
    return value as any;
}

export function PricePolicyEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PricePolicyEnum {
    return value as PricePolicyEnum;
}

