/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrintMenuWriteSchemaRequest
 */
export interface PrintMenuWriteSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof PrintMenuWriteSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PrintMenuWriteSchemaRequest
     */
    mealPlanIds: Array<number>;
    /**
     * Plantilla visible cuya portada se usará en el documento.
     * @type {number}
     * @memberof PrintMenuWriteSchemaRequest
     */
    templateId?: number;
}

/**
 * Check if a given object implements the PrintMenuWriteSchemaRequest interface.
 */
export function instanceOfPrintMenuWriteSchemaRequest(value: object): value is PrintMenuWriteSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mealPlanIds' in value) || value['mealPlanIds'] === undefined) return false;
    return true;
}

export function PrintMenuWriteSchemaRequestFromJSON(json: any): PrintMenuWriteSchemaRequest {
    return PrintMenuWriteSchemaRequestFromJSONTyped(json, false);
}

export function PrintMenuWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrintMenuWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'mealPlanIds': json['meal_plan_ids'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
    };
}

export function PrintMenuWriteSchemaRequestToJSON(json: any): PrintMenuWriteSchemaRequest {
    return PrintMenuWriteSchemaRequestToJSONTyped(json, false);
}

export function PrintMenuWriteSchemaRequestToJSONTyped(value?: PrintMenuWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'meal_plan_ids': value['mealPlanIds'],
        'template_id': value['templateId'],
    };
}

