/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionWriteSchemaActionEnum } from './ProductionWriteSchemaActionEnum';
import {
    ProductionWriteSchemaActionEnumFromJSON,
    ProductionWriteSchemaActionEnumFromJSONTyped,
    ProductionWriteSchemaActionEnumToJSON,
    ProductionWriteSchemaActionEnumToJSONTyped,
} from './ProductionWriteSchemaActionEnum';
import type { ProductionUsageSchemaRequest } from './ProductionUsageSchemaRequest';
import {
    ProductionUsageSchemaRequestFromJSON,
    ProductionUsageSchemaRequestFromJSONTyped,
    ProductionUsageSchemaRequestToJSON,
    ProductionUsageSchemaRequestToJSONTyped,
} from './ProductionUsageSchemaRequest';

/**
 * 
 * @export
 * @interface ProductionWriteSchemaRequest
 */
export interface ProductionWriteSchemaRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductionWriteSchemaRequest
     */
    servicePlan?: number;
    /**
     * 
     * @type {ProductionWriteSchemaActionEnum}
     * @memberof ProductionWriteSchemaRequest
     */
    action?: ProductionWriteSchemaActionEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductionWriteSchemaRequest
     */
    idempotencyKey?: string;
    /**
     * 
     * @type {Array<ProductionUsageSchemaRequest>}
     * @memberof ProductionWriteSchemaRequest
     */
    usages?: Array<ProductionUsageSchemaRequest>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProductionWriteSchemaRequest
     */
    recipeIds?: Array<number>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ProductionWriteSchemaRequest
     */
    edges?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof ProductionWriteSchemaRequest
     */
    start?: string;
}



/**
 * Check if a given object implements the ProductionWriteSchemaRequest interface.
 */
export function instanceOfProductionWriteSchemaRequest(value: object): value is ProductionWriteSchemaRequest {
    return true;
}

export function ProductionWriteSchemaRequestFromJSON(json: any): ProductionWriteSchemaRequest {
    return ProductionWriteSchemaRequestFromJSONTyped(json, false);
}

export function ProductionWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'servicePlan': json['service_plan'] == null ? undefined : json['service_plan'],
        'action': json['action'] == null ? undefined : ProductionWriteSchemaActionEnumFromJSON(json['action']),
        'idempotencyKey': json['idempotency_key'] == null ? undefined : json['idempotency_key'],
        'usages': json['usages'] == null ? undefined : ((json['usages'] as Array<any>).map(ProductionUsageSchemaRequestFromJSON)),
        'recipeIds': json['recipe_ids'] == null ? undefined : json['recipe_ids'],
        'edges': json['edges'] == null ? undefined : json['edges'],
        'start': json['start'] == null ? undefined : json['start'],
    };
}

export function ProductionWriteSchemaRequestToJSON(json: any): ProductionWriteSchemaRequest {
    return ProductionWriteSchemaRequestToJSONTyped(json, false);
}

export function ProductionWriteSchemaRequestToJSONTyped(value?: ProductionWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_plan': value['servicePlan'],
        'action': ProductionWriteSchemaActionEnumToJSON(value['action']),
        'idempotency_key': value['idempotencyKey'],
        'usages': value['usages'] == null ? undefined : ((value['usages'] as Array<any>).map(ProductionUsageSchemaRequestToJSON)),
        'recipe_ids': value['recipeIds'],
        'edges': value['edges'],
        'start': value['start'],
    };
}

