/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyConversionSchema } from './PropertyConversionSchema';
import {
    PropertyConversionSchemaFromJSON,
    PropertyConversionSchemaFromJSONTyped,
    PropertyConversionSchemaToJSON,
    PropertyConversionSchemaToJSONTyped,
} from './PropertyConversionSchema';
import type { PropertyNamedObjectSchema } from './PropertyNamedObjectSchema';
import {
    PropertyNamedObjectSchemaFromJSON,
    PropertyNamedObjectSchemaFromJSONTyped,
    PropertyNamedObjectSchemaToJSON,
    PropertyNamedObjectSchemaToJSONTyped,
} from './PropertyNamedObjectSchema';

/**
 * 
 * @export
 * @interface PropertyFoodValueSchema
 */
export interface PropertyFoodValueSchema {
    /**
     * 
     * @type {number}
     * @memberof PropertyFoodValueSchema
     */
    id: number;
    /**
     * 
     * @type {PropertyNamedObjectSchema}
     * @memberof PropertyFoodValueSchema
     */
    food: PropertyNamedObjectSchema;
    /**
     * 
     * @type {number}
     * @memberof PropertyFoodValueSchema
     */
    value: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyFoodValueSchema
     */
    missingUnit?: boolean;
    /**
     * 
     * @type {PropertyConversionSchema}
     * @memberof PropertyFoodValueSchema
     */
    missingConversion?: PropertyConversionSchema;
}

/**
 * Check if a given object implements the PropertyFoodValueSchema interface.
 */
export function instanceOfPropertyFoodValueSchema(value: object): value is PropertyFoodValueSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function PropertyFoodValueSchemaFromJSON(json: any): PropertyFoodValueSchema {
    return PropertyFoodValueSchemaFromJSONTyped(json, false);
}

export function PropertyFoodValueSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyFoodValueSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'food': PropertyNamedObjectSchemaFromJSON(json['food']),
        'value': json['value'],
        'missingUnit': json['missing_unit'] == null ? undefined : json['missing_unit'],
        'missingConversion': json['missing_conversion'] == null ? undefined : PropertyConversionSchemaFromJSON(json['missing_conversion']),
    };
}

export function PropertyFoodValueSchemaToJSON(json: any): PropertyFoodValueSchema {
    return PropertyFoodValueSchemaToJSONTyped(json, false);
}

export function PropertyFoodValueSchemaToJSONTyped(value?: PropertyFoodValueSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'food': PropertyNamedObjectSchemaToJSON(value['food']),
        'value': value['value'],
        'missing_unit': value['missingUnit'],
        'missing_conversion': PropertyConversionSchemaToJSON(value['missingConversion']),
    };
}

