/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyNamedObjectSchema
 */
export interface PropertyNamedObjectSchema {
    /**
     * 
     * @type {number}
     * @memberof PropertyNamedObjectSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyNamedObjectSchema
     */
    name: string;
}

/**
 * Check if a given object implements the PropertyNamedObjectSchema interface.
 */
export function instanceOfPropertyNamedObjectSchema(value: object): value is PropertyNamedObjectSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PropertyNamedObjectSchemaFromJSON(json: any): PropertyNamedObjectSchema {
    return PropertyNamedObjectSchemaFromJSONTyped(json, false);
}

export function PropertyNamedObjectSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyNamedObjectSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PropertyNamedObjectSchemaToJSON(json: any): PropertyNamedObjectSchema {
    return PropertyNamedObjectSchemaToJSONTyped(json, false);
}

export function PropertyNamedObjectSchemaToJSONTyped(value?: PropertyNamedObjectSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

