/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface PropertyTypeRequest
 */
export interface PropertyTypeRequest {
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyTypeRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyTypeRequest
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyTypeRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeRequest
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyTypeRequest
     */
    openDataSlug?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeRequest
     */
    fdcId?: number | null;
}

/**
 * Check if a given object implements the PropertyTypeRequest interface.
 */
export function instanceOfPropertyTypeRequest(value: object): value is PropertyTypeRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PropertyTypeRequestFromJSON(json: any): PropertyTypeRequest {
    return PropertyTypeRequestFromJSONTyped(json, false);
}

export function PropertyTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'openDataSlug': json['open_data_slug'] == null ? undefined : json['open_data_slug'],
        'fdcId': json['fdc_id'] == null ? undefined : json['fdc_id'],
    };
}

export function PropertyTypeRequestToJSON(json: any): PropertyTypeRequest {
    return PropertyTypeRequestToJSONTyped(json, false);
}

export function PropertyTypeRequestToJSONTyped(value?: PropertyTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'unit': value['unit'],
        'description': value['description'],
        'order': value['order'],
        'open_data_slug': value['openDataSlug'],
        'fdc_id': value['fdcId'],
    };
}

