/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `gross` - Bruta
 * * `net_usable` - Neta útil
 * @export
 */
export const QuantityBasisEnum = {
    Gross: 'gross',
    NetUsable: 'net_usable'
} as const;
export type QuantityBasisEnum = typeof QuantityBasisEnum[keyof typeof QuantityBasisEnum];


export function instanceOfQuantityBasisEnum(value: any): boolean {
    for (const key in QuantityBasisEnum) {
        if (Object.prototype.hasOwnProperty.call(QuantityBasisEnum, key)) {
            if (QuantityBasisEnum[key as keyof typeof QuantityBasisEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QuantityBasisEnumFromJSON(json: any): QuantityBasisEnum {
    return QuantityBasisEnumFromJSONTyped(json, false);
}

export function QuantityBasisEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantityBasisEnum {
    return json as QuantityBasisEnum;
}

export function QuantityBasisEnumToJSON(value?: QuantityBasisEnum | null): any {
    return value as any;
}

export function QuantityBasisEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): QuantityBasisEnum {
    return value as QuantityBasisEnum;
}

