/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptReverseRequest
 */
export interface ReceiptReverseRequest {
    /**
     * 
     * @type {string}
     * @memberof ReceiptReverseRequest
     */
    idempotencyKey: string;
}

/**
 * Check if a given object implements the ReceiptReverseRequest interface.
 */
export function instanceOfReceiptReverseRequest(value: object): value is ReceiptReverseRequest {
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function ReceiptReverseRequestFromJSON(json: any): ReceiptReverseRequest {
    return ReceiptReverseRequestFromJSONTyped(json, false);
}

export function ReceiptReverseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptReverseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKey': json['idempotency_key'],
    };
}

export function ReceiptReverseRequestToJSON(json: any): ReceiptReverseRequest {
    return ReceiptReverseRequestToJSONTyped(json, false);
}

export function ReceiptReverseRequestToJSONTyped(value?: ReceiptReverseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotency_key': value['idempotencyKey'],
    };
}

