/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptWriteRequest
 */
export interface ReceiptWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof ReceiptWriteRequest
     */
    entry: number;
    /**
     * 
     * @type {string}
     * @memberof ReceiptWriteRequest
     */
    quantity: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptWriteRequest
     */
    idempotencyKey: string;
}

/**
 * Check if a given object implements the ReceiptWriteRequest interface.
 */
export function instanceOfReceiptWriteRequest(value: object): value is ReceiptWriteRequest {
    if (!('entry' in value) || value['entry'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function ReceiptWriteRequestFromJSON(json: any): ReceiptWriteRequest {
    return ReceiptWriteRequestFromJSONTyped(json, false);
}

export function ReceiptWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entry': json['entry'],
        'quantity': json['quantity'],
        'idempotencyKey': json['idempotency_key'],
    };
}

export function ReceiptWriteRequestToJSON(json: any): ReceiptWriteRequest {
    return ReceiptWriteRequestToJSONTyped(json, false);
}

export function ReceiptWriteRequestToJSONTyped(value?: ReceiptWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry': value['entry'],
        'quantity': value['quantity'],
        'idempotency_key': value['idempotencyKey'],
    };
}

