/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeBatchUpdateRequest
 */
export interface RecipeBatchUpdateRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    recipes: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    keywordsAdd: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    keywordsRemove: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    keywordsSet: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeBatchUpdateRequest
     */
    keywordsRemoveAll?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecipeBatchUpdateRequest
     */
    workingTime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeBatchUpdateRequest
     */
    waitingTime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeBatchUpdateRequest
     */
    servings?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeBatchUpdateRequest
     */
    servingsText?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeBatchUpdateRequest
     */
    _private?: boolean | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    sharedAdd: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    sharedRemove: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeBatchUpdateRequest
     */
    sharedSet: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeBatchUpdateRequest
     */
    sharedRemoveAll?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeBatchUpdateRequest
     */
    showIngredientOverview?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeBatchUpdateRequest
     */
    clearDescription?: boolean | null;
}

/**
 * Check if a given object implements the RecipeBatchUpdateRequest interface.
 */
export function instanceOfRecipeBatchUpdateRequest(value: object): value is RecipeBatchUpdateRequest {
    if (!('recipes' in value) || value['recipes'] === undefined) return false;
    if (!('keywordsAdd' in value) || value['keywordsAdd'] === undefined) return false;
    if (!('keywordsRemove' in value) || value['keywordsRemove'] === undefined) return false;
    if (!('keywordsSet' in value) || value['keywordsSet'] === undefined) return false;
    if (!('sharedAdd' in value) || value['sharedAdd'] === undefined) return false;
    if (!('sharedRemove' in value) || value['sharedRemove'] === undefined) return false;
    if (!('sharedSet' in value) || value['sharedSet'] === undefined) return false;
    return true;
}

export function RecipeBatchUpdateRequestFromJSON(json: any): RecipeBatchUpdateRequest {
    return RecipeBatchUpdateRequestFromJSONTyped(json, false);
}

export function RecipeBatchUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeBatchUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipes': json['recipes'],
        'keywordsAdd': json['keywords_add'],
        'keywordsRemove': json['keywords_remove'],
        'keywordsSet': json['keywords_set'],
        'keywordsRemoveAll': json['keywords_remove_all'] == null ? undefined : json['keywords_remove_all'],
        'workingTime': json['working_time'] == null ? undefined : json['working_time'],
        'waitingTime': json['waiting_time'] == null ? undefined : json['waiting_time'],
        'servings': json['servings'] == null ? undefined : json['servings'],
        'servingsText': json['servings_text'] == null ? undefined : json['servings_text'],
        '_private': json['private'] == null ? undefined : json['private'],
        'sharedAdd': json['shared_add'],
        'sharedRemove': json['shared_remove'],
        'sharedSet': json['shared_set'],
        'sharedRemoveAll': json['shared_remove_all'] == null ? undefined : json['shared_remove_all'],
        'showIngredientOverview': json['show_ingredient_overview'] == null ? undefined : json['show_ingredient_overview'],
        'clearDescription': json['clear_description'] == null ? undefined : json['clear_description'],
    };
}

export function RecipeBatchUpdateRequestToJSON(json: any): RecipeBatchUpdateRequest {
    return RecipeBatchUpdateRequestToJSONTyped(json, false);
}

export function RecipeBatchUpdateRequestToJSONTyped(value?: RecipeBatchUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipes': value['recipes'],
        'keywords_add': value['keywordsAdd'],
        'keywords_remove': value['keywordsRemove'],
        'keywords_set': value['keywordsSet'],
        'keywords_remove_all': value['keywordsRemoveAll'],
        'working_time': value['workingTime'],
        'waiting_time': value['waitingTime'],
        'servings': value['servings'],
        'servings_text': value['servingsText'],
        'private': value['_private'],
        'shared_add': value['sharedAdd'],
        'shared_remove': value['sharedRemove'],
        'shared_set': value['sharedSet'],
        'shared_remove_all': value['sharedRemoveAll'],
        'show_ingredient_overview': value['showIngredientOverview'],
        'clear_description': value['clearDescription'],
    };
}

