/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
    StatusEnumToJSONTyped,
} from './StatusEnum';
import type { CostLineSchema } from './CostLineSchema';
import {
    CostLineSchemaFromJSON,
    CostLineSchemaFromJSONTyped,
    CostLineSchemaToJSON,
    CostLineSchemaToJSONTyped,
} from './CostLineSchema';

/**
 * 
 * @export
 * @interface RecipeCostSchema
 */
export interface RecipeCostSchema {
    /**
     * 
     * @type {StatusEnum}
     * @memberof RecipeCostSchema
     */
    status: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    unrounded: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    display: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    knownSubtotal: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    total: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeCostSchema
     */
    warnings: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    baseServings: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    servings: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    perServing: string | null;
    /**
     * 
     * @type {Array<CostLineSchema>}
     * @memberof RecipeCostSchema
     */
    lines: Array<CostLineSchema>;
    /**
     * 
     * @type {string}
     * @memberof RecipeCostSchema
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof RecipeCostSchema
     */
    recipeId: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeCostSchema
     */
    savedRecipe: boolean;
}



/**
 * Check if a given object implements the RecipeCostSchema interface.
 */
export function instanceOfRecipeCostSchema(value: object): value is RecipeCostSchema {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('unrounded' in value) || value['unrounded'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('knownSubtotal' in value) || value['knownSubtotal'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('baseServings' in value) || value['baseServings'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('perServing' in value) || value['perServing'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('savedRecipe' in value) || value['savedRecipe'] === undefined) return false;
    return true;
}

export function RecipeCostSchemaFromJSON(json: any): RecipeCostSchema {
    return RecipeCostSchemaFromJSONTyped(json, false);
}

export function RecipeCostSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeCostSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusEnumFromJSON(json['status']),
        'unrounded': json['unrounded'],
        'display': json['display'],
        'knownSubtotal': json['known_subtotal'],
        'total': json['total'],
        'warnings': json['warnings'],
        'baseServings': json['base_servings'],
        'servings': json['servings'],
        'perServing': json['per_serving'],
        'lines': ((json['lines'] as Array<any>).map(CostLineSchemaFromJSON)),
        'currency': json['currency'],
        'recipeId': json['recipe_id'],
        'savedRecipe': json['saved_recipe'],
    };
}

export function RecipeCostSchemaToJSON(json: any): RecipeCostSchema {
    return RecipeCostSchemaToJSONTyped(json, false);
}

export function RecipeCostSchemaToJSONTyped(value?: RecipeCostSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusEnumToJSON(value['status']),
        'unrounded': value['unrounded'],
        'display': value['display'],
        'known_subtotal': value['knownSubtotal'],
        'total': value['total'],
        'warnings': value['warnings'],
        'base_servings': value['baseServings'],
        'servings': value['servings'],
        'per_serving': value['perServing'],
        'lines': ((value['lines'] as Array<any>).map(CostLineSchemaToJSON)),
        'currency': value['currency'],
        'recipe_id': value['recipeId'],
        'saved_recipe': value['savedRecipe'],
    };
}

