/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';

/**
 * 
 * @export
 * @interface RecipeYieldWriteSchemaRequest
 */
export interface RecipeYieldWriteSchemaRequest {
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof RecipeYieldWriteSchemaRequest
     */
    quantity: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {number}
     * @memberof RecipeYieldWriteSchemaRequest
     */
    unit: number;
}

/**
 * Check if a given object implements the RecipeYieldWriteSchemaRequest interface.
 */
export function instanceOfRecipeYieldWriteSchemaRequest(value: object): value is RecipeYieldWriteSchemaRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function RecipeYieldWriteSchemaRequestFromJSON(json: any): RecipeYieldWriteSchemaRequest {
    return RecipeYieldWriteSchemaRequestFromJSONTyped(json, false);
}

export function RecipeYieldWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeYieldWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['quantity']),
        'unit': json['unit'],
    };
}

export function RecipeYieldWriteSchemaRequestToJSON(json: any): RecipeYieldWriteSchemaRequest {
    return RecipeYieldWriteSchemaRequestToJSONTyped(json, false);
}

export function RecipeYieldWriteSchemaRequestToJSONTyped(value?: RecipeYieldWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['quantity']),
        'unit': value['unit'],
    };
}

