/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeShoppingUpdate
 */
export interface RecipeShoppingUpdate {
    /**
     * 
     * @type {number}
     * @memberof RecipeShoppingUpdate
     */
    readonly id: number;
    /**
     * 
     * @type {Array<number | null>}
     * @memberof RecipeShoppingUpdate
     */
    ingredients: Array<number | null>;
}

/**
 * Check if a given object implements the RecipeShoppingUpdate interface.
 */
export function instanceOfRecipeShoppingUpdate(value: object): value is RecipeShoppingUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    return true;
}

export function RecipeShoppingUpdateFromJSON(json: any): RecipeShoppingUpdate {
    return RecipeShoppingUpdateFromJSONTyped(json, false);
}

export function RecipeShoppingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeShoppingUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ingredients': json['ingredients'],
    };
}

export function RecipeShoppingUpdateToJSON(json: any): RecipeShoppingUpdate {
    return RecipeShoppingUpdateToJSONTyped(json, false);
}

export function RecipeShoppingUpdateToJSONTyped(value?: Omit<RecipeShoppingUpdate, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ingredients': value['ingredients'],
    };
}

