/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DietDeclarationSchema } from './DietDeclarationSchema';
import {
    DietDeclarationSchemaFromJSON,
    DietDeclarationSchemaFromJSONTyped,
    DietDeclarationSchemaToJSON,
    DietDeclarationSchemaToJSONTyped,
} from './DietDeclarationSchema';
import type { RecipeReferenceSchema } from './RecipeReferenceSchema';
import {
    RecipeReferenceSchemaFromJSON,
    RecipeReferenceSchemaFromJSONTyped,
    RecipeReferenceSchemaToJSON,
    RecipeReferenceSchemaToJSONTyped,
} from './RecipeReferenceSchema';
import type { GalleryImageSchema } from './GalleryImageSchema';
import {
    GalleryImageSchemaFromJSON,
    GalleryImageSchemaFromJSONTyped,
    GalleryImageSchemaToJSON,
    GalleryImageSchemaToJSONTyped,
} from './GalleryImageSchema';

/**
 * 
 * @export
 * @interface RecipeExtrasSchema
 */
export interface RecipeExtrasSchema {
    /**
     * 
     * @type {number}
     * @memberof RecipeExtrasSchema
     */
    recipeId: number;
    /**
     * 
     * @type {string}
     * @memberof RecipeExtrasSchema
     */
    revision: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeExtrasSchema
     */
    canEdit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeExtrasSchema
     */
    isFavorite: boolean;
    /**
     * 
     * @type {Array<GalleryImageSchema>}
     * @memberof RecipeExtrasSchema
     */
    gallery: Array<GalleryImageSchema>;
    /**
     * 
     * @type {Array<DietDeclarationSchema>}
     * @memberof RecipeExtrasSchema
     */
    diets: Array<DietDeclarationSchema>;
    /**
     * 
     * @type {RecipeReferenceSchema}
     * @memberof RecipeExtrasSchema
     */
    variantOf: RecipeReferenceSchema | null;
    /**
     * 
     * @type {Array<RecipeReferenceSchema>}
     * @memberof RecipeExtrasSchema
     */
    variants: Array<RecipeReferenceSchema>;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeExtrasSchema
     */
    variantsTruncated: boolean;
    /**
     * 
     * @type {string}
     * @memberof RecipeExtrasSchema
     */
    declaration: string;
}

/**
 * Check if a given object implements the RecipeExtrasSchema interface.
 */
export function instanceOfRecipeExtrasSchema(value: object): value is RecipeExtrasSchema {
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('isFavorite' in value) || value['isFavorite'] === undefined) return false;
    if (!('gallery' in value) || value['gallery'] === undefined) return false;
    if (!('diets' in value) || value['diets'] === undefined) return false;
    if (!('variantOf' in value) || value['variantOf'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    if (!('variantsTruncated' in value) || value['variantsTruncated'] === undefined) return false;
    if (!('declaration' in value) || value['declaration'] === undefined) return false;
    return true;
}

export function RecipeExtrasSchemaFromJSON(json: any): RecipeExtrasSchema {
    return RecipeExtrasSchemaFromJSONTyped(json, false);
}

export function RecipeExtrasSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeExtrasSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeId': json['recipe_id'],
        'revision': json['revision'],
        'canEdit': json['can_edit'],
        'isFavorite': json['is_favorite'],
        'gallery': ((json['gallery'] as Array<any>).map(GalleryImageSchemaFromJSON)),
        'diets': ((json['diets'] as Array<any>).map(DietDeclarationSchemaFromJSON)),
        'variantOf': RecipeReferenceSchemaFromJSON(json['variant_of']),
        'variants': ((json['variants'] as Array<any>).map(RecipeReferenceSchemaFromJSON)),
        'variantsTruncated': json['variants_truncated'],
        'declaration': json['declaration'],
    };
}

export function RecipeExtrasSchemaToJSON(json: any): RecipeExtrasSchema {
    return RecipeExtrasSchemaToJSONTyped(json, false);
}

export function RecipeExtrasSchemaToJSONTyped(value?: RecipeExtrasSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipe_id': value['recipeId'],
        'revision': value['revision'],
        'can_edit': value['canEdit'],
        'is_favorite': value['isFavorite'],
        'gallery': ((value['gallery'] as Array<any>).map(GalleryImageSchemaToJSON)),
        'diets': ((value['diets'] as Array<any>).map(DietDeclarationSchemaToJSON)),
        'variant_of': RecipeReferenceSchemaToJSON(value['variantOf']),
        'variants': ((value['variants'] as Array<any>).map(RecipeReferenceSchemaToJSON)),
        'variants_truncated': value['variantsTruncated'],
        'declaration': value['declaration'],
    };
}

