/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `unknown` - unknown
 * * `suitable` - suitable
 * * `unsuitable` - unsuitable
 * @export
 */
export const RecipeDietStatusEnum = {
    Unknown: 'unknown',
    Suitable: 'suitable',
    Unsuitable: 'unsuitable'
} as const;
export type RecipeDietStatusEnum = typeof RecipeDietStatusEnum[keyof typeof RecipeDietStatusEnum];


export function instanceOfRecipeDietStatusEnum(value: any): boolean {
    for (const key in RecipeDietStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(RecipeDietStatusEnum, key)) {
            if (RecipeDietStatusEnum[key as keyof typeof RecipeDietStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RecipeDietStatusEnumFromJSON(json: any): RecipeDietStatusEnum {
    return RecipeDietStatusEnumFromJSONTyped(json, false);
}

export function RecipeDietStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeDietStatusEnum {
    return json as RecipeDietStatusEnum;
}

export function RecipeDietStatusEnumToJSON(value?: RecipeDietStatusEnum | null): any {
    return value as any;
}

export function RecipeDietStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): RecipeDietStatusEnum {
    return value as RecipeDietStatusEnum;
}

