/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReservationMenusResponse
 */
export interface ReservationMenusResponse {
    /**
     * 
     * @type {Array<any>}
     * @memberof ReservationMenusResponse
     */
    results: Array<any>;
}

/**
 * Check if a given object implements the ReservationMenusResponse interface.
 */
export function instanceOfReservationMenusResponse(value: object): value is ReservationMenusResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ReservationMenusResponseFromJSON(json: any): ReservationMenusResponse {
    return ReservationMenusResponseFromJSONTyped(json, false);
}

export function ReservationMenusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationMenusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'],
    };
}

export function ReservationMenusResponseToJSON(json: any): ReservationMenusResponse {
    return ReservationMenusResponseToJSONTyped(json, false);
}

export function ReservationMenusResponseToJSONTyped(value?: ReservationMenusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'],
    };
}

