/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationResponse } from './ReservationResponse';
import {
    ReservationResponseFromJSON,
    ReservationResponseFromJSONTyped,
    ReservationResponseToJSON,
    ReservationResponseToJSONTyped,
} from './ReservationResponse';

/**
 * 
 * @export
 * @interface ReservationListResponse
 */
export interface ReservationListResponse {
    /**
     * 
     * @type {number}
     * @memberof ReservationListResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationListResponse
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationListResponse
     */
    limit: number;
    /**
     * 
     * @type {Array<ReservationResponse>}
     * @memberof ReservationListResponse
     */
    results: Array<ReservationResponse>;
    /**
     * 
     * @type {boolean}
     * @memberof ReservationListResponse
     */
    canOperate: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReservationListResponse
     */
    canManage: boolean;
}

/**
 * Check if a given object implements the ReservationListResponse interface.
 */
export function instanceOfReservationListResponse(value: object): value is ReservationListResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('canOperate' in value) || value['canOperate'] === undefined) return false;
    if (!('canManage' in value) || value['canManage'] === undefined) return false;
    return true;
}

export function ReservationListResponseFromJSON(json: any): ReservationListResponse {
    return ReservationListResponseFromJSONTyped(json, false);
}

export function ReservationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'offset': json['offset'],
        'limit': json['limit'],
        'results': ((json['results'] as Array<any>).map(ReservationResponseFromJSON)),
        'canOperate': json['can_operate'],
        'canManage': json['can_manage'],
    };
}

export function ReservationListResponseToJSON(json: any): ReservationListResponse {
    return ReservationListResponseToJSONTyped(json, false);
}

export function ReservationListResponseToJSONTyped(value?: ReservationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'offset': value['offset'],
        'limit': value['limit'],
        'results': ((value['results'] as Array<any>).map(ReservationResponseToJSON)),
        'can_operate': value['canOperate'],
        'can_manage': value['canManage'],
    };
}

