/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceActionResultSchema
 */
export interface ServiceActionResultSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceActionResultSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceActionResultSchema
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceActionResultSchema
     */
    covers: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceActionResultSchema
     */
    serviceDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceActionResultSchema
     */
    state: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceActionResultSchema
     */
    mealPlan: number | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceActionResultSchema
     */
    household: number | null;
    /**
     * Versioned historical service snapshot; schema_version is authoritative
     * @type {any}
     * @memberof ServiceActionResultSchema
     */
    snapshot: any | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceActionResultSchema
     */
    confirmedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceActionResultSchema
     */
    producedAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceActionResultSchema
     */
    createdBy: number;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceActionResultSchema
     */
    stockChanged: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceActionResultSchema
     */
    movementIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceActionResultSchema
     */
    reversalMovementIds?: Array<number>;
}

/**
 * Check if a given object implements the ServiceActionResultSchema interface.
 */
export function instanceOfServiceActionResultSchema(value: object): value is ServiceActionResultSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('covers' in value) || value['covers'] === undefined) return false;
    if (!('serviceDate' in value) || value['serviceDate'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('mealPlan' in value) || value['mealPlan'] === undefined) return false;
    if (!('household' in value) || value['household'] === undefined) return false;
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('producedAt' in value) || value['producedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('stockChanged' in value) || value['stockChanged'] === undefined) return false;
    return true;
}

export function ServiceActionResultSchemaFromJSON(json: any): ServiceActionResultSchema {
    return ServiceActionResultSchemaFromJSONTyped(json, false);
}

export function ServiceActionResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceActionResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'covers': json['covers'],
        'serviceDate': (json['service_date'] == null ? null : new Date(json['service_date'])),
        'state': json['state'],
        'mealPlan': json['meal_plan'],
        'household': json['household'],
        'snapshot': json['snapshot'],
        'confirmedAt': (json['confirmed_at'] == null ? null : new Date(json['confirmed_at'])),
        'producedAt': (json['produced_at'] == null ? null : new Date(json['produced_at'])),
        'createdBy': json['created_by'],
        'stockChanged': json['stock_changed'],
        'movementIds': json['movement_ids'] == null ? undefined : json['movement_ids'],
        'reversalMovementIds': json['reversal_movement_ids'] == null ? undefined : json['reversal_movement_ids'],
    };
}

export function ServiceActionResultSchemaToJSON(json: any): ServiceActionResultSchema {
    return ServiceActionResultSchemaToJSONTyped(json, false);
}

export function ServiceActionResultSchemaToJSONTyped(value?: ServiceActionResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'covers': value['covers'],
        'service_date': value['serviceDate'] == null ? value['serviceDate'] : value['serviceDate'].toISOString().substring(0,10),
        'state': value['state'],
        'meal_plan': value['mealPlan'],
        'household': value['household'],
        'snapshot': value['snapshot'],
        'confirmed_at': value['confirmedAt'] == null ? value['confirmedAt'] : value['confirmedAt'].toISOString(),
        'produced_at': value['producedAt'] == null ? value['producedAt'] : value['producedAt'].toISOString(),
        'created_by': value['createdBy'],
        'stock_changed': value['stockChanged'],
        'movement_ids': value['movementIds'],
        'reversal_movement_ids': value['reversalMovementIds'],
    };
}

