/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceCreateResultSchema
 */
export interface ServiceCreateResultSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceCreateResultSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateResultSchema
     */
    covers: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceCreateResultSchema
     */
    mealPlan: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateResultSchema
     */
    payment: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceCreateResultSchema
     */
    stockChanged: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateResultSchema
     */
    timezone: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceCreateResultSchema
     */
    serviceDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateResultSchema
     */
    state: string;
}

/**
 * Check if a given object implements the ServiceCreateResultSchema interface.
 */
export function instanceOfServiceCreateResultSchema(value: object): value is ServiceCreateResultSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('covers' in value) || value['covers'] === undefined) return false;
    if (!('mealPlan' in value) || value['mealPlan'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    if (!('stockChanged' in value) || value['stockChanged'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('serviceDate' in value) || value['serviceDate'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function ServiceCreateResultSchemaFromJSON(json: any): ServiceCreateResultSchema {
    return ServiceCreateResultSchemaFromJSONTyped(json, false);
}

export function ServiceCreateResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCreateResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'covers': json['covers'],
        'mealPlan': json['meal_plan'],
        'payment': json['payment'],
        'stockChanged': json['stock_changed'],
        'timezone': json['timezone'],
        'serviceDate': (new Date(json['service_date'])),
        'state': json['state'],
    };
}

export function ServiceCreateResultSchemaToJSON(json: any): ServiceCreateResultSchema {
    return ServiceCreateResultSchemaToJSONTyped(json, false);
}

export function ServiceCreateResultSchemaToJSONTyped(value?: ServiceCreateResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'covers': value['covers'],
        'meal_plan': value['mealPlan'],
        'payment': value['payment'],
        'stock_changed': value['stockChanged'],
        'timezone': value['timezone'],
        'service_date': value['serviceDate'].toISOString().substring(0,10),
        'state': value['state'],
    };
}

