/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionNeedSchema } from './ProductionNeedSchema';
import {
    ProductionNeedSchemaFromJSON,
    ProductionNeedSchemaFromJSONTyped,
    ProductionNeedSchemaToJSON,
    ProductionNeedSchemaToJSONTyped,
} from './ProductionNeedSchema';
import type { CostSheetSchema } from './CostSheetSchema';
import {
    CostSheetSchemaFromJSON,
    CostSheetSchemaFromJSONTyped,
    CostSheetSchemaToJSON,
    CostSheetSchemaToJSONTyped,
} from './CostSheetSchema';

/**
 * 
 * @export
 * @interface ServiceProductionSheetSchema
 */
export interface ServiceProductionSheetSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceProductionSheetSchema
     */
    servicePlan: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceProductionSheetSchema
     */
    state: string;
    /**
     * 
     * @type {Array<ProductionNeedSchema>}
     * @memberof ServiceProductionSheetSchema
     */
    needs: Array<ProductionNeedSchema>;
    /**
     * 
     * @type {CostSheetSchema}
     * @memberof ServiceProductionSheetSchema
     */
    cost: CostSheetSchema | null;
    /**
     * Warnings retained in historical snapshots
     * @type {Array<any>}
     * @memberof ServiceProductionSheetSchema
     */
    warnings: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceProductionSheetSchema
     */
    stockChanged: boolean;
}

/**
 * Check if a given object implements the ServiceProductionSheetSchema interface.
 */
export function instanceOfServiceProductionSheetSchema(value: object): value is ServiceProductionSheetSchema {
    if (!('servicePlan' in value) || value['servicePlan'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('needs' in value) || value['needs'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('stockChanged' in value) || value['stockChanged'] === undefined) return false;
    return true;
}

export function ServiceProductionSheetSchemaFromJSON(json: any): ServiceProductionSheetSchema {
    return ServiceProductionSheetSchemaFromJSONTyped(json, false);
}

export function ServiceProductionSheetSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceProductionSheetSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'servicePlan': json['service_plan'],
        'state': json['state'],
        'needs': ((json['needs'] as Array<any>).map(ProductionNeedSchemaFromJSON)),
        'cost': CostSheetSchemaFromJSON(json['cost']),
        'warnings': json['warnings'],
        'stockChanged': json['stock_changed'],
    };
}

export function ServiceProductionSheetSchemaToJSON(json: any): ServiceProductionSheetSchema {
    return ServiceProductionSheetSchemaToJSONTyped(json, false);
}

export function ServiceProductionSheetSchemaToJSONTyped(value?: ServiceProductionSheetSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_plan': value['servicePlan'],
        'state': value['state'],
        'needs': ((value['needs'] as Array<any>).map(ProductionNeedSchemaToJSON)),
        'cost': CostSheetSchemaToJSON(value['cost']),
        'warnings': value['warnings'],
        'stock_changed': value['stockChanged'],
    };
}

