/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeImportConversionSchemaRequestBaseAmount } from './ExchangeImportConversionSchemaRequestBaseAmount';
import {
    ExchangeImportConversionSchemaRequestBaseAmountFromJSON,
    ExchangeImportConversionSchemaRequestBaseAmountFromJSONTyped,
    ExchangeImportConversionSchemaRequestBaseAmountToJSON,
    ExchangeImportConversionSchemaRequestBaseAmountToJSONTyped,
} from './ExchangeImportConversionSchemaRequestBaseAmount';

/**
 * 
 * @export
 * @interface ServiceCreateSchemaRequest
 */
export interface ServiceCreateSchemaRequest {
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ServiceCreateSchemaRequest
     */
    covers?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ServiceCreateSchemaRequest
     */
    baseCovers?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ServiceCreateSchemaRequest
     */
    extra?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {ExchangeImportConversionSchemaRequestBaseAmount}
     * @memberof ServiceCreateSchemaRequest
     */
    cancelled?: ExchangeImportConversionSchemaRequestBaseAmount;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateSchemaRequest
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceCreateSchemaRequest
     */
    serviceDate: Date;
    /**
     * 
     * @type {number}
     * @memberof ServiceCreateSchemaRequest
     */
    recipe?: number | null;
}

/**
 * Check if a given object implements the ServiceCreateSchemaRequest interface.
 */
export function instanceOfServiceCreateSchemaRequest(value: object): value is ServiceCreateSchemaRequest {
    if (!('serviceDate' in value) || value['serviceDate'] === undefined) return false;
    return true;
}

export function ServiceCreateSchemaRequestFromJSON(json: any): ServiceCreateSchemaRequest {
    return ServiceCreateSchemaRequestFromJSONTyped(json, false);
}

export function ServiceCreateSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCreateSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'covers': json['covers'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['covers']),
        'baseCovers': json['base_covers'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['base_covers']),
        'extra': json['extra'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['extra']),
        'cancelled': json['cancelled'] == null ? undefined : ExchangeImportConversionSchemaRequestBaseAmountFromJSON(json['cancelled']),
        'title': json['title'] == null ? undefined : json['title'],
        'serviceDate': (new Date(json['service_date'])),
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
    };
}

export function ServiceCreateSchemaRequestToJSON(json: any): ServiceCreateSchemaRequest {
    return ServiceCreateSchemaRequestToJSONTyped(json, false);
}

export function ServiceCreateSchemaRequestToJSONTyped(value?: ServiceCreateSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'covers': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['covers']),
        'base_covers': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['baseCovers']),
        'extra': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['extra']),
        'cancelled': ExchangeImportConversionSchemaRequestBaseAmountToJSON(value['cancelled']),
        'title': value['title'],
        'service_date': value['serviceDate'].toISOString().substring(0,10),
        'recipe': value['recipe'],
    };
}

