/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceProductionResultSchema
 */
export interface ServiceProductionResultSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceProductionResultSchema
     */
    servicePlan: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceProductionResultSchema
     */
    state: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceProductionResultSchema
     */
    movementIds: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceProductionResultSchema
     */
    stockChanged: boolean;
    /**
     * Frozen versioned service snapshot
     * @type {any}
     * @memberof ServiceProductionResultSchema
     */
    snapshot: any | null;
}

/**
 * Check if a given object implements the ServiceProductionResultSchema interface.
 */
export function instanceOfServiceProductionResultSchema(value: object): value is ServiceProductionResultSchema {
    if (!('servicePlan' in value) || value['servicePlan'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('movementIds' in value) || value['movementIds'] === undefined) return false;
    if (!('stockChanged' in value) || value['stockChanged'] === undefined) return false;
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    return true;
}

export function ServiceProductionResultSchemaFromJSON(json: any): ServiceProductionResultSchema {
    return ServiceProductionResultSchemaFromJSONTyped(json, false);
}

export function ServiceProductionResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceProductionResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'servicePlan': json['service_plan'],
        'state': json['state'],
        'movementIds': json['movement_ids'],
        'stockChanged': json['stock_changed'],
        'snapshot': json['snapshot'],
    };
}

export function ServiceProductionResultSchemaToJSON(json: any): ServiceProductionResultSchema {
    return ServiceProductionResultSchemaToJSONTyped(json, false);
}

export function ServiceProductionResultSchemaToJSONTyped(value?: ServiceProductionResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_plan': value['servicePlan'],
        'state': value['state'],
        'movement_ids': value['movementIds'],
        'stock_changed': value['stockChanged'],
        'snapshot': value['snapshot'],
    };
}

