/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceActionWriteSchemaActionEnum } from './ServiceActionWriteSchemaActionEnum';
import {
    ServiceActionWriteSchemaActionEnumFromJSON,
    ServiceActionWriteSchemaActionEnumFromJSONTyped,
    ServiceActionWriteSchemaActionEnumToJSON,
    ServiceActionWriteSchemaActionEnumToJSONTyped,
} from './ServiceActionWriteSchemaActionEnum';

/**
 * 
 * @export
 * @interface ServiceActionWriteSchemaRequest
 */
export interface ServiceActionWriteSchemaRequest {
    /**
     * 
     * @type {ServiceActionWriteSchemaActionEnum}
     * @memberof ServiceActionWriteSchemaRequest
     */
    action: ServiceActionWriteSchemaActionEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceActionWriteSchemaRequest
     */
    idempotencyKey?: string;
}



/**
 * Check if a given object implements the ServiceActionWriteSchemaRequest interface.
 */
export function instanceOfServiceActionWriteSchemaRequest(value: object): value is ServiceActionWriteSchemaRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function ServiceActionWriteSchemaRequestFromJSON(json: any): ServiceActionWriteSchemaRequest {
    return ServiceActionWriteSchemaRequestFromJSONTyped(json, false);
}

export function ServiceActionWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceActionWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ServiceActionWriteSchemaActionEnumFromJSON(json['action']),
        'idempotencyKey': json['idempotency_key'] == null ? undefined : json['idempotency_key'],
    };
}

export function ServiceActionWriteSchemaRequestToJSON(json: any): ServiceActionWriteSchemaRequest {
    return ServiceActionWriteSchemaRequestToJSONTyped(json, false);
}

export function ServiceActionWriteSchemaRequestToJSONTyped(value?: ServiceActionWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ServiceActionWriteSchemaActionEnumToJSON(value['action']),
        'idempotency_key': value['idempotencyKey'],
    };
}

