/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingListRequest } from './ShoppingListRequest';
import {
    ShoppingListRequestFromJSON,
    ShoppingListRequestFromJSONTyped,
    ShoppingListRequestToJSON,
    ShoppingListRequestToJSONTyped,
} from './ShoppingListRequest';
import type { UnitRequest } from './UnitRequest';
import {
    UnitRequestFromJSON,
    UnitRequestFromJSONTyped,
    UnitRequestToJSON,
    UnitRequestToJSONTyped,
} from './UnitRequest';
import type { FoodShoppingRequest } from './FoodShoppingRequest';
import {
    FoodShoppingRequestFromJSON,
    FoodShoppingRequestFromJSONTyped,
    FoodShoppingRequestToJSON,
    FoodShoppingRequestToJSONTyped,
} from './FoodShoppingRequest';

/**
 * Adds nested create feature
 * @export
 * @interface ShoppingListEntryRequest
 */
export interface ShoppingListEntryRequest {
    /**
     * 
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    listRecipe?: number | null;
    /**
     * 
     * @type {Array<ShoppingListRequest>}
     * @memberof ShoppingListEntryRequest
     */
    shoppingLists?: Array<ShoppingListRequest>;
    /**
     * 
     * @type {FoodShoppingRequest}
     * @memberof ShoppingListEntryRequest
     */
    food: FoodShoppingRequest | null;
    /**
     * 
     * @type {UnitRequest}
     * @memberof ShoppingListEntryRequest
     */
    unit?: UnitRequest | null;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ShoppingListEntryRequest
     */
    checked?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    ingredient?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ShoppingListEntryRequest
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ShoppingListEntryRequest
     */
    delayUntil?: Date | null;
    /**
     * If a mealplan id is given try to find existing or create new ShoppingListRecipe with that meal plan and link entry to it
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    mealplanId?: number;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListEntryRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the ShoppingListEntryRequest interface.
 */
export function instanceOfShoppingListEntryRequest(value: object): value is ShoppingListEntryRequest {
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ShoppingListEntryRequestFromJSON(json: any): ShoppingListEntryRequest {
    return ShoppingListEntryRequestFromJSONTyped(json, false);
}

export function ShoppingListEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingListEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listRecipe': json['list_recipe'] == null ? undefined : json['list_recipe'],
        'shoppingLists': json['shopping_lists'] == null ? undefined : ((json['shopping_lists'] as Array<any>).map(ShoppingListRequestFromJSON)),
        'food': FoodShoppingRequestFromJSON(json['food']),
        'unit': json['unit'] == null ? undefined : UnitRequestFromJSON(json['unit']),
        'amount': json['amount'],
        'order': json['order'] == null ? undefined : json['order'],
        'checked': json['checked'] == null ? undefined : json['checked'],
        'ingredient': json['ingredient'] == null ? undefined : json['ingredient'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'delayUntil': json['delay_until'] == null ? undefined : (new Date(json['delay_until'])),
        'mealplanId': json['mealplan_id'] == null ? undefined : json['mealplan_id'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ShoppingListEntryRequestToJSON(json: any): ShoppingListEntryRequest {
    return ShoppingListEntryRequestToJSONTyped(json, false);
}

export function ShoppingListEntryRequestToJSONTyped(value?: ShoppingListEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list_recipe': value['listRecipe'],
        'shopping_lists': value['shoppingLists'] == null ? undefined : ((value['shoppingLists'] as Array<any>).map(ShoppingListRequestToJSON)),
        'food': FoodShoppingRequestToJSON(value['food']),
        'unit': UnitRequestToJSON(value['unit']),
        'amount': value['amount'],
        'order': value['order'],
        'checked': value['checked'],
        'ingredient': value['ingredient'],
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'delay_until': value['delayUntil'] == null ? value['delayUntil'] : value['delayUntil'].toISOString(),
        'mealplan_id': value['mealplanId'],
        'id': value['id'],
    };
}

