/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface ShoppingListRequest
 */
export interface ShoppingListRequest {
    /**
     * 
     * @type {string}
     * @memberof ShoppingListRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListRequest
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the ShoppingListRequest interface.
 */
export function instanceOfShoppingListRequest(value: object): value is ShoppingListRequest {
    return true;
}

export function ShoppingListRequestFromJSON(json: any): ShoppingListRequest {
    return ShoppingListRequestFromJSONTyped(json, false);
}

export function ShoppingListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ShoppingListRequestToJSON(json: any): ShoppingListRequest {
    return ShoppingListRequestToJSONTyped(json, false);
}

export function ShoppingListRequestToJSONTyped(value?: ShoppingListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
        'id': value['id'],
    };
}

