/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingListEntrySimpleCreateRequest } from './ShoppingListEntrySimpleCreateRequest';
import {
    ShoppingListEntrySimpleCreateRequestFromJSON,
    ShoppingListEntrySimpleCreateRequestFromJSONTyped,
    ShoppingListEntrySimpleCreateRequestToJSON,
    ShoppingListEntrySimpleCreateRequestToJSONTyped,
} from './ShoppingListEntrySimpleCreateRequest';

/**
 * 
 * @export
 * @interface ShoppingListEntryBulkCreateRequest
 */
export interface ShoppingListEntryBulkCreateRequest {
    /**
     * 
     * @type {Array<ShoppingListEntrySimpleCreateRequest>}
     * @memberof ShoppingListEntryBulkCreateRequest
     */
    entries: Array<ShoppingListEntrySimpleCreateRequest>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ShoppingListEntryBulkCreateRequest
     */
    shoppingListsIds?: Array<number>;
}

/**
 * Check if a given object implements the ShoppingListEntryBulkCreateRequest interface.
 */
export function instanceOfShoppingListEntryBulkCreateRequest(value: object): value is ShoppingListEntryBulkCreateRequest {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function ShoppingListEntryBulkCreateRequestFromJSON(json: any): ShoppingListEntryBulkCreateRequest {
    return ShoppingListEntryBulkCreateRequestFromJSONTyped(json, false);
}

export function ShoppingListEntryBulkCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingListEntryBulkCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(ShoppingListEntrySimpleCreateRequestFromJSON)),
        'shoppingListsIds': json['shopping_lists_ids'] == null ? undefined : json['shopping_lists_ids'],
    };
}

export function ShoppingListEntryBulkCreateRequestToJSON(json: any): ShoppingListEntryBulkCreateRequest {
    return ShoppingListEntryBulkCreateRequestToJSONTyped(json, false);
}

export function ShoppingListEntryBulkCreateRequestToJSONTyped(value?: ShoppingListEntryBulkCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(ShoppingListEntrySimpleCreateRequestToJSON)),
        'shopping_lists_ids': value['shoppingListsIds'],
    };
}

