/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiProviderRequest } from './AiProviderRequest';
import {
    AiProviderRequestFromJSON,
    AiProviderRequestFromJSONTyped,
    AiProviderRequestToJSON,
    AiProviderRequestToJSONTyped,
} from './AiProviderRequest';
import type { FoodInheritFieldRequest } from './FoodInheritFieldRequest';
import {
    FoodInheritFieldRequestFromJSON,
    FoodInheritFieldRequestFromJSONTyped,
    FoodInheritFieldRequestToJSON,
    FoodInheritFieldRequestToJSONTyped,
} from './FoodInheritFieldRequest';
import type { SpaceNavTextColorEnum } from './SpaceNavTextColorEnum';
import {
    SpaceNavTextColorEnumFromJSON,
    SpaceNavTextColorEnumFromJSONTyped,
    SpaceNavTextColorEnumToJSON,
    SpaceNavTextColorEnumToJSONTyped,
} from './SpaceNavTextColorEnum';
import type { UserFileViewRequest } from './UserFileViewRequest';
import {
    UserFileViewRequestFromJSON,
    UserFileViewRequestFromJSONTyped,
    UserFileViewRequestToJSON,
    UserFileViewRequestToJSONTyped,
} from './UserFileViewRequest';
import type { SpaceThemeEnum } from './SpaceThemeEnum';
import {
    SpaceThemeEnumFromJSON,
    SpaceThemeEnumFromJSONTyped,
    SpaceThemeEnumToJSON,
    SpaceThemeEnumToJSONTyped,
} from './SpaceThemeEnum';

/**
 * Adds nested create feature
 * @export
 * @interface SpaceRequest
 */
export interface SpaceRequest {
    /**
     * 
     * @type {string}
     * @memberof SpaceRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceRequest
     */
    message?: string;
    /**
     * 
     * @type {Array<FoodInheritFieldRequest>}
     * @memberof SpaceRequest
     */
    foodInherit?: Array<FoodInheritFieldRequest>;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    image?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    navLogo?: UserFileViewRequest | null;
    /**
     * 
     * @type {SpaceThemeEnum}
     * @memberof SpaceRequest
     */
    spaceTheme?: SpaceThemeEnum;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    customSpaceTheme?: UserFileViewRequest | null;
    /**
     * 
     * @type {string}
     * @memberof SpaceRequest
     */
    navBgColor?: string;
    /**
     * 
     * @type {SpaceNavTextColorEnum}
     * @memberof SpaceRequest
     */
    navTextColor?: SpaceNavTextColorEnum;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor32?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor128?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor144?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor180?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor192?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColor512?: UserFileViewRequest | null;
    /**
     * 
     * @type {UserFileViewRequest}
     * @memberof SpaceRequest
     */
    logoColorSvg?: UserFileViewRequest | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceRequest
     */
    aiCreditsMonthly?: number;
    /**
     * 
     * @type {number}
     * @memberof SpaceRequest
     */
    aiCreditsBalance?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SpaceRequest
     */
    aiEnabled?: boolean;
    /**
     * 
     * @type {AiProviderRequest}
     * @memberof SpaceRequest
     */
    aiDefaultProvider?: AiProviderRequest | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpaceRequest
     */
    spaceSetupCompleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SpaceRequest
     */
    householdSetupCompleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SpaceRequest
     */
    id?: number;
}



/**
 * Check if a given object implements the SpaceRequest interface.
 */
export function instanceOfSpaceRequest(value: object): value is SpaceRequest {
    return true;
}

export function SpaceRequestFromJSON(json: any): SpaceRequest {
    return SpaceRequestFromJSONTyped(json, false);
}

export function SpaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'message': json['message'] == null ? undefined : json['message'],
        'foodInherit': json['food_inherit'] == null ? undefined : ((json['food_inherit'] as Array<any>).map(FoodInheritFieldRequestFromJSON)),
        'image': json['image'] == null ? undefined : UserFileViewRequestFromJSON(json['image']),
        'navLogo': json['nav_logo'] == null ? undefined : UserFileViewRequestFromJSON(json['nav_logo']),
        'spaceTheme': json['space_theme'] == null ? undefined : SpaceThemeEnumFromJSON(json['space_theme']),
        'customSpaceTheme': json['custom_space_theme'] == null ? undefined : UserFileViewRequestFromJSON(json['custom_space_theme']),
        'navBgColor': json['nav_bg_color'] == null ? undefined : json['nav_bg_color'],
        'navTextColor': json['nav_text_color'] == null ? undefined : SpaceNavTextColorEnumFromJSON(json['nav_text_color']),
        'logoColor32': json['logo_color_32'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_32']),
        'logoColor128': json['logo_color_128'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_128']),
        'logoColor144': json['logo_color_144'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_144']),
        'logoColor180': json['logo_color_180'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_180']),
        'logoColor192': json['logo_color_192'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_192']),
        'logoColor512': json['logo_color_512'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_512']),
        'logoColorSvg': json['logo_color_svg'] == null ? undefined : UserFileViewRequestFromJSON(json['logo_color_svg']),
        'aiCreditsMonthly': json['ai_credits_monthly'] == null ? undefined : json['ai_credits_monthly'],
        'aiCreditsBalance': json['ai_credits_balance'] == null ? undefined : json['ai_credits_balance'],
        'aiEnabled': json['ai_enabled'] == null ? undefined : json['ai_enabled'],
        'aiDefaultProvider': json['ai_default_provider'] == null ? undefined : AiProviderRequestFromJSON(json['ai_default_provider']),
        'spaceSetupCompleted': json['space_setup_completed'] == null ? undefined : json['space_setup_completed'],
        'householdSetupCompleted': json['household_setup_completed'] == null ? undefined : json['household_setup_completed'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SpaceRequestToJSON(json: any): SpaceRequest {
    return SpaceRequestToJSONTyped(json, false);
}

export function SpaceRequestToJSONTyped(value?: SpaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'message': value['message'],
        'food_inherit': value['foodInherit'] == null ? undefined : ((value['foodInherit'] as Array<any>).map(FoodInheritFieldRequestToJSON)),
        'image': UserFileViewRequestToJSON(value['image']),
        'nav_logo': UserFileViewRequestToJSON(value['navLogo']),
        'space_theme': SpaceThemeEnumToJSON(value['spaceTheme']),
        'custom_space_theme': UserFileViewRequestToJSON(value['customSpaceTheme']),
        'nav_bg_color': value['navBgColor'],
        'nav_text_color': SpaceNavTextColorEnumToJSON(value['navTextColor']),
        'logo_color_32': UserFileViewRequestToJSON(value['logoColor32']),
        'logo_color_128': UserFileViewRequestToJSON(value['logoColor128']),
        'logo_color_144': UserFileViewRequestToJSON(value['logoColor144']),
        'logo_color_180': UserFileViewRequestToJSON(value['logoColor180']),
        'logo_color_192': UserFileViewRequestToJSON(value['logoColor192']),
        'logo_color_512': UserFileViewRequestToJSON(value['logoColor512']),
        'logo_color_svg': UserFileViewRequestToJSON(value['logoColorSvg']),
        'ai_credits_monthly': value['aiCreditsMonthly'],
        'ai_credits_balance': value['aiCreditsBalance'],
        'ai_enabled': value['aiEnabled'],
        'ai_default_provider': AiProviderRequestToJSON(value['aiDefaultProvider']),
        'space_setup_completed': value['spaceSetupCompleted'],
        'household_setup_completed': value['householdSetupCompleted'],
        'id': value['id'],
    };
}

