/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MethodEnum } from './MethodEnum';
import {
    MethodEnumFromJSON,
    MethodEnumFromJSONTyped,
    MethodEnumToJSON,
    MethodEnumToJSONTyped,
} from './MethodEnum';
import type { ConnectorConfigUrl } from './ConnectorConfigUrl';
import {
    ConnectorConfigUrlFromJSON,
    ConnectorConfigUrlFromJSONTyped,
    ConnectorConfigUrlToJSON,
    ConnectorConfigUrlToJSONTyped,
} from './ConnectorConfigUrl';

/**
 * Adds nested create feature
 * @export
 * @interface Storage
 */
export interface Storage {
    /**
     * 
     * @type {number}
     * @memberof Storage
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Storage
     */
    name: string;
    /**
     * 
     * @type {MethodEnum}
     * @memberof Storage
     */
    method?: MethodEnum;
    /**
     * 
     * @type {string}
     * @memberof Storage
     */
    username?: string | null;
    /**
     * 
     * @type {ConnectorConfigUrl}
     * @memberof Storage
     */
    url?: ConnectorConfigUrl | null;
    /**
     * 
     * @type {string}
     * @memberof Storage
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof Storage
     */
    readonly createdBy: number;
}



/**
 * Check if a given object implements the Storage interface.
 */
export function instanceOfStorage(value: object): value is Storage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function StorageFromJSON(json: any): Storage {
    return StorageFromJSONTyped(json, false);
}

export function StorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Storage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'method': json['method'] == null ? undefined : MethodEnumFromJSON(json['method']),
        'username': json['username'] == null ? undefined : json['username'],
        'url': json['url'] == null ? undefined : ConnectorConfigUrlFromJSON(json['url']),
        'path': json['path'] == null ? undefined : json['path'],
        'createdBy': json['created_by'],
    };
}

export function StorageToJSON(json: any): Storage {
    return StorageToJSONTyped(json, false);
}

export function StorageToJSONTyped(value?: Omit<Storage, 'id'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'method': MethodEnumToJSON(value['method']),
        'username': value['username'],
        'url': ConnectorConfigUrlToJSON(value['url']),
        'path': value['path'],
    };
}

