/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MethodEnum } from './MethodEnum';
import {
    MethodEnumFromJSON,
    MethodEnumFromJSONTyped,
    MethodEnumToJSON,
    MethodEnumToJSONTyped,
} from './MethodEnum';
import type { ConnectorConfigUrl } from './ConnectorConfigUrl';
import {
    ConnectorConfigUrlFromJSON,
    ConnectorConfigUrlFromJSONTyped,
    ConnectorConfigUrlToJSON,
    ConnectorConfigUrlToJSONTyped,
} from './ConnectorConfigUrl';

/**
 * Adds nested create feature
 * @export
 * @interface StorageRequest
 */
export interface StorageRequest {
    /**
     * 
     * @type {string}
     * @memberof StorageRequest
     */
    name: string;
    /**
     * 
     * @type {MethodEnum}
     * @memberof StorageRequest
     */
    method?: MethodEnum;
    /**
     * 
     * @type {string}
     * @memberof StorageRequest
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StorageRequest
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StorageRequest
     */
    token?: string | null;
    /**
     * 
     * @type {ConnectorConfigUrl}
     * @memberof StorageRequest
     */
    url?: ConnectorConfigUrl | null;
    /**
     * 
     * @type {string}
     * @memberof StorageRequest
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof StorageRequest
     */
    id?: number;
}



/**
 * Check if a given object implements the StorageRequest interface.
 */
export function instanceOfStorageRequest(value: object): value is StorageRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StorageRequestFromJSON(json: any): StorageRequest {
    return StorageRequestFromJSONTyped(json, false);
}

export function StorageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'method': json['method'] == null ? undefined : MethodEnumFromJSON(json['method']),
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'token': json['token'] == null ? undefined : json['token'],
        'url': json['url'] == null ? undefined : ConnectorConfigUrlFromJSON(json['url']),
        'path': json['path'] == null ? undefined : json['path'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function StorageRequestToJSON(json: any): StorageRequest {
    return StorageRequestToJSONTyped(json, false);
}

export function StorageRequestToJSONTyped(value?: StorageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'method': MethodEnumToJSON(value['method']),
        'username': value['username'],
        'password': value['password'],
        'token': value['token'],
        'url': ConnectorConfigUrlToJSON(value['url']),
        'path': value['path'],
        'id': value['id'],
    };
}

