/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingListRequest } from './ShoppingListRequest';
import {
    ShoppingListRequestFromJSON,
    ShoppingListRequestFromJSONTyped,
    ShoppingListRequestToJSON,
    ShoppingListRequestToJSONTyped,
} from './ShoppingListRequest';

/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface SupermarketRequest
 */
export interface SupermarketRequest {
    /**
     * 
     * @type {string}
     * @memberof SupermarketRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SupermarketRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<ShoppingListRequest>}
     * @memberof SupermarketRequest
     */
    shoppingLists?: Array<ShoppingListRequest>;
    /**
     * 
     * @type {string}
     * @memberof SupermarketRequest
     */
    openDataSlug?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SupermarketRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the SupermarketRequest interface.
 */
export function instanceOfSupermarketRequest(value: object): value is SupermarketRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SupermarketRequestFromJSON(json: any): SupermarketRequest {
    return SupermarketRequestFromJSONTyped(json, false);
}

export function SupermarketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermarketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'shoppingLists': json['shopping_lists'] == null ? undefined : ((json['shopping_lists'] as Array<any>).map(ShoppingListRequestFromJSON)),
        'openDataSlug': json['open_data_slug'] == null ? undefined : json['open_data_slug'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SupermarketRequestToJSON(json: any): SupermarketRequest {
    return SupermarketRequestToJSONTyped(json, false);
}

export function SupermarketRequestToJSONTyped(value?: SupermarketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'shopping_lists': value['shoppingLists'] == null ? undefined : ((value['shoppingLists'] as Array<any>).map(ShoppingListRequestToJSON)),
        'open_data_slug': value['openDataSlug'],
        'id': value['id'],
    };
}

