/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateApplyResultSchema
 */
export interface TemplateApplyResultSchema {
    /**
     * 
     * @type {Array<number>}
     * @memberof TemplateApplyResultSchema
     */
    createdIds: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TemplateApplyResultSchema
     */
    replacedIds: Array<number>;
}

/**
 * Check if a given object implements the TemplateApplyResultSchema interface.
 */
export function instanceOfTemplateApplyResultSchema(value: object): value is TemplateApplyResultSchema {
    if (!('createdIds' in value) || value['createdIds'] === undefined) return false;
    if (!('replacedIds' in value) || value['replacedIds'] === undefined) return false;
    return true;
}

export function TemplateApplyResultSchemaFromJSON(json: any): TemplateApplyResultSchema {
    return TemplateApplyResultSchemaFromJSONTyped(json, false);
}

export function TemplateApplyResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateApplyResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'createdIds': json['created_ids'],
        'replacedIds': json['replaced_ids'],
    };
}

export function TemplateApplyResultSchemaToJSON(json: any): TemplateApplyResultSchema {
    return TemplateApplyResultSchemaToJSONTyped(json, false);
}

export function TemplateApplyResultSchemaToJSONTyped(value?: TemplateApplyResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_ids': value['createdIds'],
        'replaced_ids': value['replacedIds'],
    };
}

