/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateEntryWriteSchemaRequest } from './TemplateEntryWriteSchemaRequest';
import {
    TemplateEntryWriteSchemaRequestFromJSON,
    TemplateEntryWriteSchemaRequestFromJSONTyped,
    TemplateEntryWriteSchemaRequestToJSON,
    TemplateEntryWriteSchemaRequestToJSONTyped,
} from './TemplateEntryWriteSchemaRequest';

/**
 * 
 * @export
 * @interface TemplateWriteSchemaRequest
 */
export interface TemplateWriteSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateWriteSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TemplateWriteSchemaRequest
     */
    weeks: number;
    /**
     * 
     * @type {Array<TemplateEntryWriteSchemaRequest>}
     * @memberof TemplateWriteSchemaRequest
     */
    entries: Array<TemplateEntryWriteSchemaRequest>;
}

/**
 * Check if a given object implements the TemplateWriteSchemaRequest interface.
 */
export function instanceOfTemplateWriteSchemaRequest(value: object): value is TemplateWriteSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weeks' in value) || value['weeks'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function TemplateWriteSchemaRequestFromJSON(json: any): TemplateWriteSchemaRequest {
    return TemplateWriteSchemaRequestFromJSONTyped(json, false);
}

export function TemplateWriteSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateWriteSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'weeks': json['weeks'],
        'entries': ((json['entries'] as Array<any>).map(TemplateEntryWriteSchemaRequestFromJSON)),
    };
}

export function TemplateWriteSchemaRequestToJSON(json: any): TemplateWriteSchemaRequest {
    return TemplateWriteSchemaRequestToJSONTyped(json, false);
}

export function TemplateWriteSchemaRequestToJSONTyped(value?: TemplateWriteSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'weeks': value['weeks'],
        'entries': ((value['entries'] as Array<any>).map(TemplateEntryWriteSchemaRequestToJSON)),
    };
}

