/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateEntryWriteSchemaRequest } from './TemplateEntryWriteSchemaRequest';
import {
    TemplateEntryWriteSchemaRequestFromJSON,
    TemplateEntryWriteSchemaRequestFromJSONTyped,
    TemplateEntryWriteSchemaRequestToJSON,
    TemplateEntryWriteSchemaRequestToJSONTyped,
} from './TemplateEntryWriteSchemaRequest';

/**
 * 
 * @export
 * @interface TemplateUpdateSchemaRequest
 */
export interface TemplateUpdateSchemaRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateSchemaRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TemplateUpdateSchemaRequest
     */
    weeks: number;
    /**
     * 
     * @type {Array<TemplateEntryWriteSchemaRequest>}
     * @memberof TemplateUpdateSchemaRequest
     */
    entries: Array<TemplateEntryWriteSchemaRequest>;
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateSchemaRequest
     */
    revision: string;
}

/**
 * Check if a given object implements the TemplateUpdateSchemaRequest interface.
 */
export function instanceOfTemplateUpdateSchemaRequest(value: object): value is TemplateUpdateSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weeks' in value) || value['weeks'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function TemplateUpdateSchemaRequestFromJSON(json: any): TemplateUpdateSchemaRequest {
    return TemplateUpdateSchemaRequestFromJSONTyped(json, false);
}

export function TemplateUpdateSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateUpdateSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'weeks': json['weeks'],
        'entries': ((json['entries'] as Array<any>).map(TemplateEntryWriteSchemaRequestFromJSON)),
        'revision': json['revision'],
    };
}

export function TemplateUpdateSchemaRequestToJSON(json: any): TemplateUpdateSchemaRequest {
    return TemplateUpdateSchemaRequestToJSONTyped(json, false);
}

export function TemplateUpdateSchemaRequestToJSONTyped(value?: TemplateUpdateSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'weeks': value['weeks'],
        'entries': ((value['entries'] as Array<any>).map(TemplateEntryWriteSchemaRequestToJSON)),
        'revision': value['revision'],
    };
}

