/* tslint:disable */
/* eslint-disable */
/**
 * Cuaderno Cocina
 * Cuaderno Cocina API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateEntrySchema
 */
export interface TemplateEntrySchema {
    /**
     * 
     * @type {number}
     * @memberof TemplateEntrySchema
     */
    dayIndex: number;
    /**
     * 
     * @type {number}
     * @memberof TemplateEntrySchema
     */
    mealType: number;
    /**
     * 
     * @type {number}
     * @memberof TemplateEntrySchema
     */
    course?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TemplateEntrySchema
     */
    recipe?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    sourceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    servings: string;
    /**
     * 
     * @type {number}
     * @memberof TemplateEntrySchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    mealTypeName: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    courseName: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateEntrySchema
     */
    recipeName: string | null;
}

/**
 * Check if a given object implements the TemplateEntrySchema interface.
 */
export function instanceOfTemplateEntrySchema(value: object): value is TemplateEntrySchema {
    if (!('dayIndex' in value) || value['dayIndex'] === undefined) return false;
    if (!('mealType' in value) || value['mealType'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mealTypeName' in value) || value['mealTypeName'] === undefined) return false;
    if (!('courseName' in value) || value['courseName'] === undefined) return false;
    if (!('recipeName' in value) || value['recipeName'] === undefined) return false;
    return true;
}

export function TemplateEntrySchemaFromJSON(json: any): TemplateEntrySchema {
    return TemplateEntrySchemaFromJSONTyped(json, false);
}

export function TemplateEntrySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateEntrySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'dayIndex': json['day_index'],
        'mealType': json['meal_type'],
        'course': json['course'] == null ? undefined : json['course'],
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'title': json['title'] == null ? undefined : json['title'],
        'sourceUrl': json['source_url'] == null ? undefined : json['source_url'],
        'servings': json['servings'],
        'id': json['id'],
        'mealTypeName': json['meal_type_name'],
        'courseName': json['course_name'],
        'recipeName': json['recipe_name'],
    };
}

export function TemplateEntrySchemaToJSON(json: any): TemplateEntrySchema {
    return TemplateEntrySchemaToJSONTyped(json, false);
}

export function TemplateEntrySchemaToJSONTyped(value?: TemplateEntrySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day_index': value['dayIndex'],
        'meal_type': value['mealType'],
        'course': value['course'],
        'recipe': value['recipe'],
        'title': value['title'],
        'source_url': value['sourceUrl'],
        'servings': value['servings'],
        'id': value['id'],
        'meal_type_name': value['mealTypeName'],
        'course_name': value['courseName'],
        'recipe_name': value['recipeName'],
    };
}

