/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VisibleFoodSimple
 */
export interface VisibleFoodSimple {
    /**
     * 
     * @type {number}
     * @memberof VisibleFoodSimple
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof VisibleFoodSimple
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VisibleFoodSimple
     */
    pluralName?: string | null;
}

/**
 * Check if a given object implements the VisibleFoodSimple interface.
 */
export function instanceOfVisibleFoodSimple(value: object): value is VisibleFoodSimple {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function VisibleFoodSimpleFromJSON(json: any): VisibleFoodSimple {
    return VisibleFoodSimpleFromJSONTyped(json, false);
}

export function VisibleFoodSimpleFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisibleFoodSimple {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
    };
}

export function VisibleFoodSimpleToJSON(json: any): VisibleFoodSimple {
    return VisibleFoodSimpleToJSONTyped(json, false);
}

export function VisibleFoodSimpleToJSONTyped(value?: Omit<VisibleFoodSimple, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'plural_name': value['pluralName'],
    };
}

